//! Media generation tools over `stella-media`'s `MediaProvider` port, BYOK
//! like everything else: `generate_image` — and the `generate_video` /
//! `poll_video` pair when the key family has a video adapter — register only
//! when a capable provider key is present in the environment (`ZAI_API_KEY`
//! or `OPENAI_API_KEY`), mirroring the issue tools' conditional
//! registration — no key, no dead schema. `generate_svg` is client-side
//! (the model authors the SVG, the pipeline validates
//! and sanitizes it), so it needs no key and is always registered.
//!
//! Artifact discipline (`stella-media`): generated bytes are persisted
//! through the `ArtifactStore` into `.stella/artifacts/` — the single
//! allowed writer — and every tool reports the citation-ready path.
//!
//! Image and video submissions cross a host-owned spend gate before touching
//! the provider. Tool arguments cannot approve spend; callers without an
//! injected host gate deny by default. The registry constructs an approving
//! tool only in explicit [`HostDataIsolation::ProcessFree`] mode, which omits
//! process-launching/delegating built-ins from that executor. A submitted
//! video handle is persisted through the `JobStore` so a dropped session never
//! orphans a paid job; `poll_video` reconciles it live against the provider
//! (L-V3) and persists the finished artifact under the identity assigned at
//! submit.

use std::sync::Arc;

use async_trait::async_trait;
use serde_json::Value;
use stella_media::{
    CostDecision, DEFAULT_SVG_ATTEMPTS, DenyMediaSpendGate, ImageRequest, ImageSize, MediaKind,
    MediaOperationClaim, MediaOperationJournal, MediaOperationState, MediaProvider, MediaSpendGate,
    MediaSpendRequest, SvgPipeline, VideoRequest,
};
use stella_protocol::tool::{ToolOutput, ToolSchema};

use crate::registry::Tool;

mod authority;
mod backend;
mod poll_video;
pub(crate) use authority::process_free;
#[cfg(test)]
use authority::unix_now;
use authority::{
    DeniedOperationIds, open_jobs, open_store, operation_key, reconciliation_required,
    spend_denied, video_submitted,
};
pub use authority::{HostDataIsolation, HostMediaOperation, MediaOperationIdSource};
pub use backend::{MediaBackend, detect_media_backend};
pub use poll_video::PollVideo;

/// Default video duration when the model omits `duration_secs`.
const DEFAULT_VIDEO_DURATION_SECS: u32 = 5;

pub struct GenerateImage {
    provider: Arc<dyn MediaProvider>,
    spend_gate: Arc<dyn MediaSpendGate>,
    operation_ids: Arc<dyn MediaOperationIdSource>,
    operation_journal: Option<Arc<dyn MediaOperationJournal>>,
}

impl GenerateImage {
    /// Construct with the secure deny-by-default host gate.
    pub fn new(provider: Arc<dyn MediaProvider>) -> Self {
        Self {
            provider,
            spend_gate: Arc::new(DenyMediaSpendGate),
            // This source is paired only with the deny gate. Approving hosts
            // must inject a retry-stable logical invocation identity.
            operation_ids: Arc::new(DeniedOperationIds),
            operation_journal: None,
        }
    }

    /// Construct with host-owned approval and retry-stable invocation identity.
    pub(crate) fn with_host_context(
        provider: Arc<dyn MediaProvider>,
        spend_gate: Arc<dyn MediaSpendGate>,
        operation_ids: Arc<dyn MediaOperationIdSource>,
        operation_journal: Arc<dyn MediaOperationJournal>,
    ) -> Self {
        Self {
            provider,
            spend_gate,
            operation_ids,
            operation_journal: Some(operation_journal),
        }
    }
}

#[async_trait]
impl Tool for GenerateImage {
    fn schema(&self) -> ToolSchema {
        ToolSchema {
            name: "generate_image".into(),
            description: "Generate an image from a text prompt and save it under \
                          .stella/artifacts/. Returns the file path, model, and cost. \
                          Uses the configured BYOK image provider."
                .into(),
            input_schema: serde_json::json!({
                "type": "object",
                "properties": {
                    "prompt": {
                        "type": "string",
                        "description": "What to generate"
                    },
                    "size": {
                        "type": "string",
                        "description": "WIDTHxHEIGHT, e.g. 1024x1024 (the default)"
                    },
                    "label": {
                        "type": "string",
                        "description": "Short human label for the artifact filename"
                    }
                },
                "required": ["prompt"]
            }),
            read_only: false,
            speculation_safe: false,
        }
    }

    async fn execute(&self, input: &Value, root: &std::path::Path) -> ToolOutput {
        let Some(prompt) = input.get("prompt").and_then(|v| v.as_str()) else {
            return ToolOutput::Error {
                message: "`prompt` is required".into(),
            };
        };
        let size = match input.get("size").and_then(|v| v.as_str()) {
            Some(raw) => match raw.parse::<ImageSize>() {
                Ok(s) => s,
                Err(_) => {
                    return ToolOutput::Error {
                        message: format!(
                            "`size` must be WIDTHxHEIGHT (e.g. 1024x1024), got `{raw}`"
                        ),
                    };
                }
            },
            None => ImageSize::square(1024),
        };
        let mut request = ImageRequest::new(prompt, size);
        if let Some(label) = input.get("label").and_then(|v| v.as_str()) {
            // Otherwise keep the request's own prompt-derived label.
            request.label = label.to_string();
        }

        let (operation_id, expires_at) = operation_key(
            self.operation_ids.as_ref(),
            MediaKind::Image,
            self.provider.id(),
        );
        request.operation_id = Some(operation_id.clone());
        let Some(journal) = &self.operation_journal else {
            return ToolOutput::Error {
                message: "media spend requires host approval and a host operation journal".into(),
            };
        };
        match journal.claim(
            &operation_id,
            MediaKind::Image,
            self.provider.id(),
            expires_at,
        ) {
            Ok(MediaOperationClaim::New) => {}
            Ok(MediaOperationClaim::Existing(MediaOperationState::ImageCompleted {
                artifact_id,
            })) => {
                return ToolOutput::Ok {
                    content: format!("image operation already completed as `{artifact_id}`"),
                };
            }
            Ok(MediaOperationClaim::Existing(state)) => {
                return reconciliation_required(&operation_id, format!("state {state:?}"));
            }
            Ok(MediaOperationClaim::Expired) => {
                return reconciliation_required(&operation_id, "operation identity expired");
            }
            Err(error) => {
                return ToolOutput::Error {
                    message: format!("media_operation_journal_unavailable: {error}"),
                };
            }
        }
        let capabilities = self.provider.capabilities();
        let estimate = capabilities.estimate_image(request.n, request.size);
        let spend_request = MediaSpendRequest::new(
            operation_id.clone(),
            MediaKind::Image,
            self.provider.id(),
            estimate.as_ref().map(|estimate| estimate.estimated_usd),
            estimate.map_or_else(
                || {
                    format!(
                        "{} image(s) at {} (cost unavailable)",
                        request.n, request.size
                    )
                },
                |estimate| estimate.detail,
            ),
        );
        if self.spend_gate.authorize(&spend_request).await != CostDecision::Approve {
            if let Err(error) = journal.cancel(&operation_id) {
                return reconciliation_required(&operation_id, error);
            }
            return spend_denied(&spend_request);
        }

        let artifact = match self.provider.generate_image(request).await {
            Ok(a) => a,
            Err(error) => return reconciliation_required(&operation_id, error),
        };

        let store = match open_store(root) {
            Ok(s) => s,
            Err(error) => return reconciliation_required(&operation_id, format!("{error:?}")),
        };
        match store.save_artifact(&artifact) {
            Ok(saved) => {
                let content = format!(
                    "generated \"{}\" → {} ({}, model {}, ${:.4})",
                    saved.label, saved.path, size, artifact.model, artifact.cost_usd
                );
                if let Err(error) = journal.finalize(
                    &operation_id,
                    MediaOperationState::ImageCompleted {
                        artifact_id: saved.id.clone(),
                    },
                ) {
                    return reconciliation_required(&operation_id, error);
                }
                ToolOutput::Ok { content }
            }
            Err(error) => reconciliation_required(&operation_id, error),
        }
    }
}

pub struct GenerateVideo {
    provider: Arc<dyn MediaProvider>,
    spend_gate: Arc<dyn MediaSpendGate>,
    operation_ids: Arc<dyn MediaOperationIdSource>,
    operation_journal: Option<Arc<dyn MediaOperationJournal>>,
}

impl GenerateVideo {
    /// Construct with the secure deny-by-default host gate.
    pub fn new(provider: Arc<dyn MediaProvider>) -> Self {
        Self {
            provider,
            spend_gate: Arc::new(DenyMediaSpendGate),
            // This source is paired only with the deny gate. Approving hosts
            // must inject a retry-stable logical invocation identity.
            operation_ids: Arc::new(DeniedOperationIds),
            operation_journal: None,
        }
    }

    /// Construct with host-owned approval and retry-stable invocation identity.
    pub(crate) fn with_host_context(
        provider: Arc<dyn MediaProvider>,
        spend_gate: Arc<dyn MediaSpendGate>,
        operation_ids: Arc<dyn MediaOperationIdSource>,
        operation_journal: Arc<dyn MediaOperationJournal>,
    ) -> Self {
        Self {
            provider,
            spend_gate,
            operation_ids,
            operation_journal: Some(operation_journal),
        }
    }
}

#[async_trait]
impl Tool for GenerateVideo {
    fn schema(&self) -> ToolSchema {
        ToolSchema {
            name: "generate_video".into(),
            description: "Submit an asynchronous text-to-video job with the configured BYOK \
                          video provider; returns the job id to check with poll_video. Video \
                          costs real money and requires approval from the host runtime before \
                          provider submission."
                .into(),
            input_schema: serde_json::json!({
                "type": "object",
                "properties": {
                    "prompt": {
                        "type": "string",
                        "description": "What to generate"
                    },
                    "duration_secs": {
                        "type": "integer",
                        "description": "Target duration in seconds, at least 1 (default 5); \
                                        drives the cost estimate"
                    },
                    "label": {
                        "type": "string",
                        "description": "Short human label for the artifact filename"
                    }
                },
                "required": ["prompt"]
            }),
            read_only: false,
            speculation_safe: false,
        }
    }

    async fn execute(&self, input: &Value, root: &std::path::Path) -> ToolOutput {
        let Some(prompt) = input.get("prompt").and_then(|v| v.as_str()) else {
            return ToolOutput::Error {
                message: "`prompt` is required".into(),
            };
        };
        let duration_secs = match input.get("duration_secs") {
            None => DEFAULT_VIDEO_DURATION_SECS,
            Some(v) => match v.as_u64().and_then(|secs| u32::try_from(secs).ok()) {
                Some(secs) if secs >= 1 => secs,
                _ => {
                    return ToolOutput::Error {
                        message: "`duration_secs` must be a positive integer".into(),
                    };
                }
            },
        };
        let mut request = VideoRequest::new(prompt, duration_secs);
        if let Some(label) = input.get("label").and_then(|v| v.as_str()) {
            request.label = label.to_string();
        }

        let (operation_id, expires_at) = operation_key(
            self.operation_ids.as_ref(),
            MediaKind::Video,
            self.provider.id(),
        );
        request.operation_id = Some(operation_id.clone());
        let Some(journal) = &self.operation_journal else {
            return ToolOutput::Error {
                message: "media spend requires host approval and a host operation journal".into(),
            };
        };
        match journal.claim(
            &operation_id,
            MediaKind::Video,
            self.provider.id(),
            expires_at,
        ) {
            Ok(MediaOperationClaim::New) => {}
            Ok(MediaOperationClaim::Existing(MediaOperationState::VideoSubmitted {
                provider_job_id,
            })) => {
                return ToolOutput::Ok {
                    content: format!("video operation already exists as job `{provider_job_id}`"),
                };
            }
            Ok(MediaOperationClaim::Existing(MediaOperationState::VideoCompleted {
                provider_job_id,
            })) => {
                return ToolOutput::Ok {
                    content: format!(
                        "video operation already completed as job `{provider_job_id}`"
                    ),
                };
            }
            Ok(MediaOperationClaim::Existing(state)) => {
                return reconciliation_required(&operation_id, format!("state {state:?}"));
            }
            Ok(MediaOperationClaim::Expired) => {
                return reconciliation_required(&operation_id, "operation identity expired");
            }
            Err(error) => {
                return ToolOutput::Error {
                    message: format!("media_operation_journal_unavailable: {error}"),
                };
            }
        }
        let estimate = self.provider.capabilities().estimate_video(duration_secs);
        let spend_request = MediaSpendRequest::new(
            operation_id.clone(),
            MediaKind::Video,
            self.provider.id(),
            estimate.as_ref().map(|estimate| estimate.estimated_usd),
            estimate.map_or_else(
                || format!("{duration_secs}s video (cost unavailable)"),
                |estimate| estimate.detail,
            ),
        );
        if self.spend_gate.authorize(&spend_request).await != CostDecision::Approve {
            if let Err(error) = journal.cancel(&operation_id) {
                return reconciliation_required(&operation_id, error);
            }
            return spend_denied(&spend_request);
        }

        let job = match self.provider.generate_video(request).await {
            Ok(job) => job,
            Err(error) => return reconciliation_required(&operation_id, error),
        };
        // Persist the handle BEFORE reporting success — a paid job whose id
        // exists only in this reply would be orphaned by a dropped session.
        if let Err(error) = open_jobs(root).record(&job) {
            return reconciliation_required(&operation_id, error);
        }
        if let Err(error) = journal.finalize(
            &operation_id,
            MediaOperationState::VideoSubmitted {
                provider_job_id: job.provider_job_id.clone(),
            },
        ) {
            return reconciliation_required(&operation_id, error);
        }
        video_submitted(&job)
    }
}

pub struct GenerateSvg;

#[async_trait]
impl Tool for GenerateSvg {
    fn schema(&self) -> ToolSchema {
        ToolSchema {
            name: "generate_svg".into(),
            description: format!(
                "Validate, sanitize, and save an SVG document you authored to \
                 .stella/artifacts/, returning the file path. The SVG is treated as \
                 untrusted code: scripts, event handlers, and external references are \
                 stripped. If it fails to parse, the error names the offending line and \
                 column — fix the SVG and retry (up to {DEFAULT_SVG_ATTEMPTS} attempts \
                 total)."
            ),
            input_schema: serde_json::json!({
                "type": "object",
                "properties": {
                    "svg": {
                        "type": "string",
                        "description": "The complete SVG document (<svg …>…</svg>)"
                    },
                    "label": {
                        "type": "string",
                        "description": "Short human label for the artifact filename"
                    }
                },
                "required": ["svg"]
            }),
            read_only: false,
            speculation_safe: false,
        }
    }

    async fn execute(&self, input: &Value, root: &std::path::Path) -> ToolOutput {
        let Some(svg) = input.get("svg").and_then(|v| v.as_str()) else {
            return ToolOutput::Error {
                message: "`svg` is required".into(),
            };
        };
        // The bounded repair loop maps onto the agent
        // loop here: a failed attempt returns the parse error for the model
        // to fix, instead of driving an in-process `SvgGenerator` (that port
        // stays for model-backed CLI glue).
        let processed = match SvgPipeline::process(svg) {
            Ok(p) => p,
            Err(e) => {
                return ToolOutput::Error {
                    message: format!("invalid SVG: {e}"),
                };
            }
        };
        let label = input.get("label").and_then(|v| v.as_str()).unwrap_or("svg");
        let store = match open_store(root) {
            Ok(s) => s,
            Err(e) => return e,
        };
        match store.save(processed.svg.as_bytes(), MediaKind::Svg, label) {
            Ok(saved) => {
                let sanitized = if processed.removed.is_empty() {
                    String::new()
                } else {
                    format!(" — sanitized: stripped {}", processed.removed.join(", "))
                };
                ToolOutput::Ok {
                    content: format!("svg \"{}\" → {}{sanitized}", saved.label, saved.path),
                }
            }
            Err(e) => ToolOutput::Error {
                message: format!("could not persist the SVG: {e}"),
            },
        }
    }
}

#[cfg(test)]
mod tests;
