//! `issue`: file, edit, close and comment on a tracker issue.
//!
//! Five of the eleven verbs, on one schema. See [`crate::forge`] for why they
//! are grouped, and for why Rust signs the bodies here rather than the prompt
//! asking for it.
//!
//! # Any configured tracker
//!
//! The tool holds a [`stella_protocol::issue::IssueProvider`], so a workspace
//! bound to Linear gets Linear. Nothing in this file knows what a `gh` is.
//!
//! That is why the verbs go through the port. The other route is a `bash`
//! string the model writes. A Linear workspace cannot run `gh issue create`,
//! and a model handed `bash` writes it anyway.

use async_trait::async_trait;
use serde_json::{Value, json};
use stella_protocol::issue::{CommentId, IssueDraft, IssueKey, IssueLabel};
use stella_protocol::tool::{ErrorClass, ToolOutput, ToolSchema};

use super::{ForgeSlots, optional, required, unknown_action};
use crate::registry::Tool;

/// The actions this tool takes, in the order the schema lists them.
const ACTIONS: &[&str] = &["create", "update", "close", "comment", "edit_comment"];

/// `issue`: the tracker plane, as one tool.
pub struct IssueTool {
    slots: ForgeSlots,
}

impl IssueTool {
    /// Build the tool over the host's slots.
    #[must_use]
    pub fn new(slots: ForgeSlots) -> Self {
        Self { slots }
    }
}

#[async_trait]
impl Tool for IssueTool {
    fn schema(&self) -> ToolSchema {
        ToolSchema {
            name: "issue".into(),
            description: "File, edit, close, or comment on an issue in this workspace's \
                 configured tracker. Use this instead of `gh issue ...` in bash: it reaches \
                 whichever tracker is configured (not only GitHub), and it signs what it writes \
                 so the record says what produced it. Do NOT add your own \"generated by\" \
                 footer; one is appended for you."
                .into(),
            input_schema: json!({
                "type": "object",
                "properties": {
                    "action": {
                        "type": "string",
                        "enum": ACTIONS,
                        "description":
                            "create: file a new issue (needs title, body). \
                             update: change an open issue's title and/or body (needs key). \
                             close: resolve it (needs key). \
                             comment: add a comment (needs key, body). \
                             edit_comment: rewrite a comment you posted (needs key, comment_id, body)."
                    },
                    "key": {
                        "type": "string",
                        "description": "The issue's number or id, without a leading `#`. \
                                        Required by every action except create."
                    },
                    "title": {"type": "string", "description": "Issue title. Required by create."},
                    "body": {
                        "type": "string",
                        "description": "The issue body, or the comment text. Write only what you \
                                        mean to say; the attribution footer is added for you."
                    },
                    "labels": {
                        "type": "array",
                        "items": {"type": "string"},
                        "description": "Labels to apply on create."
                    },
                    "comment_id": {
                        "type": "string",
                        "description": "The id a previous comment action returned. Required by \
                                        edit_comment."
                    },
                    "resolution": {
                        "type": "string",
                        "enum": ["completed", "not_planned", "duplicate"],
                        "description": "Why it is being closed. Defaults to completed."
                    },
                    "receipt": {
                        "type": "string",
                        "description": "Evidence attached as a closing comment. Say what you ran \
                                        and what it showed, not that you are confident."
                    }
                },
                "required": ["action"]
            }),
            // All five of these actions write to a shared tracker, `update`
            // and `close` too. That is harder to walk back than a file in the
            // work tree.
            read_only: false,
            speculation_safe: false,
        }
    }

    async fn execute(&self, input: &Value, _ctx: &crate::ctx::ToolCtx) -> ToolOutput {
        match self.run(input).await {
            Ok(output) | Err(output) => output,
        }
    }
}

impl IssueTool {
    /// The body of [`Tool::execute`]. The `?` turns a bad argument into one
    /// line here rather than a nest.
    async fn run(&self, input: &Value) -> Result<ToolOutput, ToolOutput> {
        let action = required(input, "action")?;
        // Asked before the tracker is looked up, so a switched-off action
        // reads the same on a workspace that has no tracker as on one that
        // does.
        self.slots.permits("issue", action)?;
        let tracker = self.slots.tracker()?;
        let attribution = self.slots.attribution();

        match action {
            "create" => {
                let draft = IssueDraft {
                    title: required(input, "title")?.to_owned(),
                    body: stella_autonomy::sign(required(input, "body")?, &attribution.issue),
                    labels: labels(input),
                    parent: None,
                    assignee: None,
                };
                let key = tracker.file(&draft).await.map_err(failed)?;
                Ok(ToolOutput::ok_with_data(
                    format!("Filed issue #{key}."),
                    json!({"key": key.as_str()}),
                ))
            }
            "update" => {
                let key = issue_key(input)?;
                let title = optional(input, "title");
                // Re-signed on the way through, so an edit cannot strip the
                // footer off an issue that had one. `sign` is idempotent
                // against its own output. A model that echoed the signed body
                // back gets one footer, not two.
                let body = optional(input, "body")
                    .map(|body| stella_autonomy::sign(body, &attribution.issue));
                if title.is_none() && body.is_none() {
                    return Err(ToolOutput::classified_error(
                        ErrorClass::InvalidInput,
                        "update needs a title, a body, or both. Nothing was sent to change.",
                    ));
                }
                tracker
                    .edit(&key, title, body.as_deref())
                    .await
                    .map_err(failed)?;
                Ok(ToolOutput::ok(format!("Updated issue #{key}.")))
            }
            "close" => {
                let key = issue_key(input)?;
                let resolution = optional(input, "resolution").unwrap_or("completed");
                let receipt = optional(input, "receipt")
                    .map(|receipt| stella_autonomy::sign(receipt, &attribution.issue_comment))
                    .unwrap_or_default();
                tracker
                    .close(&key, &receipt, resolution)
                    .await
                    .map_err(failed)?;
                Ok(ToolOutput::ok(format!(
                    "Closed issue #{key} as {resolution}."
                )))
            }
            "comment" => {
                let key = issue_key(input)?;
                let body =
                    stella_autonomy::sign(required(input, "body")?, &attribution.issue_comment);
                let comment = tracker.comment(&key, &body).await.map_err(failed)?;
                Ok(ToolOutput::ok_with_data(
                    format!("Commented on issue #{key} (comment {comment})."),
                    json!({"key": key.as_str(), "comment_id": comment.as_str()}),
                ))
            }
            "edit_comment" => {
                let key = issue_key(input)?;
                let comment = CommentId::from(required(input, "comment_id")?);
                let body =
                    stella_autonomy::sign(required(input, "body")?, &attribution.issue_comment);
                tracker
                    .edit_comment(&key, &comment, &body)
                    .await
                    .map_err(failed)?;
                Ok(ToolOutput::ok(format!(
                    "Rewrote comment {comment} on issue #{key}."
                )))
            }
            other => Err(unknown_action(other, ACTIONS)),
        }
    }
}

/// The issue this call names. A leading `#` is fine.
///
/// Models write `#4231`. That is how an issue shows up everywhere they have
/// read one. Trackers take the bare number. Stripping it here costs nothing.
/// It removes a failure the model could not work out from the error.
fn issue_key(input: &Value) -> Result<IssueKey, ToolOutput> {
    Ok(IssueKey::from(
        required(input, "key")?.trim_start_matches('#'),
    ))
}

/// The labels this call asks for, ignoring anything that is not a string.
fn labels(input: &Value) -> Vec<IssueLabel> {
    input
        .get("labels")
        .and_then(Value::as_array)
        .map(|items| {
            items
                .iter()
                .filter_map(Value::as_str)
                .map(str::trim)
                .filter(|name| !name.is_empty())
                .map(|name| IssueLabel {
                    name: name.to_owned(),
                })
                .collect()
        })
        .unwrap_or_default()
}

/// A tracker's refusal, in the shape the model retries against.
///
/// Classified `Environment`, not `Internal`. A `gh` that is not signed in is
/// one. So is a deleted issue, or a tracker that is down. All of them sit
/// outside this tool, and none is a bug in this file.
fn failed(error: stella_protocol::issue::IssueError) -> ToolOutput {
    ToolOutput::classified_error(ErrorClass::Environment, error.to_string())
}

#[cfg(test)]
mod tests;
