//! `pull_request`: open, edit, close, merge and comment on a pull request.
//!
//! Six of the eleven verbs, on one schema. See [`crate::forge`] for why they
//! are grouped. It also says why Rust signs every body here rather than the
//! prompt asking for it.
//!
//! # The merge guard
//!
//! Every other action here can be undone. A closed pull request reopens. The
//! text can be changed again, and a comment can be rewritten. A merge writes
//! to a shared branch and stays there.
//!
//! So `merge` refuses unless the call says `confirm: true`. The model has to
//! make that claim. It cannot fall into it while it retries something else.
//!
//! The guard sits in this file rather than in the host's policy plane. It is
//! about the verb itself. A workspace that wants a person to sign off on a
//! merge has an approval gate for that. The two stack.

use async_trait::async_trait;
use serde_json::{Value, json};
use stella_protocol::pull_request::{
    CommentId, PullRequestDraft, PullRequestKey, PullRequestPatch,
};
use stella_protocol::tool::{ErrorClass, ToolOutput, ToolSchema};

use super::{ForgeSlots, known_action, optional, required, unknown_action};
use crate::registry::Tool;

/// The actions this tool takes, in the order the schema lists them.
const ACTIONS: &[&str] = &[
    "create",
    "update",
    "close",
    "merge",
    "comment",
    "edit_comment",
];

/// `pull_request`: the forge plane, as one tool.
pub struct PullRequestTool {
    slots: ForgeSlots,
}

impl PullRequestTool {
    /// Build the tool over the host's slots.
    #[must_use]
    pub fn new(slots: ForgeSlots) -> Self {
        Self { slots }
    }
}

#[async_trait]
impl Tool for PullRequestTool {
    fn schema(&self) -> ToolSchema {
        ToolSchema {
            name: "pull_request".into(),
            description: "Open, edit, close, merge, or comment on a pull request on this \
                 workspace's configured forge. Use this instead of `gh pr ...` in bash: it signs \
                 what it writes so the record says what produced it. Do NOT add your own \
                 \"generated by\" footer; one is appended for you. Merging requires \
                 `confirm: true` because it writes to a shared branch."
                .into(),
            input_schema: json!({
                "type": "object",
                "properties": {
                    "action": {
                        "type": "string",
                        "enum": ACTIONS,
                        "description":
                            "create: open one from a pushed branch (needs head, title, body). \
                             update: change title, description, and/or draft status (needs key). \
                             close: close without merging (needs key). \
                             merge: merge it (needs key and confirm). \
                             comment: add a comment (needs key, body). \
                             edit_comment: rewrite a comment you posted (needs key, comment_id, body)."
                    },
                    "key": {
                        "type": "string",
                        "description": "The pull request's number, without a leading `#`. \
                                        Required by every action except create."
                    },
                    "head": {
                        "type": "string",
                        "description": "The branch to open from. It must already be pushed. \
                                        Required by create."
                    },
                    "title": {"type": "string", "description": "Pull request title."},
                    "body": {
                        "type": "string",
                        "description": "The description, or the comment text. Write only what you \
                                        mean to say; the attribution footer is added for you."
                    },
                    "draft": {
                        "type": "boolean",
                        "description": "On create, open it as a draft. On update, `false` marks \
                                        it ready for review."
                    },
                    "comment_id": {
                        "type": "string",
                        "description": "The id a previous comment action returned. Required by \
                                        edit_comment."
                    },
                    "confirm": {
                        "type": "boolean",
                        "description": "Required by merge, and only by merge. Set it when you \
                                        have checked that CI is green and the change is the one \
                                        that should land."
                    }
                },
                "required": ["action"]
            }),
            read_only: false,
            speculation_safe: false,
        }
    }

    async fn execute(&self, input: &Value, _ctx: &crate::ctx::ToolCtx) -> ToolOutput {
        match self.run(input) {
            Ok(output) | Err(output) => output,
        }
    }
}

impl PullRequestTool {
    /// The body of [`Tool::execute`].
    ///
    /// This is synchronous because
    /// [`stella_protocol::pull_request::PullRequestProvider`] is. The port's
    /// own module says why. Each call is one short subprocess, so this holds
    /// the dispatch thread for one `gh` round trip.
    fn run(&self, input: &Value) -> Result<ToolOutput, ToolOutput> {
        let action = required(input, "action")?;
        known_action(action, ACTIONS)?;
        // Before the forge is even looked up: a switched-off action is a
        // decision somebody made, and it is the same answer whether or not
        // this workspace has a forge attached.
        self.slots.permits("pull_request", action)?;
        let forge = self.slots.forge()?;
        let attribution = self.slots.attribution();

        match action {
            "create" => {
                let draft = PullRequestDraft {
                    head_ref: required(input, "head")?.to_owned(),
                    title: attribution.title(required(input, "title")?),
                    body: stella_autonomy::sign(
                        required(input, "body")?,
                        &attribution.pull_request,
                    ),
                    draft: input.get("draft").and_then(Value::as_bool).unwrap_or(false),
                };
                let key = forge.open(&draft).map_err(failed)?;
                Ok(ToolOutput::ok_with_data(
                    format!("Opened pull request #{key}."),
                    json!({"key": key.as_str()}),
                ))
            }
            "update" => {
                let key = pr_key(input)?;
                let patch = PullRequestPatch {
                    // Prefixed on the way through, for the reason the body
                    // below is re-signed: an edit must not be able to strip
                    // the mark off a pull request that carried one.
                    // `Attribution::title` is idempotent, so a title that
                    // already reads `stella self-driving: …` keeps one prefix.
                    title: optional(input, "title").map(|title| attribution.title(title)),
                    // Re-signed on the way through, so an edit cannot strip
                    // the footer off a body that had one. `sign` is idempotent
                    // against its own output. A model that echoed the signed
                    // body back gets one footer, not two.
                    body: optional(input, "body")
                        .map(|body| stella_autonomy::sign(body, &attribution.pull_request)),
                    draft: input.get("draft").and_then(Value::as_bool),
                };
                if patch.is_empty() {
                    return Err(ToolOutput::classified_error(
                        ErrorClass::InvalidInput,
                        "update needs a title, a body, a draft flag, or some combination. \
                         Nothing was sent to change.",
                    ));
                }
                forge.update(&key, &patch).map_err(failed)?;
                Ok(ToolOutput::ok(format!("Updated pull request #{key}.")))
            }
            "close" => {
                let key = pr_key(input)?;
                forge.close(&key).map_err(failed)?;
                Ok(ToolOutput::ok(format!(
                    "Closed pull request #{key} without merging."
                )))
            }
            "merge" => {
                let key = pr_key(input)?;
                if input.get("confirm").and_then(Value::as_bool) != Some(true) {
                    return Err(ToolOutput::classified_error(
                        ErrorClass::InvalidInput,
                        format!(
                            "merging #{key} writes to a shared branch and cannot be undone, so \
                             it needs `confirm: true`. Check the checks first — `watch_ci` on \
                             this pull request's branch reports them."
                        ),
                    ));
                }
                forge.merge(&key).map_err(failed)?;
                Ok(ToolOutput::ok(format!("Merged pull request #{key}.")))
            }
            "comment" => {
                let key = pr_key(input)?;
                let body = stella_autonomy::sign(
                    required(input, "body")?,
                    &attribution.pull_request_comment,
                );
                let comment = forge.comment(&key, &body).map_err(failed)?;
                Ok(ToolOutput::ok_with_data(
                    format!("Commented on pull request #{key} (comment {comment})."),
                    json!({"key": key.as_str(), "comment_id": comment.as_str()}),
                ))
            }
            "edit_comment" => {
                let key = pr_key(input)?;
                let comment = CommentId::from(required(input, "comment_id")?);
                let body = stella_autonomy::sign(
                    required(input, "body")?,
                    &attribution.pull_request_comment,
                );
                forge.edit_comment(&key, &comment, &body).map_err(failed)?;
                Ok(ToolOutput::ok(format!(
                    "Rewrote comment {comment} on pull request #{key}."
                )))
            }
            other => Err(unknown_action(other, ACTIONS)),
        }
    }
}

/// The pull request this call names. A leading `#` is fine: see
/// [`super::issue`]'s version of this for why.
fn pr_key(input: &Value) -> Result<PullRequestKey, ToolOutput> {
    Ok(PullRequestKey::from(
        required(input, "key")?.trim_start_matches('#'),
    ))
}

/// A forge's refusal, in the shape the model retries against.
fn failed(error: stella_protocol::pull_request::PullRequestError) -> ToolOutput {
    ToolOutput::classified_error(ErrorClass::Environment, error.to_string())
}

#[cfg(test)]
mod tests;
