//! How the loop signs what it writes.
//!
//! Everything an autonomous loop puts into a shared repository should say so.
//! A commit, a pull request description, an issue, an issue comment — a person
//! reading any of them a month later needs to know whether a human wrote it,
//! and that is not a thing to leave to a reader's guess about tone.
//!
//! # The rule is exact, because "roughly a footer" is not a contract
//!
//! [`sign`] appends the signature as a **horizontal rule footer**: a blank
//! line, `---`, a newline, then the text. So a signed body always ends
//!
//! ```text
//! <body>
//!
//! ---
//! Generated by Stella. To inspect this run in the observatory run `stella observe` in your terminal.
//! ```
//!
//! Trailing whitespace on the body is removed first, so the result does not
//! depend on whether the caller happened to end with a newline — precisely the
//! difference that would otherwise produce two near-identical formats across
//! four surfaces with no way to tell which is right.
//! `the_signature_is_a_horizontal_rule_footer` is the witness.
//!
//! **The separator is fixed and the text is not.** A distribution changes what
//! the footer *says*; it does not get to change whether there is a rule above
//! it, because that is what makes a signed body recognisable at a glance
//! across every surface and every deployment.
//!
//! # Configurable per surface, and separately
//!
//! The five surfaces are separate fields rather than one string, because they
//! are read in different places and a deployment will want different words:
//! a commit trailer is scanned by tooling, an issue comment is read by a
//! person. A field left empty signs nothing — the loop stays silent on that
//! surface rather than falling back to a default the operator did not choose.
//!
//! The branch prefix lives here too. It is the same question wearing a
//! different hat: *what does this repository see when the loop touches it?*

use serde::{Deserialize, Serialize};

/// What the footer says, unless a workspace changes it.
///
/// One string for all five surfaces by default: a reader should recognise the
/// same mark on a commit, a pull request, an issue and a comment without
/// having to learn five phrasings. A deployment that wants them to differ sets
/// them separately.
///
/// It names the command that opens the run behind the text. A reader who
/// finds one of these asks what made it. A mark that only says "a robot"
/// cannot answer that.
pub const SIGNATURE: &str = "Generated by Stella. To inspect this run in the observatory run \
     `stella observe` in your terminal.";

/// What separates a body from its signature: a blank line, then a rule.
///
/// Fixed rather than configurable — see the module docs.
const SEPARATOR: &str = "\n\n---\n";

/// The default branch prefix.
///
/// Every branch the loop opens is namespaced, so a human scanning `git branch`
/// can tell at a glance which refs are theirs. It is also what keeps the loop's
/// branches out of the fleet's namespace, where `stella fleet gc` would believe
/// it owned them.
pub const DEFAULT_BRANCH_PREFIX: &str = "stella/";

/// What a pull request the loop opens is titled with, unless configured.
///
/// Names the *thing that did it* rather than the crate it touched. A
/// maintainer scanning a pull request list wants to know which entries nobody
/// wrote by hand; which crate a change lands in is already in the diff.
pub const DEFAULT_TITLE_PREFIX: &str = "stella self-driving:";

/// What the loop appends to each thing it writes, and how it names branches.
///
/// Source-tracked so it travels with the repository, and rewritable by an
/// installed plugin: a downstream distribution signs in its own name, and that
/// is a configuration change rather than a fork.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(default)]
pub struct Attribution {
    /// What the loop asks a turn to end its commit message with.
    ///
    /// The weakest of the five, and the only one that depends on the model
    /// cooperating. The other four are appended in Rust by the tool that
    /// sends the body. A commit is authored by `git` inside the `bash` tool,
    /// which nothing here rewrites, so `self_driving_cmd::work`'s `prompt_for`
    /// puts this text into the turn's prompt instead. A model that paraphrases
    /// it produces an unsigned commit and nothing catches that. Making it
    /// deterministic means either a `prepare-commit-msg` hook or a commit
    /// tool, and which one is the maintainer's call.
    pub commit: String,
    /// Appended to every pull request description it opens.
    pub pull_request: String,
    /// Appended to every issue it files.
    pub issue: String,
    /// Appended to every issue comment it posts.
    pub issue_comment: String,
    /// Appended to every pull request comment it posts.
    ///
    /// This is its own field rather than a share of [`Self::issue_comment`].
    /// GitHub keeps both on one endpoint. That is a GitHub detail. On a forge
    /// where a review comment and a tracker comment are separate things, they
    /// need not read the same.
    pub pull_request_comment: String,
    /// Prefix for every branch it creates.
    ///
    /// A prefix that does not end in `/` is used verbatim rather than
    /// corrected: some teams namespace with `-`, and silently rewriting an
    /// operator's choice is worse than honouring an unusual one.
    pub branch_prefix: String,
    /// Prefix for the title of every pull request it opens.
    ///
    /// The footer says who wrote a pull request once you open it; this says so
    /// in the list, which is where a maintainer actually triages. Without it an
    /// autonomous pull request inherits its issue's title verbatim and is
    /// indistinguishable from a human's at a glance.
    ///
    /// Deliberately **not** applied to commit messages. Those follow
    /// Conventional Commits (`fix(stella-cli): …`), the scope is required,
    /// and a prefix in front of it would break the convention the repository
    /// enforces. The commit identifies its author through the footer instead.
    pub title_prefix: String,
}

impl Default for Attribution {
    fn default() -> Self {
        Self {
            commit: SIGNATURE.to_owned(),
            pull_request: SIGNATURE.to_owned(),
            issue: SIGNATURE.to_owned(),
            issue_comment: SIGNATURE.to_owned(),
            pull_request_comment: SIGNATURE.to_owned(),
            branch_prefix: DEFAULT_BRANCH_PREFIX.to_owned(),
            title_prefix: DEFAULT_TITLE_PREFIX.to_owned(),
        }
    }
}

impl Attribution {
    /// Put the title prefix in front of a summary.
    ///
    /// An empty prefix is honoured as "no prefix" here, unlike
    /// [`Self::branch_prefix`] — an unprefixed title is merely
    /// indistinguishable, while an unprefixed branch collides with a human's
    /// refs. One is cosmetic and one is operational.
    ///
    /// Already-prefixed titles are left alone, so re-opening a pull request
    /// for the same issue cannot stack the prefix twice.
    #[must_use]
    pub fn title(&self, summary: &str) -> String {
        let prefix = self.title_prefix.trim();
        if prefix.is_empty() || summary.starts_with(prefix) {
            return summary.to_owned();
        }
        format!("{prefix} {summary}")
    }

    /// The branch prefix, falling back to the default when unset.
    ///
    /// An empty prefix is treated as unset rather than as "no prefix": an
    /// unnamespaced branch is how the loop's refs end up indistinguishable
    /// from a human's, and an operator who genuinely wants that can say so
    /// with a prefix of their own choosing.
    #[must_use]
    pub fn branch_prefix(&self) -> &str {
        if self.branch_prefix.trim().is_empty() {
            DEFAULT_BRANCH_PREFIX
        } else {
            &self.branch_prefix
        }
    }
}

/// Append `signature` to `body` as a horizontal rule footer.
///
/// The result ends `<body>\n\n---\n<signature>`. Trailing whitespace on the
/// body is normalized first, so two callers whose bodies differ only in how
/// they terminated produce identical output.
///
/// An empty signature returns the body untouched — including its own trailing
/// whitespace, because a caller that signs nothing has not asked for its text
/// to be reformatted.
///
/// # Examples
///
/// The join is a blank line and then the rule, whatever the body ended with —
/// so two callers that differ only in trailing whitespace produce the
/// identical result:
///
/// ```
/// use stella_autonomy::sign;
///
/// assert_eq!(
///     sign("body", "Created by stella."),
///     "body\n\n---\nCreated by stella."
/// );
/// assert_eq!(
///     sign("body\n\n", "Created by stella."),
///     "body\n\n---\nCreated by stella."
/// );
/// ```
#[must_use]
pub fn sign(body: &str, signature: &str) -> String {
    if signature.trim().is_empty() {
        return body.to_owned();
    }
    let trimmed = body.trim_end();
    let footer = format!("{SEPARATOR}{}", signature.trim());
    if trimmed.ends_with(&footer) {
        // Already signed with this exact footer, so signing again would stack
        // a second one. This is not hypothetical. Every edit path reads a body
        // back from the forge, hands it to a model, and writes the model's
        // version. The body it read already carried the footer.
        // `a_signed_body_signed_again_is_unchanged` is the witness.
        //
        // The test is the tail, and that is the whole promise. A body whose
        // footer sits in the middle — a model that quoted the old description
        // above its new text — gets a second footer at the end, and the
        // quoted one stays where the model put it. Reaching inside the body
        // to find and move it would mean editing what the model wrote, which
        // is the one thing this plane does not do. One footer at the end is
        // what the record needs; a line that reads like a footer inside the
        // text is the model's prose.
        return trimmed.to_owned();
    }
    if trimmed.is_empty() {
        // An empty body gets the footer without a leading blank line: a rule
        // with nothing above it is a rule separating nothing.
        return format!("---\n{}", signature.trim());
    }
    format!("{trimmed}{SEPARATOR}{}", signature.trim())
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A pull request the loop opened says so in the list, not just inside it.
    ///
    /// The footer identifies an autonomous pull request once it is open; the
    /// title is what a maintainer reads while triaging twenty of them. Before
    /// this, the title was the issue's verbatim — `stella-autonomy: sign() has
    /// no doctest …` — indistinguishable from something a person wrote.
    #[test]
    fn a_title_says_what_opened_the_pull_request() {
        let attribution = Attribution::default();
        assert_eq!(
            attribution.title("stella-autonomy: sign() has no doctest (#4006)"),
            "stella self-driving: stella-autonomy: sign() has no doctest (#4006)"
        );
    }

    /// Re-opening for the same issue cannot stack the prefix.
    #[test]
    fn an_already_prefixed_title_is_left_alone() {
        let attribution = Attribution::default();
        let once = attribution.title("fix the thing");
        assert_eq!(attribution.title(&once), once);
    }

    /// The prefix is the operator's, and an empty one means none.
    ///
    /// Unlike `branch_prefix`, where empty falls back to the default: an
    /// unprefixed title is merely indistinguishable, while an unprefixed
    /// branch collides with a human's refs. Cosmetic versus operational.
    #[test]
    fn an_empty_title_prefix_is_honoured_as_no_prefix() {
        let attribution = Attribution {
            title_prefix: String::new(),
            ..Attribution::default()
        };
        assert_eq!(attribution.title("fix the thing"), "fix the thing");

        let oxagen = Attribution {
            title_prefix: "oxagen:".to_owned(),
            ..Attribution::default()
        };
        assert_eq!(oxagen.title("fix the thing"), "oxagen: fix the thing");
    }

    /// **The witness.** A blank line, a rule, then the text — whatever the body
    /// ended with, so the four surfaces cannot drift into four near-identical
    /// formats.
    #[test]
    fn the_signature_is_a_horizontal_rule_footer() {
        for body in [
            "the body",
            "the body\n",
            "the body\n\n",
            "the body\n\n\n   \t\n",
            "the body   ",
        ] {
            assert_eq!(
                sign(body, SIGNATURE),
                format!("the body\n\n---\n{SIGNATURE}"),
                "body {body:?} must produce the same footer"
            );
        }
    }

    /// Signing a body that already carries this exact footer changes nothing.
    ///
    /// The path that needs it: every edit reads a body back from the forge,
    /// hands it to a model, and writes what comes back. What it read was
    /// already signed, so an appending-only `sign` produced a second footer on
    /// the first edit and a third on the next.
    ///
    /// A *different* signature still appends, and that is correct rather than
    /// an oversight: a workspace that changed its footer has two marks with
    /// two meanings, and dropping the old one would erase the record of what
    /// wrote the body first.
    #[test]
    fn a_signed_body_signed_again_is_unchanged() {
        let once = sign("the body", SIGNATURE);
        assert_eq!(sign(&once, SIGNATURE), once);
        assert_eq!(sign(&format!("{once}\n\n"), SIGNATURE), once);

        let with_other = sign(&once, "some other mark");
        assert!(
            with_other.ends_with("---\nsome other mark"),
            "a different signature still appends: {with_other:?}"
        );
    }

    /// A multi-line body keeps its own interior line breaks; only the join is
    /// normalized.
    #[test]
    fn interior_line_breaks_are_left_alone() {
        assert_eq!(
            sign("first\n\nsecond\n", "sig"),
            "first\n\nsecond\n\n---\nsig"
        );
    }

    /// An operator who clears a surface's signature gets silence on it, not a
    /// default they did not choose.
    #[test]
    fn an_empty_signature_signs_nothing_and_reformats_nothing() {
        assert_eq!(sign("the body\n\n", ""), "the body\n\n");
        assert_eq!(sign("the body", "   "), "the body");
    }

    /// A rule with nothing above it separates nothing, so an empty body gets
    /// the footer without a leading blank line.
    #[test]
    fn an_empty_body_gets_the_footer_without_a_leading_blank_line() {
        assert_eq!(sign("", "sig"), "---\nsig");
        assert_eq!(sign("  \n ", "sig"), "---\nsig");
    }

    /// The default is `stella/`, and it is what an unset prefix falls back to.
    #[test]
    fn the_branch_prefix_defaults_to_stella() {
        assert_eq!(Attribution::default().branch_prefix(), "stella/");

        let unset = Attribution {
            branch_prefix: String::new(),
            ..Attribution::default()
        };
        assert_eq!(unset.branch_prefix(), "stella/");
    }

    /// An unusual prefix is honoured rather than corrected.
    #[test]
    fn an_operator_prefix_is_used_verbatim() {
        let theirs = Attribution {
            branch_prefix: "oxagen-".to_owned(),
            ..Attribution::default()
        };
        assert_eq!(theirs.branch_prefix(), "oxagen-");
    }

    /// A distribution changes what the footer says; it does not change that
    /// there is a rule above it. That is what makes a signed body recognisable
    /// across every surface and every deployment.
    #[test]
    fn the_separator_is_fixed_even_when_the_text_is_not() {
        assert!(sign("body", "Created by oxagen.").starts_with("body\n\n---\n"));
        assert!(sign("body", "anything at all").starts_with("body\n\n---\n"));
    }

    /// The four surfaces are independent: changing one does not move another.
    #[test]
    fn each_surface_signs_separately() {
        let a = Attribution {
            commit: "c".into(),
            pull_request: "p".into(),
            issue: "i".into(),
            issue_comment: "n".into(),
            ..Attribution::default()
        };
        assert_eq!(sign("x", &a.commit), "x\n\n---\nc");
        assert_eq!(sign("x", &a.pull_request), "x\n\n---\np");
        assert_eq!(sign("x", &a.issue), "x\n\n---\ni");
        assert_eq!(sign("x", &a.issue_comment), "x\n\n---\nn");
    }

    /// A partial manifest fills in the defaults for what it did not mention —
    /// so a plugin rewriting one surface does not silently blank the rest.
    #[test]
    fn a_partial_manifest_keeps_the_other_surfaces() {
        let parsed: Attribution =
            serde_json::from_str(r#"{"commit":"Created by oxagen."}"#).expect("deserialize");
        assert_eq!(parsed.commit, "Created by oxagen.");
        assert_eq!(parsed.issue, SIGNATURE);
        assert_eq!(parsed.branch_prefix(), "stella/");
    }

    #[test]
    fn attribution_round_trips_through_json() {
        let a = Attribution::default();
        let json = serde_json::to_string(&a).expect("serialize");
        let back: Attribution = serde_json::from_str(&json).expect("deserialize");
        assert_eq!(a, back);
    }
}
