//! Media generation tools over `stella-media`'s `MediaProvider` port, BYOK
//! like everything else: `generate_image` — and the `generate_video` /
//! `poll_video` pair when the key family has a video adapter — register only
//! when a capable provider key is present in the environment (`ZAI_API_KEY`
//! or `OPENAI_API_KEY`), mirroring the issue tools' conditional
//! registration — no key, no dead schema. `generate_svg` is client-side
//! (the model authors the SVG, the pipeline validates
//! and sanitizes it), so it needs no key and is always registered.
//!
//! Artifact discipline (`stella-media`): generated bytes are persisted
//! through the `ArtifactStore` into `.stella/artifacts/` — the single
//! allowed writer — and every tool reports the citation-ready path.
//!
//! Image and video submissions cross a host-owned spend gate before touching
//! the provider. Tool arguments cannot approve spend; callers without an
//! injected host gate deny by default. A submitted video handle is persisted
//! through the `JobStore` so a dropped session never orphans a paid job;
//! `poll_video` reconciles it live against the provider (L-V3) and persists
//! the finished artifact under the identity assigned at submit.

use std::sync::{
    Arc,
    atomic::{AtomicU64, Ordering},
};

use async_trait::async_trait;
use serde_json::Value;
use stella_media::{
    ArtifactStore, CostDecision, DEFAULT_SVG_ATTEMPTS, DenyMediaSpendGate, ImageRequest, ImageSize,
    JobStore, MediaJob, MediaJobState, MediaKind, MediaOperationState, MediaProvider,
    MediaSpendGate, MediaSpendRequest, SvgPipeline, VideoRequest,
};
use stella_protocol::tool::{ToolOutput, ToolSchema};

use crate::registry::Tool;

/// Default duration used for the video cost estimate when the model omits
/// `duration_secs`.
const DEFAULT_VIDEO_DURATION_SECS: u32 = 5;

/// Host-owned source of invocation identities. The value never comes from
/// model arguments and must remain stable when the host retries one call.
pub trait MediaOperationIdSource: Send + Sync {
    fn operation_id(&self) -> String;
}

struct DeniedOperationIds;

impl MediaOperationIdSource for DeniedOperationIds {
    fn operation_id(&self) -> String {
        static NEXT: AtomicU64 = AtomicU64::new(0);
        format!(
            "{}-{}-{}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap_or_default()
                .as_nanos(),
            NEXT.fetch_add(1, Ordering::Relaxed)
        )
    }
}

fn operation_key(source: &dyn MediaOperationIdSource, kind: MediaKind, provider: &str) -> String {
    let kind = match kind {
        MediaKind::Image => "image",
        MediaKind::Video => "video",
        MediaKind::Svg => "svg",
    };
    let identity = format!(
        "stella-media-v1\0{kind}\0{provider}\0{}",
        source.operation_id()
    );
    format!("mop_{}", crate::staleness::hex_sha256(identity.as_bytes()))
}

/// The media backends resolved from the environment: an image-capable
/// provider (detection keys on it), plus the same key family's video
/// provider when it has one.
pub struct MediaBackend {
    pub image: Arc<dyn MediaProvider>,
    /// `None` when the configured key family has no video adapter (OpenAI in
    /// v1) — the video tool pair stays unregistered.
    pub video: Option<Arc<dyn MediaProvider>>,
}

/// Detect a media-capable BYOK backend from provider env keys. Z.ai wins
/// when several are set (the same "most specific configured backend first"
/// rule as the issue tools' Linear-over-GitHub precedence); it is also the
/// only key family with a video adapter (CogVideoX).
pub fn detect_media_backend() -> Option<MediaBackend> {
    if let Ok(key) = stella_media::ApiKey::from_env("ZAI_API_KEY") {
        return Some(MediaBackend {
            image: Arc::new(stella_media::adapters::ZaiImageProvider::new(
                key.clone(),
                stella_media::adapters::zai_image::DEFAULT_MODEL,
            )),
            video: Some(Arc::new(stella_media::adapters::ZaiVideoProvider::new(
                key,
                stella_media::adapters::zai_video::DEFAULT_MODEL,
            ))),
        });
    }
    if let Ok(key) = stella_media::ApiKey::from_env("OPENAI_API_KEY") {
        return Some(MediaBackend {
            image: Arc::new(stella_media::adapters::OpenAiImageProvider::new(
                key,
                stella_media::adapters::openai_image::DEFAULT_MODEL,
            )),
            video: None,
        });
    }
    None
}

/// Open the workspace's artifact store (`.stella/artifacts/`) — the one
/// sanctioned writer for generated media.
fn open_store(root: &std::path::Path) -> Result<ArtifactStore, ToolOutput> {
    ArtifactStore::open(root.join(".stella").join("artifacts")).map_err(|e| ToolOutput::Error {
        message: format!("artifact store unavailable: {e}"),
    })
}

/// The video job store (`jobs.json`) lives inside the same artifacts root.
fn open_jobs(root: &std::path::Path) -> JobStore {
    JobStore::open(root.join(".stella").join("artifacts"))
}

fn spend_denied(request: &MediaSpendRequest) -> ToolOutput {
    let estimate = request
        .estimated_usd
        .map_or_else(|| "unknown cost".to_string(), |usd| format!("${usd:.4}"));
    ToolOutput::Error {
        message: format!(
            "media spend requires host approval: {} submission to {} ({estimate}; {})",
            match request.kind {
                MediaKind::Image => "image",
                MediaKind::Video => "video",
                MediaKind::Svg => "SVG",
            },
            request.provider_id,
            request.detail
        ),
    }
}

fn reconciliation_required(operation_id: &str, detail: impl std::fmt::Display) -> ToolOutput {
    ToolOutput::Error {
        message: format!(
            "reconciliation_required: paid media operation `{operation_id}` may have reached the provider; refusing automatic resubmission ({detail})"
        ),
    }
}

fn video_submitted(job: &MediaJob) -> ToolOutput {
    ToolOutput::Ok {
        content: format!(
            "submitted video job `{}` (model {}, ~${:.4}) — the job runs asynchronously; check it with poll_video",
            job.provider_job_id, job.model, job.estimated_cost_usd
        ),
    }
}

pub struct GenerateImage {
    provider: Arc<dyn MediaProvider>,
    spend_gate: Arc<dyn MediaSpendGate>,
    operation_ids: Arc<dyn MediaOperationIdSource>,
}

impl GenerateImage {
    /// Construct with the secure deny-by-default host gate.
    pub fn new(provider: Arc<dyn MediaProvider>) -> Self {
        Self {
            provider,
            spend_gate: Arc::new(DenyMediaSpendGate),
            // This source is paired only with the deny gate. Approving hosts
            // must inject a retry-stable logical invocation identity.
            operation_ids: Arc::new(DeniedOperationIds),
        }
    }

    /// Construct with host-owned approval and retry-stable invocation identity.
    pub fn with_host_context(
        provider: Arc<dyn MediaProvider>,
        spend_gate: Arc<dyn MediaSpendGate>,
        operation_ids: Arc<dyn MediaOperationIdSource>,
    ) -> Self {
        Self {
            provider,
            spend_gate,
            operation_ids,
        }
    }
}

#[async_trait]
impl Tool for GenerateImage {
    fn schema(&self) -> ToolSchema {
        ToolSchema {
            name: "generate_image".into(),
            description: "Generate an image from a text prompt and save it under \
                          .stella/artifacts/. Returns the file path, model, and cost. \
                          Uses the configured BYOK image provider."
                .into(),
            input_schema: serde_json::json!({
                "type": "object",
                "properties": {
                    "prompt": {
                        "type": "string",
                        "description": "What to generate"
                    },
                    "size": {
                        "type": "string",
                        "description": "WIDTHxHEIGHT, e.g. 1024x1024 (the default)"
                    },
                    "label": {
                        "type": "string",
                        "description": "Short human label for the artifact filename"
                    }
                },
                "required": ["prompt"]
            }),
            read_only: false,
        }
    }

    async fn execute(&self, input: &Value, root: &std::path::Path) -> ToolOutput {
        let Some(prompt) = input.get("prompt").and_then(|v| v.as_str()) else {
            return ToolOutput::Error {
                message: "`prompt` is required".into(),
            };
        };
        let size = match input.get("size").and_then(|v| v.as_str()) {
            Some(raw) => match raw.parse::<ImageSize>() {
                Ok(s) => s,
                Err(_) => {
                    return ToolOutput::Error {
                        message: format!(
                            "`size` must be WIDTHxHEIGHT (e.g. 1024x1024), got `{raw}`"
                        ),
                    };
                }
            },
            None => ImageSize::square(1024),
        };
        let mut request = ImageRequest::new(prompt, size);
        if let Some(label) = input.get("label").and_then(|v| v.as_str()) {
            // Otherwise keep the request's own prompt-derived label.
            request.label = label.to_string();
        }

        let operation_id = operation_key(
            self.operation_ids.as_ref(),
            MediaKind::Image,
            self.provider.id(),
        );
        request.operation_id = Some(operation_id.clone());
        let jobs = open_jobs(root);
        match jobs.claim_operation(&operation_id, MediaKind::Image, self.provider.id()) {
            Ok(None) => {}
            Ok(Some(MediaOperationState::ImageCompleted { artifact_path })) => {
                return ToolOutput::Ok {
                    content: format!("image operation already completed → {artifact_path}"),
                };
            }
            Ok(Some(state)) => {
                return reconciliation_required(&operation_id, format!("state {state:?}"));
            }
            Err(error) => {
                return ToolOutput::Error {
                    message: format!("media_operation_journal_unavailable: {error}"),
                };
            }
        }
        let capabilities = self.provider.capabilities();
        let estimate = capabilities.estimate_image(request.n, request.size);
        let spend_request = MediaSpendRequest::new(
            operation_id.clone(),
            MediaKind::Image,
            self.provider.id(),
            estimate.as_ref().map(|estimate| estimate.estimated_usd),
            estimate.map_or_else(
                || {
                    format!(
                        "{} image(s) at {} (cost unavailable)",
                        request.n, request.size
                    )
                },
                |estimate| estimate.detail,
            ),
        );
        if self.spend_gate.authorize(&spend_request).await != CostDecision::Approve {
            if let Err(error) = jobs.cancel_operation(&operation_id) {
                return reconciliation_required(&operation_id, error);
            }
            return spend_denied(&spend_request);
        }

        let artifact = match self.provider.generate_image(request).await {
            Ok(a) => a,
            Err(error) => return reconciliation_required(&operation_id, error),
        };

        let store = match open_store(root) {
            Ok(s) => s,
            Err(error) => return reconciliation_required(&operation_id, format!("{error:?}")),
        };
        match store.save_artifact(&artifact) {
            Ok(saved) => {
                let content = format!(
                    "generated \"{}\" → {} ({}, model {}, ${:.4})",
                    saved.label, saved.path, size, artifact.model, artifact.cost_usd
                );
                if let Err(error) = jobs.complete_image_operation(&operation_id, &saved.path) {
                    return reconciliation_required(&operation_id, error);
                }
                ToolOutput::Ok { content }
            }
            Err(error) => reconciliation_required(&operation_id, error),
        }
    }
}

pub struct GenerateVideo {
    provider: Arc<dyn MediaProvider>,
    spend_gate: Arc<dyn MediaSpendGate>,
    operation_ids: Arc<dyn MediaOperationIdSource>,
}

impl GenerateVideo {
    /// Construct with the secure deny-by-default host gate.
    pub fn new(provider: Arc<dyn MediaProvider>) -> Self {
        Self {
            provider,
            spend_gate: Arc::new(DenyMediaSpendGate),
            // This source is paired only with the deny gate. Approving hosts
            // must inject a retry-stable logical invocation identity.
            operation_ids: Arc::new(DeniedOperationIds),
        }
    }

    /// Construct with host-owned approval and retry-stable invocation identity.
    pub fn with_host_context(
        provider: Arc<dyn MediaProvider>,
        spend_gate: Arc<dyn MediaSpendGate>,
        operation_ids: Arc<dyn MediaOperationIdSource>,
    ) -> Self {
        Self {
            provider,
            spend_gate,
            operation_ids,
        }
    }
}

#[async_trait]
impl Tool for GenerateVideo {
    fn schema(&self) -> ToolSchema {
        ToolSchema {
            name: "generate_video".into(),
            description: "Submit an asynchronous text-to-video job with the configured BYOK \
                          video provider; returns the job id to check with poll_video. Video \
                          costs real money and requires approval from the host runtime before \
                          provider submission."
                .into(),
            input_schema: serde_json::json!({
                "type": "object",
                "properties": {
                    "prompt": {
                        "type": "string",
                        "description": "What to generate"
                    },
                    "duration_secs": {
                        "type": "integer",
                        "description": "Target duration in seconds, at least 1 (default 5); \
                                        drives the cost estimate"
                    },
                    "label": {
                        "type": "string",
                        "description": "Short human label for the artifact filename"
                    }
                },
                "required": ["prompt"]
            }),
            read_only: false,
        }
    }

    async fn execute(&self, input: &Value, root: &std::path::Path) -> ToolOutput {
        let Some(prompt) = input.get("prompt").and_then(|v| v.as_str()) else {
            return ToolOutput::Error {
                message: "`prompt` is required".into(),
            };
        };
        let duration_secs = match input.get("duration_secs") {
            None => DEFAULT_VIDEO_DURATION_SECS,
            Some(v) => match v.as_u64().and_then(|secs| u32::try_from(secs).ok()) {
                Some(secs) if secs >= 1 => secs,
                _ => {
                    return ToolOutput::Error {
                        message: "`duration_secs` must be a positive integer".into(),
                    };
                }
            },
        };
        let mut request = VideoRequest::new(prompt, duration_secs);
        if let Some(label) = input.get("label").and_then(|v| v.as_str()) {
            request.label = label.to_string();
        }

        let operation_id = operation_key(
            self.operation_ids.as_ref(),
            MediaKind::Video,
            self.provider.id(),
        );
        request.operation_id = Some(operation_id.clone());
        let jobs = open_jobs(root);
        match jobs.claim_operation(&operation_id, MediaKind::Video, self.provider.id()) {
            Ok(None) => {}
            Ok(Some(MediaOperationState::VideoSubmitted { provider_job_id })) => {
                return match jobs.get(&provider_job_id) {
                    Ok(Some(job)) => video_submitted(&job),
                    Ok(None) => {
                        reconciliation_required(&operation_id, "persisted video handle is missing")
                    }
                    Err(error) => reconciliation_required(&operation_id, error),
                };
            }
            Ok(Some(MediaOperationState::VideoCompleted {
                provider_job_id,
                artifact_path,
            })) => {
                return ToolOutput::Ok {
                    content: format!(
                        "video job `{provider_job_id}` already completed → {artifact_path}"
                    ),
                };
            }
            Ok(Some(state)) => {
                return reconciliation_required(&operation_id, format!("state {state:?}"));
            }
            Err(error) => {
                return ToolOutput::Error {
                    message: format!("media_operation_journal_unavailable: {error}"),
                };
            }
        }
        let estimate = self.provider.capabilities().estimate_video(duration_secs);
        let spend_request = MediaSpendRequest::new(
            operation_id.clone(),
            MediaKind::Video,
            self.provider.id(),
            estimate.as_ref().map(|estimate| estimate.estimated_usd),
            estimate.map_or_else(
                || format!("{duration_secs}s video (cost unavailable)"),
                |estimate| estimate.detail,
            ),
        );
        if self.spend_gate.authorize(&spend_request).await != CostDecision::Approve {
            if let Err(error) = jobs.cancel_operation(&operation_id) {
                return reconciliation_required(&operation_id, error);
            }
            return spend_denied(&spend_request);
        }

        let job = match self.provider.generate_video(request).await {
            Ok(job) => job,
            Err(error) => return reconciliation_required(&operation_id, error),
        };
        // Persist the handle BEFORE reporting success — a paid job whose id
        // exists only in this reply would be orphaned by a dropped session.
        if let Err(error) = jobs.complete_video_operation(&operation_id, &job) {
            return reconciliation_required(&operation_id, error);
        }
        video_submitted(&job)
    }
}

pub struct PollVideo(pub Arc<dyn MediaProvider>);

#[async_trait]
impl Tool for PollVideo {
    fn schema(&self) -> ToolSchema {
        ToolSchema {
            name: "poll_video".into(),
            description: "Check a video job submitted with generate_video, reconciling its \
                          state live against the provider. On success the video is saved \
                          under .stella/artifacts/ and the file path is returned; while \
                          queued/running, call again after a short wait."
                .into(),
            input_schema: serde_json::json!({
                "type": "object",
                "properties": {
                    "job_id": {
                        "type": "string",
                        "description": "The provider job id returned by generate_video"
                    }
                },
                "required": ["job_id"]
            }),
            read_only: false,
        }
    }

    async fn execute(&self, input: &Value, root: &std::path::Path) -> ToolOutput {
        let Some(job_id) = input.get("job_id").and_then(|v| v.as_str()) else {
            return ToolOutput::Error {
                message: "`job_id` is required".into(),
            };
        };
        let jobs = open_jobs(root);
        // The persisted handle supplies the identity assigned at submit
        // (artifact id, label); the state below never comes from it.
        let job = match jobs.get(job_id) {
            Ok(Some(job)) => job,
            Ok(None) => {
                return ToolOutput::Error {
                    message: format!(
                        "no persisted video job `{job_id}` — was it submitted with \
                         generate_video?"
                    ),
                };
            }
            Err(e) => {
                return ToolOutput::Error {
                    message: format!("video job store unavailable: {e}"),
                };
            }
        };
        // Live reconciliation (L-V3): report the provider's answer, never a
        // cached state.
        let status = match stella_media::resume(&jobs, self.0.as_ref(), job_id).await {
            Ok(status) => status,
            Err(e) => {
                return ToolOutput::Error {
                    message: format!("video poll failed: {e}"),
                };
            }
        };
        match status.state {
            MediaJobState::Succeeded => {
                let Some(artifact) = status.artifact else {
                    return ToolOutput::Error {
                        message: format!(
                            "video job `{job_id}` succeeded but the provider returned no \
                             artifact"
                        ),
                    };
                };
                let store = match open_store(root) {
                    Ok(s) => s,
                    Err(e) => return e,
                };
                // Persist under the id assigned at submit, so events and the
                // final file share one identity across a resume.
                match store.save_with_id(
                    &job.artifact_id,
                    &artifact.bytes,
                    artifact.kind,
                    &artifact.extension,
                    &artifact.label,
                ) {
                    Ok(saved) => {
                        if let Err(error) = jobs.complete_video_job(job_id, &saved.path) {
                            return reconciliation_required(job_id, error);
                        }
                        ToolOutput::Ok {
                            content: format!(
                                "video \"{}\" → {} (model {}, ${:.4})",
                                saved.label, saved.path, artifact.model, artifact.cost_usd
                            ),
                        }
                    }
                    Err(e) => ToolOutput::Error {
                        message: format!("could not persist the video: {e}"),
                    },
                }
            }
            MediaJobState::Failed { reason } => {
                let _ = jobs.remove(job_id);
                ToolOutput::Error {
                    message: format!("video job `{job_id}` failed: {reason}"),
                }
            }
            MediaJobState::Queued | MediaJobState::Running => {
                let state = match status.state {
                    MediaJobState::Queued => "queued",
                    _ => "running",
                };
                let progress = status
                    .progress
                    .map(|p| format!(" ({:.0}% reported)", p * 100.0))
                    .unwrap_or_default();
                ToolOutput::Ok {
                    content: format!(
                        "video job `{job_id}` is {state}{progress} — poll again after a \
                         short wait"
                    ),
                }
            }
        }
    }
}

pub struct GenerateSvg;

#[async_trait]
impl Tool for GenerateSvg {
    fn schema(&self) -> ToolSchema {
        ToolSchema {
            name: "generate_svg".into(),
            description: format!(
                "Validate, sanitize, and save an SVG document you authored to \
                 .stella/artifacts/, returning the file path. The SVG is treated as \
                 untrusted code: scripts, event handlers, and external references are \
                 stripped. If it fails to parse, the error names the offending line and \
                 column — fix the SVG and retry (up to {DEFAULT_SVG_ATTEMPTS} attempts \
                 total)."
            ),
            input_schema: serde_json::json!({
                "type": "object",
                "properties": {
                    "svg": {
                        "type": "string",
                        "description": "The complete SVG document (<svg …>…</svg>)"
                    },
                    "label": {
                        "type": "string",
                        "description": "Short human label for the artifact filename"
                    }
                },
                "required": ["svg"]
            }),
            read_only: false,
        }
    }

    async fn execute(&self, input: &Value, root: &std::path::Path) -> ToolOutput {
        let Some(svg) = input.get("svg").and_then(|v| v.as_str()) else {
            return ToolOutput::Error {
                message: "`svg` is required".into(),
            };
        };
        // The bounded repair loop maps onto the agent
        // loop here: a failed attempt returns the parse error for the model
        // to fix, instead of driving an in-process `SvgGenerator` (that port
        // stays for model-backed CLI glue).
        let processed = match SvgPipeline::process(svg) {
            Ok(p) => p,
            Err(e) => {
                return ToolOutput::Error {
                    message: format!("invalid SVG: {e}"),
                };
            }
        };
        let label = input.get("label").and_then(|v| v.as_str()).unwrap_or("svg");
        let store = match open_store(root) {
            Ok(s) => s,
            Err(e) => return e,
        };
        match store.save(processed.svg.as_bytes(), MediaKind::Svg, label) {
            Ok(saved) => {
                let sanitized = if processed.removed.is_empty() {
                    String::new()
                } else {
                    format!(" — sanitized: stripped {}", processed.removed.join(", "))
                };
                ToolOutput::Ok {
                    content: format!("svg \"{}\" → {}{sanitized}", saved.label, saved.path),
                }
            }
            Err(e) => ToolOutput::Error {
                message: format!("could not persist the SVG: {e}"),
            },
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::atomic::{AtomicUsize, Ordering};
    use stella_media::{
        CostDecision, MediaArtifact, MediaCapabilities, MediaError, MediaJob, MediaJobStatus,
        MediaKind, MediaSpendGate, MediaSpendRequest, VideoRequest,
    };

    /// A deterministic in-memory provider: one fixed PNG-ish artifact, no
    /// network — the same fake-backed seam discipline as the fleet/monitor
    /// ports.
    struct FakeImages;

    #[async_trait]
    impl MediaProvider for FakeImages {
        fn id(&self) -> &str {
            "fake"
        }
        fn capabilities(&self) -> MediaCapabilities {
            MediaCapabilities::default()
        }
        async fn generate_image(&self, req: ImageRequest) -> Result<MediaArtifact, MediaError> {
            if req.prompt.contains("refuse me") {
                return Err(MediaError::ContentPolicy("test refusal".into()));
            }
            Ok(MediaArtifact {
                kind: MediaKind::Image,
                bytes: vec![0x89, b'P', b'N', b'G'],
                extension: "png".into(),
                label: req.label,
                model: "fake-image-1".into(),
                cost_usd: 0.01,
            })
        }
        async fn generate_video(&self, _req: VideoRequest) -> Result<MediaJob, MediaError> {
            Err(MediaError::Transport("not under test".into()))
        }
        async fn poll_video(&self, _job: &MediaJob) -> Result<MediaJobStatus, MediaError> {
            Err(MediaError::Transport("not under test".into()))
        }
    }

    struct CountingImages {
        submits: AtomicUsize,
        manifest_blocker: Option<std::path::PathBuf>,
    }

    #[async_trait]
    impl MediaProvider for CountingImages {
        fn id(&self) -> &str {
            "counting"
        }

        fn capabilities(&self) -> MediaCapabilities {
            MediaCapabilities {
                provider_id: "counting".into(),
                image: true,
                image_usd_each: Some(0.01),
                ..Default::default()
            }
        }

        async fn generate_image(&self, req: ImageRequest) -> Result<MediaArtifact, MediaError> {
            let attempt = self.submits.fetch_add(1, Ordering::SeqCst);
            if attempt == 0
                && let Some(blocker) = &self.manifest_blocker
            {
                std::fs::create_dir_all(blocker).unwrap();
            }
            Ok(MediaArtifact {
                kind: MediaKind::Image,
                bytes: vec![0x89, b'P', b'N', b'G'],
                extension: "png".into(),
                label: req.label,
                model: "counting-image-1".into(),
                cost_usd: 0.01,
            })
        }

        async fn generate_video(&self, _req: VideoRequest) -> Result<MediaJob, MediaError> {
            Err(MediaError::Transport("not under test".into()))
        }

        async fn poll_video(&self, _job: &MediaJob) -> Result<MediaJobStatus, MediaError> {
            Err(MediaError::Transport("not under test".into()))
        }
    }

    struct ApproveSpendGate {
        calls: AtomicUsize,
    }

    struct FixedOperationIds(&'static str);

    impl MediaOperationIdSource for FixedOperationIds {
        fn operation_id(&self) -> String {
            self.0.to_string()
        }
    }

    #[async_trait]
    impl MediaSpendGate for ApproveSpendGate {
        async fn authorize(&self, _request: &MediaSpendRequest) -> CostDecision {
            self.calls.fetch_add(1, Ordering::SeqCst);
            CostDecision::Approve
        }
    }

    fn approving_gate() -> Arc<dyn MediaSpendGate> {
        Arc::new(ApproveSpendGate {
            calls: AtomicUsize::new(0),
        })
    }

    #[derive(Clone, Debug, PartialEq, Eq)]
    enum SubmissionEvent {
        Gate(MediaKind, String),
        Provider(MediaKind, String),
    }

    struct OrderedGate(Arc<std::sync::Mutex<Vec<SubmissionEvent>>>);

    #[async_trait]
    impl MediaSpendGate for OrderedGate {
        async fn authorize(&self, request: &MediaSpendRequest) -> CostDecision {
            self.0.lock().unwrap().push(SubmissionEvent::Gate(
                request.kind,
                request.operation_id.clone(),
            ));
            CostDecision::Approve
        }
    }

    struct OrderedProvider {
        events: Arc<std::sync::Mutex<Vec<SubmissionEvent>>>,
        image_price: Option<f64>,
        video_price: Option<f64>,
    }

    #[async_trait]
    impl MediaProvider for OrderedProvider {
        fn id(&self) -> &str {
            "ordered"
        }

        fn capabilities(&self) -> MediaCapabilities {
            MediaCapabilities {
                provider_id: "ordered".into(),
                image: true,
                video: true,
                image_usd_each: self.image_price,
                video_usd_per_second: self.video_price,
                ..Default::default()
            }
        }

        async fn generate_image(&self, req: ImageRequest) -> Result<MediaArtifact, MediaError> {
            self.events.lock().unwrap().push(SubmissionEvent::Provider(
                MediaKind::Image,
                req.operation_id.unwrap(),
            ));
            Ok(MediaArtifact {
                kind: MediaKind::Image,
                bytes: b"image".to_vec(),
                extension: "png".into(),
                label: req.label,
                model: "ordered-image".into(),
                cost_usd: self.image_price.unwrap_or_default(),
            })
        }

        async fn generate_video(&self, req: VideoRequest) -> Result<MediaJob, MediaError> {
            self.events.lock().unwrap().push(SubmissionEvent::Provider(
                MediaKind::Video,
                req.operation_id.unwrap(),
            ));
            Ok(MediaJob {
                artifact_id: "med_ordered".into(),
                provider_id: "ordered".into(),
                provider_job_id: "ordered-job".into(),
                kind: MediaKind::Video,
                model: "ordered-video".into(),
                estimated_cost_usd: self.video_price.unwrap_or_default() * 5.0,
                submitted_at: 1_700_000_000,
                label: req.label,
            })
        }

        async fn poll_video(&self, _job: &MediaJob) -> Result<MediaJobStatus, MediaError> {
            Err(MediaError::Transport("not under test".into()))
        }
    }

    #[tokio::test]
    async fn priced_and_unpriced_media_share_gate_then_provider_order() {
        for (kind, price, host_id) in [
            (MediaKind::Image, Some(0.01), "host-priced-image"),
            (MediaKind::Image, None, "host-unpriced-image"),
            (MediaKind::Video, Some(0.2), "host-priced-video"),
            (MediaKind::Video, None, "host-unpriced-video"),
        ] {
            let dir = tempfile::tempdir().unwrap();
            let events = Arc::new(std::sync::Mutex::new(Vec::new()));
            let provider = Arc::new(OrderedProvider {
                events: events.clone(),
                image_price: if kind == MediaKind::Image {
                    price
                } else {
                    None
                },
                video_price: if kind == MediaKind::Video {
                    price
                } else {
                    None
                },
            });
            let gate = Arc::new(OrderedGate(events.clone()));
            let ids = Arc::new(FixedOperationIds(host_id));
            let tool: Arc<dyn Tool> = match kind {
                MediaKind::Image => Arc::new(GenerateImage::with_host_context(provider, gate, ids)),
                MediaKind::Video => Arc::new(GenerateVideo::with_host_context(provider, gate, ids)),
                MediaKind::Svg => unreachable!(),
            };
            for _ in 0..2 {
                let out = tool
                    .execute(&serde_json::json!({"prompt": "same"}), dir.path())
                    .await;
                assert!(matches!(out, ToolOutput::Ok { .. }), "{out:?}");
            }
            let actual = events.lock().unwrap().clone();
            assert_eq!(actual.len(), 2, "{kind:?} at {price:?}: {actual:?}");
            let operation_id = match &actual[0] {
                SubmissionEvent::Gate(_, operation_id) => operation_id.clone(),
                event => panic!("gate must be first: {event:?}"),
            };
            assert_eq!(
                actual,
                vec![
                    SubmissionEvent::Gate(kind, operation_id.clone()),
                    SubmissionEvent::Provider(kind, operation_id),
                ]
            );
        }
    }

    fn tool() -> GenerateImage {
        GenerateImage::with_host_context(
            Arc::new(FakeImages),
            approving_gate(),
            Arc::new(FixedOperationIds("host-test-image")),
        )
    }

    #[test]
    fn schema_is_mutating_and_named() {
        let schema = tool().schema();
        assert_eq!(schema.name, "generate_image");
        assert!(!schema.read_only);
    }

    #[tokio::test]
    async fn image_without_a_host_gate_is_denied_before_submission() {
        let dir = tempfile::tempdir().expect("tempdir");
        let provider = Arc::new(CountingImages {
            submits: AtomicUsize::new(0),
            manifest_blocker: None,
        });
        let out = GenerateImage::new(provider.clone())
            .execute(&serde_json::json!({"prompt": "a star"}), dir.path())
            .await;
        match out {
            ToolOutput::Error { message } => {
                assert!(message.contains("host approval"), "{message}");
            }
            ToolOutput::Ok { content } => panic!("the host gate must deny: {content}"),
        }
        assert_eq!(provider.submits.load(Ordering::SeqCst), 0);
    }

    #[tokio::test]
    async fn approving_host_gate_allows_exactly_one_provider_submission() {
        let provider = Arc::new(CountingImages {
            submits: AtomicUsize::new(0),
            manifest_blocker: None,
        });
        let gate = Arc::new(ApproveSpendGate {
            calls: AtomicUsize::new(0),
        });
        let backend = || MediaBackend {
            image: provider.clone(),
            video: None,
        };

        let denied_root = tempfile::tempdir().expect("tempdir");
        let denied = crate::registry::ToolRegistry::with_backends_and_options(
            denied_root.path().to_path_buf(),
            None,
            Some(backend()),
            crate::registry::RegistryOptions {
                media_requires_host_approval: false,
                media_spend_gate: Some(gate.clone()),
                media_operation_ids: Some(Arc::new(FixedOperationIds("host-denied-image"))),
                ..Default::default()
            },
        );
        let denied_out = denied
            .execute("generate_image", &serde_json::json!({"prompt": "a star"}))
            .await;
        assert!(denied_out.is_error(), "{denied_out:?}");
        assert_eq!(provider.submits.load(Ordering::SeqCst), 0);

        let missing_id_root = tempfile::tempdir().expect("tempdir");
        let missing_id = crate::registry::ToolRegistry::with_backends_and_options(
            missing_id_root.path().to_path_buf(),
            None,
            Some(backend()),
            crate::registry::RegistryOptions {
                media_requires_host_approval: true,
                media_spend_gate: Some(gate.clone()),
                ..Default::default()
            },
        );
        let missing_id_out = missing_id
            .execute("generate_image", &serde_json::json!({"prompt": "a star"}))
            .await;
        assert!(missing_id_out.is_error(), "{missing_id_out:?}");
        assert_eq!(gate.calls.load(Ordering::SeqCst), 0);
        assert_eq!(provider.submits.load(Ordering::SeqCst), 0);

        let approved_root = tempfile::tempdir().expect("tempdir");
        let approved = crate::registry::ToolRegistry::with_backends_and_options(
            approved_root.path().to_path_buf(),
            None,
            Some(backend()),
            crate::registry::RegistryOptions {
                media_requires_host_approval: true,
                media_spend_gate: Some(gate.clone()),
                media_operation_ids: Some(Arc::new(FixedOperationIds("host-approved-image"))),
                ..Default::default()
            },
        );
        let approved_out = approved
            .execute("generate_image", &serde_json::json!({"prompt": "a star"}))
            .await;

        assert!(!approved_out.is_error(), "{approved_out:?}");
        assert_eq!(gate.calls.load(Ordering::SeqCst), 1);
        assert_eq!(provider.submits.load(Ordering::SeqCst), 1);
    }

    #[tokio::test]
    async fn generates_and_persists_under_stella_artifacts() {
        let dir = tempfile::tempdir().expect("tempdir");
        let out = tool()
            .execute(
                &serde_json::json!({"prompt": "a star", "label": "star"}),
                dir.path(),
            )
            .await;
        match out {
            ToolOutput::Ok { content } => {
                assert!(content.contains("star"), "labels the artifact: {content}");
                assert!(content.contains("fake-image-1"), "names the model");
                // The artifact actually landed inside .stella/artifacts/.
                let artifacts = dir.path().join(".stella").join("artifacts");
                let count = std::fs::read_dir(&artifacts)
                    .map(|d| d.filter_map(Result::ok).count())
                    .unwrap_or(0);
                assert!(count >= 1, "one artifact on disk");
            }
            ToolOutput::Error { message } => panic!("expected success: {message}"),
        }
    }

    #[tokio::test]
    async fn refusal_and_bad_size_and_missing_prompt_are_named_errors() {
        let dir = tempfile::tempdir().expect("tempdir");
        let refused = tool()
            .execute(&serde_json::json!({"prompt": "refuse me"}), dir.path())
            .await;
        match refused {
            ToolOutput::Error { message } => assert!(message.contains("content policy")),
            ToolOutput::Ok { .. } => panic!("refusal must surface as an error"),
        }
        let bad_size = tool()
            .execute(
                &serde_json::json!({"prompt": "ok", "size": "huge"}),
                dir.path(),
            )
            .await;
        assert!(matches!(bad_size, ToolOutput::Error { .. }));
        let no_prompt = tool().execute(&serde_json::json!({}), dir.path()).await;
        assert!(matches!(no_prompt, ToolOutput::Error { .. }));
    }

    // ---- video --------------------------------------------------------

    /// A deterministic video provider: fixed job handle, scripted poll
    /// state, no network — proves the tool pair drives the gate, the job
    /// store, and the artifact store, not the wire.
    struct FakeVideo {
        usd_per_second: Option<f64>,
        state: std::sync::Mutex<MediaJobState>,
        submits: AtomicUsize,
        journal_blocker: Option<std::path::PathBuf>,
    }

    impl FakeVideo {
        fn new(usd_per_second: Option<f64>, state: MediaJobState) -> Arc<Self> {
            Arc::new(Self {
                usd_per_second,
                state: std::sync::Mutex::new(state),
                submits: AtomicUsize::new(0),
                journal_blocker: None,
            })
        }

        fn with_journal_blocker(blocker: std::path::PathBuf) -> Arc<Self> {
            Arc::new(Self {
                usd_per_second: Some(0.2),
                state: std::sync::Mutex::new(MediaJobState::Running),
                submits: AtomicUsize::new(0),
                journal_blocker: Some(blocker),
            })
        }
    }

    #[async_trait]
    impl MediaProvider for FakeVideo {
        fn id(&self) -> &str {
            "fake"
        }
        fn capabilities(&self) -> MediaCapabilities {
            MediaCapabilities {
                provider_id: "fake".into(),
                video: true,
                video_usd_per_second: self.usd_per_second,
                ..Default::default()
            }
        }
        async fn generate_image(&self, _req: ImageRequest) -> Result<MediaArtifact, MediaError> {
            Err(MediaError::Transport("not under test".into()))
        }
        async fn generate_video(&self, req: VideoRequest) -> Result<MediaJob, MediaError> {
            let attempt = self.submits.fetch_add(1, Ordering::SeqCst);
            if attempt == 0
                && let Some(blocker) = &self.journal_blocker
            {
                std::fs::create_dir_all(blocker).unwrap();
            }
            let estimated_cost_usd = self
                .capabilities()
                .estimate_video(req.duration_secs)
                .map(|e| e.estimated_usd)
                .unwrap_or(0.0);
            Ok(MediaJob {
                artifact_id: "med_fake".into(),
                provider_id: "fake".into(),
                provider_job_id: format!("vid-{}", attempt + 1),
                kind: MediaKind::Video,
                model: "fake-video-1".into(),
                estimated_cost_usd,
                submitted_at: 1_700_000_000,
                label: req.label,
            })
        }
        async fn poll_video(&self, job: &MediaJob) -> Result<MediaJobStatus, MediaError> {
            let state = self.state.lock().expect("lock").clone();
            let artifact = matches!(state, MediaJobState::Succeeded).then(|| MediaArtifact {
                kind: MediaKind::Video,
                bytes: b"mp4-bytes".to_vec(),
                extension: "mp4".into(),
                label: job.label.clone(),
                model: job.model.clone(),
                cost_usd: job.estimated_cost_usd,
            });
            Ok(MediaJobStatus {
                state,
                progress: None,
                artifact,
            })
        }
    }

    fn job_store(root: &std::path::Path) -> JobStore {
        JobStore::open(root.join(".stella").join("artifacts"))
    }

    /// Submit through an approving host gate so poll tests exercise the real
    /// persisted handle.
    async fn submit(fake: &Arc<FakeVideo>, root: &std::path::Path) {
        let out = GenerateVideo::with_host_context(
            fake.clone(),
            approving_gate(),
            Arc::new(FixedOperationIds("host-submit-video")),
        )
        .execute(&serde_json::json!({"prompt": "a teaser"}), root)
        .await;
        assert!(matches!(out, ToolOutput::Ok { .. }), "{out:?}");
    }

    #[test]
    fn video_and_svg_schemas_are_mutating_and_named() {
        let fake = FakeVideo::new(Some(0.2), MediaJobState::Running);
        for (schema, name) in [
            (
                GenerateVideo::with_host_context(
                    fake.clone(),
                    approving_gate(),
                    Arc::new(FixedOperationIds("host-schema-video")),
                )
                .schema(),
                "generate_video",
            ),
            (PollVideo(fake).schema(), "poll_video"),
            (GenerateSvg.schema(), "generate_svg"),
        ] {
            assert_eq!(schema.name, name);
            assert!(!schema.read_only);
            assert!(
                schema.input_schema["properties"]
                    .get("confirm_spend")
                    .is_none(),
                "model schemas must not expose spend authority"
            );
        }
    }

    #[tokio::test]
    async fn video_without_a_host_gate_is_denied_before_submission() {
        let dir = tempfile::tempdir().expect("tempdir");
        let fake = FakeVideo::new(Some(0.2), MediaJobState::Running);
        let out = GenerateVideo::new(fake.clone())
            .execute(&serde_json::json!({"prompt": "a teaser"}), dir.path())
            .await;
        match out {
            ToolOutput::Error { message } => {
                assert!(message.contains("host approval"), "{message}");
            }
            ToolOutput::Ok { content } => panic!("the gate must deny: {content}"),
        }
        assert_eq!(
            fake.submits.load(Ordering::SeqCst),
            0,
            "a denied job must never reach the provider"
        );
        assert!(job_store(dir.path()).list().unwrap().is_empty());
    }

    #[tokio::test]
    async fn model_controlled_confirm_spend_cannot_authorize_video() {
        let dir = tempfile::tempdir().expect("tempdir");
        let fake = FakeVideo::new(Some(0.2), MediaJobState::Running);
        let out = GenerateVideo::new(fake.clone())
            .execute(
                &serde_json::json!({
                    "prompt": "a teaser", "duration_secs": 10,
                    "confirm_spend": true, "label": "teaser"
                }),
                dir.path(),
            )
            .await;
        match out {
            ToolOutput::Error { message } => {
                assert!(message.contains("host approval"), "{message}");
            }
            ToolOutput::Ok { content } => {
                panic!("model-controlled consent must not pass: {content}")
            }
        }
        assert_eq!(fake.submits.load(Ordering::SeqCst), 0);
        assert!(job_store(dir.path()).list().unwrap().is_empty());
    }

    #[tokio::test]
    async fn video_without_a_rate_card_still_requires_host_approval() {
        let dir = tempfile::tempdir().expect("tempdir");
        let fake = FakeVideo::new(None, MediaJobState::Running);
        let out = GenerateVideo::new(fake.clone())
            .execute(&serde_json::json!({"prompt": "a teaser"}), dir.path())
            .await;
        assert!(matches!(out, ToolOutput::Error { .. }), "{out:?}");
        assert_eq!(fake.submits.load(Ordering::SeqCst), 0);
    }

    #[tokio::test]
    async fn video_completion_journal_failure_is_reconciliation_required_and_retry_safe() {
        let dir = tempfile::tempdir().expect("tempdir");
        let blocker = dir
            .path()
            .join(".stella")
            .join("artifacts")
            .join("jobs.json.lock");
        let fake = FakeVideo::with_journal_blocker(blocker.clone());
        let tool = GenerateVideo::with_host_context(
            fake.clone(),
            approving_gate(),
            Arc::new(FixedOperationIds("host-retry-video")),
        );
        let input = serde_json::json!({"prompt": "a teaser"});

        let first = tool.execute(&input, dir.path()).await;
        let ToolOutput::Error { message } = first else {
            panic!("persistence failure must be terminal: {first:?}");
        };
        assert!(message.contains("reconciliation_required"), "{message}");
        assert!(!message.contains("a teaser"), "{message}");
        assert_eq!(fake.submits.load(Ordering::SeqCst), 1);

        std::fs::remove_dir(&blocker).unwrap();
        let retry = tool.execute(&input, dir.path()).await;
        let ToolOutput::Error { message } = retry else {
            panic!("an ambiguous pending operation must not resubmit: {retry:?}");
        };
        assert!(message.contains("reconciliation_required"), "{message}");
        assert_eq!(fake.submits.load(Ordering::SeqCst), 1);
    }

    #[tokio::test]
    async fn image_artifact_failure_is_reconciliation_required_and_retry_safe() {
        let dir = tempfile::tempdir().expect("tempdir");
        let blocker = dir
            .path()
            .join(".stella")
            .join("artifacts")
            .join(".manifest.json.tmp");
        let provider = Arc::new(CountingImages {
            submits: AtomicUsize::new(0),
            manifest_blocker: Some(blocker.clone()),
        });
        let tool = GenerateImage::with_host_context(
            provider.clone(),
            approving_gate(),
            Arc::new(FixedOperationIds("host-retry-image")),
        );
        let input = serde_json::json!({"prompt": "a star"});

        let first = tool.execute(&input, dir.path()).await;
        let ToolOutput::Error { message } = first else {
            panic!("artifact failure must be terminal: {first:?}");
        };
        assert!(message.contains("reconciliation_required"), "{message}");
        assert!(!message.contains("a star"), "{message}");
        assert_eq!(provider.submits.load(Ordering::SeqCst), 1);

        std::fs::remove_dir(&blocker).unwrap();
        let retry = tool.execute(&input, dir.path()).await;
        assert!(matches!(retry, ToolOutput::Error { .. }), "{retry:?}");
        assert_eq!(provider.submits.load(Ordering::SeqCst), 1);
    }

    #[tokio::test]
    async fn distinct_host_operation_ids_allow_intentional_identical_video_generations() {
        let dir = tempfile::tempdir().expect("tempdir");
        let fake = FakeVideo::new(Some(0.2), MediaJobState::Running);
        let input = serde_json::json!({"prompt": "same teaser"});
        for operation_id in ["host-intent-one", "host-intent-two"] {
            let out = GenerateVideo::with_host_context(
                fake.clone(),
                approving_gate(),
                Arc::new(FixedOperationIds(operation_id)),
            )
            .execute(&input, dir.path())
            .await;
            assert!(matches!(out, ToolOutput::Ok { .. }), "{out:?}");
        }
        assert_eq!(fake.submits.load(Ordering::SeqCst), 2);
    }

    #[tokio::test]
    async fn poll_running_keeps_the_job_persisted() {
        let dir = tempfile::tempdir().expect("tempdir");
        let fake = FakeVideo::new(Some(0.2), MediaJobState::Running);
        submit(&fake, dir.path()).await;
        let out = PollVideo(fake)
            .execute(&serde_json::json!({"job_id": "vid-1"}), dir.path())
            .await;
        match out {
            ToolOutput::Ok { content } => assert!(content.contains("running"), "{content}"),
            ToolOutput::Error { message } => panic!("expected running status: {message}"),
        }
        assert!(
            job_store(dir.path()).get("vid-1").unwrap().is_some(),
            "a non-terminal poll must keep the handle"
        );
    }

    #[tokio::test]
    async fn poll_success_persists_the_video_and_forgets_the_job() {
        let dir = tempfile::tempdir().expect("tempdir");
        let fake = FakeVideo::new(Some(0.2), MediaJobState::Succeeded);
        submit(&fake, dir.path()).await;
        let out = PollVideo(fake.clone())
            .execute(&serde_json::json!({"job_id": "vid-1"}), dir.path())
            .await;
        match out {
            ToolOutput::Ok { content } => {
                // Saved under the artifact id assigned at submit.
                assert!(content.contains("med_fake.mp4"), "{content}");
            }
            ToolOutput::Error { message } => panic!("expected success: {message}"),
        }
        let file = dir
            .path()
            .join(".stella")
            .join("artifacts")
            .join("med_fake.mp4");
        assert_eq!(std::fs::read(&file).unwrap(), b"mp4-bytes");
        assert!(
            job_store(dir.path()).get("vid-1").unwrap().is_none(),
            "a terminal, persisted job is forgotten"
        );
        let replay = GenerateVideo::with_host_context(
            fake.clone(),
            approving_gate(),
            Arc::new(FixedOperationIds("host-submit-video")),
        )
        .execute(&serde_json::json!({"prompt": "a teaser"}), dir.path())
        .await;
        assert!(matches!(replay, ToolOutput::Ok { .. }), "{replay:?}");
        assert_eq!(fake.submits.load(Ordering::SeqCst), 1);
        // A second poll of the forgotten job is a named error, never a
        // stale replay.
        let again = PollVideo(fake)
            .execute(&serde_json::json!({"job_id": "vid-1"}), dir.path())
            .await;
        assert!(matches!(again, ToolOutput::Error { .. }), "{again:?}");
    }

    #[tokio::test]
    async fn poll_failure_reports_the_reason_and_forgets_the_job() {
        let dir = tempfile::tempdir().expect("tempdir");
        let fake = FakeVideo::new(
            Some(0.2),
            MediaJobState::Failed {
                reason: "provider purged the job".into(),
            },
        );
        submit(&fake, dir.path()).await;
        let out = PollVideo(fake)
            .execute(&serde_json::json!({"job_id": "vid-1"}), dir.path())
            .await;
        match out {
            ToolOutput::Error { message } => assert!(message.contains("purged"), "{message}"),
            ToolOutput::Ok { content } => panic!("a failed job must error: {content}"),
        }
        assert!(job_store(dir.path()).get("vid-1").unwrap().is_none());
    }

    #[tokio::test]
    async fn poll_unknown_job_and_missing_id_are_named_errors() {
        let dir = tempfile::tempdir().expect("tempdir");
        let fake = FakeVideo::new(Some(0.2), MediaJobState::Running);
        let unknown = PollVideo(fake.clone())
            .execute(&serde_json::json!({"job_id": "ghost"}), dir.path())
            .await;
        match unknown {
            ToolOutput::Error { message } => assert!(message.contains("ghost"), "{message}"),
            ToolOutput::Ok { content } => panic!("unknown job must error: {content}"),
        }
        let no_id = PollVideo(fake)
            .execute(&serde_json::json!({}), dir.path())
            .await;
        assert!(matches!(no_id, ToolOutput::Error { .. }));
    }

    // ---- svg ----------------------------------------------------------

    #[tokio::test]
    async fn svg_is_sanitized_and_persisted() {
        let dir = tempfile::tempdir().expect("tempdir");
        let hostile = r#"<svg xmlns="http://www.w3.org/2000/svg" width="4" height="4"><script>x()</script><rect/></svg>"#;
        let out = GenerateSvg
            .execute(
                &serde_json::json!({"svg": hostile, "label": "icon"}),
                dir.path(),
            )
            .await;
        match out {
            ToolOutput::Ok { content } => {
                assert!(content.contains(".svg"), "{content}");
                assert!(
                    content.contains("stripped"),
                    "reports sanitization: {content}"
                );
                // The persisted artifact is the sanitized text, not the input.
                let artifacts = dir.path().join(".stella").join("artifacts");
                let svg_file = std::fs::read_dir(&artifacts)
                    .unwrap()
                    .filter_map(Result::ok)
                    .find(|e| e.path().extension().is_some_and(|x| x == "svg"))
                    .expect("svg on disk");
                let text = std::fs::read_to_string(svg_file.path()).unwrap();
                assert!(!text.contains("script"), "{text}");
                assert!(text.contains("<rect"), "{text}");
            }
            ToolOutput::Error { message } => panic!("expected success: {message}"),
        }
    }

    #[tokio::test]
    async fn malformed_svg_is_a_repairable_named_error() {
        let dir = tempfile::tempdir().expect("tempdir");
        let out = GenerateSvg
            .execute(&serde_json::json!({"svg": "<svg><rect></svg>"}), dir.path())
            .await;
        match out {
            // The line/col detail is what lets the model repair and retry.
            ToolOutput::Error { message } => assert!(message.contains("parse error"), "{message}"),
            ToolOutput::Ok { content } => panic!("malformed SVG must error: {content}"),
        }
        let no_svg = GenerateSvg
            .execute(&serde_json::json!({}), dir.path())
            .await;
        assert!(matches!(no_svg, ToolOutput::Error { .. }));
    }
}
