import "./global.css";
import type { Metadata, Viewport } from "next";
import type { ReactNode } from "react";
import { Space_Grotesk } from "next/font/google";
import { RootProvider } from "fumadocs-ui/provider/next";

/**
 * The brand face. The wordmark is Space Grotesk Medium drawn as outlines, so
 * loading the family here lets brand-name text on the page match the logo
 * instead of approximating it with a generic mono. Body copy is untouched.
 */
const brandFont = Space_Grotesk({
  subsets: ["latin"],
  weight: ["500"],
  variable: "--font-brand",
  display: "swap",
});

const SITE_URL = "https://stella.oxagen.sh";
const SITE_NAME = "Stella CLI";
const SITE_DESCRIPTION =
  "Documentation for the Stella CLI — a fast, BYOK, model-agnostic terminal coding agent.";
// OG + Twitter card images are generated by src/app/opengraph-image.tsx and
// twitter-image.tsx (neutral, next/og) — Next wires them into metadata.

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: "Stella CLI — Docs",
    template: "%s — Stella CLI",
  },
  description: SITE_DESCRIPTION,
  applicationName: SITE_NAME,
  appleWebApp: {
    capable: true,
    title: "Stella",
    statusBarStyle: "black-translucent",
  },
  openGraph: {
    title: "Stella CLI — Docs",
    description: SITE_DESCRIPTION,
    url: SITE_URL,
    siteName: SITE_NAME,
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Stella CLI — Docs",
    description: SITE_DESCRIPTION,
  },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  themeColor: [
    { media: "(prefers-color-scheme: dark)", color: "#080d1a" }, // --stella-ground
    { media: "(prefers-color-scheme: light)", color: "#ffffff" }, // --stella-paper
  ],
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning className={brandFont.variable}>
      <body className="flex min-h-screen flex-col">
        <RootProvider>{children}</RootProvider>
      </body>
    </html>
  );
}
