import "./global.css";
import type { Metadata, Viewport } from "next";
import type { ReactNode } from "react";
import localFont from "next/font/local";
import { RootProvider } from "fumadocs-ui/provider/next";
import { Analytics } from "@vercel/analytics/next";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { SITE_NAME, SITE_URL } from "@/lib/site";

/**
 * Three faces, each doing the job it exists for, vendored from the Oxagen house
 * kit by `scripts/sync-brand-assets.mjs`.
 *
 * SPACE GROTESK is the display face: h1 to h3 and the `stella*` wordmark, which
 * is this font's own outlines at weight 600. Never below 20px.
 *
 * GEIST is the text face: body, h4 to h6, UI, navigation.
 *
 * MONASPACE NEON is the code face: code and terminal transcripts, where column
 * alignment is load-bearing, with texture healing on.
 */
const display = localFont({
  src: [
    { path: "../fonts/space-grotesk-latin-500.woff2", weight: "500", style: "normal" },
    { path: "../fonts/space-grotesk-latin-600.woff2", weight: "600", style: "normal" },
    { path: "../fonts/space-grotesk-latin-700.woff2", weight: "700", style: "normal" },
  ],
  variable: "--font-stella-display",
  display: "swap",
});

const sans = localFont({
  src: "../fonts/geist-latin-wght.woff2",
  weight: "100 900",
  variable: "--font-stella-sans",
  display: "swap",
});

const mono = localFont({
  src: "../fonts/monaspace-neon-latin-wght.woff2",
  weight: "200 800",
  variable: "--font-stella-mono",
  display: "swap",
});

const SITE_DESCRIPTION =
  "Documentation for stella — the terminal agent. Fast, BYOK, model-agnostic, and it proves its work finished.";
// OG + Twitter card images are generated by src/app/opengraph-image.tsx and
// twitter-image.tsx (next/og) — Next wires them into metadata.

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  // lowercase always — the brand name never takes a capital, even in a tab.
  title: {
    default: "stella — docs",
    template: "%s — stella docs",
  },
  description: SITE_DESCRIPTION,
  alternates: { canonical: SITE_URL },
  applicationName: SITE_NAME,
  appleWebApp: {
    capable: true,
    title: "stella",
    statusBarStyle: "black-translucent",
  },
  openGraph: {
    title: "stella — docs",
    description: SITE_DESCRIPTION,
    url: SITE_URL,
    siteName: SITE_NAME,
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "stella — docs",
    description: SITE_DESCRIPTION,
  },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  themeColor: [
    { media: "(prefers-color-scheme: dark)", color: "#09090b" }, // --st-bg
    { media: "(prefers-color-scheme: light)", color: "#ffffff" }, // --st-paper-ground
  ],
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning className={`${display.variable} ${sans.variable} ${mono.variable}`}>
      <body className="flex min-h-screen flex-col">
        {/* First focusable node in the document, ahead of the Fumadocs header
         * and (on /docs) a ~90-link sidebar. Both route groups expose a
         * `#content` target at the top of their reading order. */}
        <a className="skip-link" href="#content">
          Skip to content
        </a>
        <RootProvider>{children}</RootProvider>
        {/* Vercel Web Analytics + Core Web Vitals. Both are cookie-less,
            no-op outside Vercel deployments, and served same-origin from
            /_vercel/* — nothing third-party enters the page. */}
        <Analytics />
        <SpeedInsights />
      </body>
    </html>
  );
}
