import "./global.css";
import type { Metadata, Viewport } from "next";
import type { ReactNode } from "react";
import { RootProvider } from "fumadocs-ui/provider/next";
import { Analytics } from "@vercel/analytics/next";
import { SpeedInsights } from "@vercel/speed-insights/next";
/*
 * The house faces load through the kit's own `next/font` loader, which
 * `scripts/sync-brand-assets.mjs` copies to `src/brand/next-fonts.ts` with the
 * font files beside it in `src/fonts/`. Space Grotesk sets h1 to h3 and the
 * wordmark, Aeonik sets everything else read, and Monaspace Neon sets code.
 * `src/brand/house-type.css`, which the same sync writes, maps the loader's
 * variables onto the site's font roles, and global.css points the heading
 * role at the display face.
 */
import { fontVariables } from "@/brand/next-fonts";
import { HOUSE_COLORS } from "@/components/brand-marks.generated";
import { SITE_NAME, SITE_URL } from "@/lib/site";

const SITE_DESCRIPTION =
  "Documentation for stella — the terminal agent. Fast, BYOK, model-agnostic, and it proves its work finished.";
// OG + Twitter card images are generated by src/app/opengraph-image.tsx and
// twitter-image.tsx (next/og) — Next wires them into metadata.

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  // lowercase always — the brand name never takes a capital, even in a tab.
  title: {
    default: "stella — docs",
    template: "%s — stella docs",
  },
  description: SITE_DESCRIPTION,
  alternates: { canonical: SITE_URL },
  applicationName: SITE_NAME,
  appleWebApp: {
    capable: true,
    title: "stella",
    statusBarStyle: "black-translucent",
  },
  openGraph: {
    title: "stella — docs",
    description: SITE_DESCRIPTION,
    url: SITE_URL,
    siteName: SITE_NAME,
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "stella — docs",
    description: SITE_DESCRIPTION,
  },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  themeColor: [
    { media: "(prefers-color-scheme: dark)", color: HOUSE_COLORS.ink },
    { media: "(prefers-color-scheme: light)", color: HOUSE_COLORS.paper },
  ],
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning className={fontVariables}>
      <body className="flex min-h-screen flex-col">
        {/* First focusable node in the document, ahead of the Fumadocs header
         * and (on /docs) a ~90-link sidebar. Both route groups expose a
         * `#content` target at the top of their reading order. */}
        <a className="skip-link" href="#content">
          Skip to content
        </a>
        <RootProvider>{children}</RootProvider>
        {/* Vercel Web Analytics + Core Web Vitals. Both are cookie-less,
            no-op outside Vercel deployments, and served same-origin from
            /_vercel/* — nothing third-party enters the page. */}
        <Analytics />
        <SpeedInsights />
      </body>
    </html>
  );
}
