//! Witness tests for the deterministic half of self-driving (#1548), ported from
//! `scripts/test-self-driving.sh` so the Rust implementation answers to the same
//! contract the shell driver did — plus the properties only a generator can
//! sweep. The failure modes here are SILENT and PERMANENT: a digest that
//! over-normalizes merges two defects and the second is never filed; a
//! controller that mislearns pins the batch ceiling forever; a fold that
//! trusts a stale heartbeat reports a crashed run as running to every reader.

use proptest::prelude::*;
use serde_json::json;

use super::*;

// ---------------------------------------------------------------------------
// digest — the dedup key the termination oracle rests on
// ---------------------------------------------------------------------------

/// Byte-parity with the shell pipeline that built every existing `seen.txt`
/// (`tr | sed | shasum -a 256 | cut -c1-16`). These hashes were generated by
/// running that pipeline; a divergence here re-reports every previously
/// triaged finding as new.
#[test]
fn digest_matches_the_shell_pipeline_goldens() {
    assert_eq!(
        finding_digest("crates/stella-core/src/driver.rs:812 retry counter never reset"),
        "a9efcba568ece91c"
    );
    assert_eq!(
        finding_digest("  Padded   And   Mixed:99Case  "),
        "a14d1857fdef58c3"
    );
    assert_eq!(
        finding_digest("unicode — em-dash · and:42:43 twice"),
        "034bf1e7a3e3b8a4"
    );
}

#[test]
fn line_number_case_and_whitespace_normalize_to_one_finding() {
    let a = finding_digest("crates/stella-core/src/driver.rs:812 retry counter never reset");
    let b = finding_digest("crates/stella-core/src/driver.rs:940    Retry Counter Never Reset");
    assert_eq!(a, b, "the same defect at a shifted line is one finding");

    let c = finding_digest("crates/stella-cli/src/agent.rs a different defect entirely");
    assert_ne!(a, c, "distinct findings keep distinct digests");
}

proptest! {
    /// The normalizations the digest promises, swept over ASCII descriptions
    /// (the shell's `tr` was byte-wise, so parity is an ASCII contract).
    #[test]
    fn digest_is_invariant_under_padding_case_and_line_numbers(s in "[ -~]{0,80}") {
        let base = finding_digest(&s);
        prop_assert_eq!(&finding_digest(&format!("  {s}  ")), &base);
        prop_assert_eq!(&finding_digest(&s.to_ascii_uppercase()), &base);
        prop_assert_eq!(
            &finding_digest(&format!("{s}:123 tail")),
            &finding_digest(&format!("{s}:7 tail"))
        );
    }
}

// ---------------------------------------------------------------------------
// AIMD — the only thing that moves the ceilings
// ---------------------------------------------------------------------------

#[test]
fn three_clean_runs_raise_the_parallel_ceiling_exactly_once() {
    let limits = AimdLimits::default();
    let mut cal = Calibration::seeded(&limits);
    for _ in 0..3 {
        calibrate(&mut cal, CycleOutcome::Ok, &limits);
    }
    assert_eq!(cal.parallel_ceiling, 3);
    assert_eq!(cal.clean_run, 3);
}

#[test]
fn a_resource_failure_halves_batch_and_resets_parallel_to_serial() {
    let limits = AimdLimits::default();
    let mut cal = Calibration::seeded(&limits);
    for _ in 0..3 {
        calibrate(&mut cal, CycleOutcome::Ok, &limits);
    }
    calibrate(&mut cal, CycleOutcome::ResourceFail, &limits);
    assert_eq!(
        (cal.batch_ceiling, cal.parallel_ceiling, cal.clean_run),
        (10, 1, 0)
    );
}

/// The regression that shipped in the shell driver: rebuilding the document
/// from the keys this module owns silently discarded every key it did not —
/// `last_clean_head` among them, leaving watch mode unable to ever sleep.
#[test]
fn calibrate_preserves_keys_it_does_not_own() {
    let raw = r#"{"batch_ceiling":20,"parallel_ceiling":2,"clean_run":0,
                  "note":"seeded","last_clean_head":"deadbeef"}"#;
    let mut cal: Calibration = serde_json::from_str(raw).expect("calibration parses");
    calibrate(&mut cal, CycleOutcome::Ok, &AimdLimits::default());
    let out = serde_json::to_value(&cal).expect("serializes");
    assert_eq!(out["last_clean_head"], "deadbeef");
}

proptest! {
    /// Whatever the evidence says, the ceilings stay inside the hard bounds —
    /// a controller that can wander out of range needs no adversary.
    #[test]
    fn the_ceilings_never_leave_their_hard_bounds(outcomes in prop::collection::vec(prop::bool::ANY, 0..64)) {
        let limits = AimdLimits::default();
        let mut cal = Calibration::seeded(&limits);
        for ok in outcomes {
            let outcome = if ok { CycleOutcome::Ok } else { CycleOutcome::ResourceFail };
            calibrate(&mut cal, outcome, &limits);
            prop_assert!(cal.batch_ceiling >= limits.batch_min);
            prop_assert!(cal.batch_ceiling <= limits.batch_max);
            prop_assert!(cal.parallel_ceiling >= 1);
            prop_assert!(cal.parallel_ceiling <= limits.parallel_max);
        }
    }
}

// ---------------------------------------------------------------------------
// aperture — why the loop never terminates, and what backs each lens (#1549)
// ---------------------------------------------------------------------------

#[test]
fn the_ladder_is_the_shell_drivers_ladder_in_order() {
    let names: Vec<&str> = LENSES.iter().map(|l| l.name).collect();
    assert_eq!(
        names,
        [
            "rubric",
            "properties",
            "invariants",
            "concurrency",
            "performance",
            "supply-chain",
            "security",
            "docs",
            "soak"
        ]
    );
}

#[test]
fn advancing_walks_every_lens_and_ends_in_watch_not_termination() {
    let mut current = "rubric";
    let mut walked = vec![current];
    loop {
        let next = advance(current);
        if next == WATCH {
            break;
        }
        walked.push(next);
        current = next;
    }
    assert_eq!(walked.len(), LENSES.len(), "every lens is reachable");
    assert_eq!(advance("soak"), WATCH);
    assert_eq!(advance(WATCH), WATCH, "watch is terminal, not an error");
    assert_eq!(advance("no-such-lens"), WATCH);
}

/// #1549's contract: no aperture is silently a no-op. Every lens either names
/// a concrete command a cycle runs and interprets, or is on the record as
/// model-only — so the model always knows whether it is working aided.
#[test]
fn every_lens_declares_its_tooling_or_admits_it_has_none() {
    for l in LENSES {
        match l.tooling {
            Tooling::Command { run, interpret } => {
                assert!(!run.trim().is_empty(), "{} names an empty command", l.name);
                assert!(
                    !interpret.trim().is_empty(),
                    "{} says nothing about interpreting its tool",
                    l.name
                );
            }
            Tooling::ModelOnly { note } => {
                assert!(
                    !note.trim().is_empty(),
                    "{} is model-only with no note — a silent no-op",
                    l.name
                );
            }
        }
    }
    let heavy: Vec<&str> = LENSES
        .iter()
        .filter(|l| l.heavy_only)
        .map(|l| l.name)
        .collect();
    assert_eq!(
        heavy,
        ["performance", "soak"],
        "the lenses that spend real money are gated on the heavy tier"
    );
}

// ---------------------------------------------------------------------------
// dry streak — per lens, and consecutive
// ---------------------------------------------------------------------------

fn cycle(cycle: u64, aperture: &str, dry: bool) -> CycleRecord {
    CycleRecord {
        cycle,
        run_id: String::new(),
        ended_at: String::new(),
        ended_at_unix: 0,
        fixed: 0,
        filed: 0,
        new_findings: u64::from(!dry),
        bench: String::new(),
        gate: "green".into(),
        prs: Vec::new(),
        tier: "normal".into(),
        aperture: aperture.into(),
        lens_tool: None,
        outcome: "ok".into(),
        minutes: 0,
        dry,
        extra: serde_json::Map::new(),
    }
}

#[test]
fn the_streak_is_scoped_to_the_current_lens() {
    // Two dry cycles advanced rubric; the fresh lens must not inherit them.
    let rows = vec![
        cycle(1, "rubric", false),
        cycle(2, "rubric", true),
        cycle(3, "rubric", true),
    ];
    assert_eq!(dry_streak(&rows, "rubric"), 2);
    assert_eq!(
        dry_streak(&rows, "properties"),
        0,
        "a fresh lens does not inherit the dry tail that opened it"
    );
}

#[test]
fn a_discovering_cycle_between_two_dry_ones_resets_the_streak() {
    let rows = vec![
        cycle(1, "rubric", true),
        cycle(2, "rubric", false),
        cycle(3, "rubric", true),
    ];
    assert_eq!(
        dry_streak(&rows, "rubric"),
        1,
        "dry-noise-dry never advances"
    );
}

proptest! {
    /// The streak is exactly the length of the maximal suffix of records that
    /// are dry AND under the queried lens — no simplification into "dry
    /// records in the tail" survives this.
    #[test]
    fn the_streak_is_the_maximal_matching_suffix(
        spec in prop::collection::vec((prop::bool::ANY, prop::bool::ANY), 0..24)
    ) {
        let rows: Vec<CycleRecord> = spec
            .iter()
            .enumerate()
            .map(|(i, (on_lens, dry))| {
                cycle(i as u64, if *on_lens { "rubric" } else { "properties" }, *dry)
            })
            .collect();
        let expected = rows
            .iter()
            .rev()
            .take_while(|r| r.aperture == "rubric" && r.dry)
            .count() as u32;
        prop_assert_eq!(dry_streak(&rows, "rubric"), expected);
    }
}

// ---------------------------------------------------------------------------
// the governor — the plan is a function of the machine
// ---------------------------------------------------------------------------
//
// One assertion shape for the whole ladder, ported case-for-case from
// scripts/test-self-driving.sh: pin a healthy 8-core / 16 GiB / 50 GiB baseline,
// apply one case's overrides, and compare the WHOLE decision tuple exactly —
// "light with the build still on" and "light with the build forbidden" are
// different decisions, and a single-field check lets one impersonate the
// other.

fn base_supply() -> Supply {
    Supply {
        cpu: 8,
        load1: 1,
        mem_total_gb: 16,
        mem_free_gb: 8,
        disk_free_gb: 50,
        on_battery: false,
        busy: false,
    }
}

fn ceilings() -> Calibration {
    Calibration::seeded(&AimdLimits::default())
}

#[track_caller]
fn assert_plan(supply: Supply, demand: Demand, want: (&str, bool, u32, &str, &str, u32, &str)) {
    let plan = plan_cycle(supply, demand, &ceilings(), Floors::default());
    let got = (
        plan.tier.as_str(),
        plan.local_build,
        plan.parallel,
        plan.scope.as_str(),
        plan.bench.as_str(),
        plan.batch,
        plan.audit.as_str(),
    );
    assert_eq!(got, want, "reason: {}", plan.reason);
}

#[test]
fn the_supply_rungs_decide_the_tier() {
    let d = Demand::default();
    assert_plan(
        base_supply(),
        d,
        ("normal", true, 2, "impacted", "loop", 20, "deep"),
    );

    let big = Supply {
        mem_total_gb: 64,
        mem_free_gb: 32,
        disk_free_gb: 200,
        ..base_supply()
    };
    assert_plan(big, d, ("heavy", true, 2, "workspace", "h2h", 20, "deep"));
    assert_plan(
        Supply { load1: 4, ..big },
        d,
        ("normal", true, 2, "impacted", "loop", 20, "deep"),
    );

    assert_plan(
        Supply {
            disk_free_gb: 5,
            ..base_supply()
        },
        d,
        ("light", false, 2, "ci", "off", 5, "deep"),
    );
    // The floor outranks heavy-class hardware — the first rung wins.
    assert_plan(
        Supply {
            disk_free_gb: 5,
            ..big
        },
        d,
        ("light", false, 2, "ci", "off", 5, "deep"),
    );
    assert_plan(
        Supply {
            busy: true,
            ..base_supply()
        },
        d,
        ("light", false, 1, "ci", "off", 5, "deep"),
    );
    assert_plan(
        Supply {
            mem_free_gb: 2,
            ..base_supply()
        },
        d,
        ("light", false, 1, "ci", "off", 5, "deep"),
    );
    assert_plan(
        Supply {
            on_battery: true,
            ..base_supply()
        },
        d,
        ("light", true, 1, "impacted", "off", 5, "deep"),
    );
    // Saturation sheds the bench arm too — a loop-bench timed on a box whose
    // load already equals its cores is a number the ledger would mislearn
    // from (#1564). The build stays: it runs slower, not wrong.
    assert_plan(
        Supply {
            load1: 8,
            ..base_supply()
        },
        d,
        ("light", true, 1, "impacted", "off", 5, "deep"),
    );
}

#[test]
fn demand_shrinks_the_batch_and_a_p0_rescues_a_light_cycle() {
    assert_plan(
        base_supply(),
        Demand {
            open_defects: 3,
            p0: 0,
        },
        ("normal", true, 2, "impacted", "loop", 3, "deep"),
    );
    // A P0 on a light tier buys a minimal fast cycle, not a skipped one.
    assert_plan(
        Supply {
            on_battery: true,
            ..base_supply()
        },
        Demand {
            open_defects: 3,
            p0: 2,
        },
        ("light", true, 1, "impacted", "off", 2, "fast"),
    );
    // A P0 on a healthy box changes nothing — the rescue is light-only.
    assert_plan(
        base_supply(),
        Demand {
            open_defects: 3,
            p0: 2,
        },
        ("normal", true, 2, "impacted", "loop", 3, "deep"),
    );
    // The light tier caps the batch at 5 whatever the queue holds.
    assert_plan(
        Supply {
            on_battery: true,
            ..base_supply()
        },
        Demand {
            open_defects: 9,
            p0: 0,
        },
        ("light", true, 1, "impacted", "off", 5, "deep"),
    );
}

proptest! {
    /// Demand can shrink a cycle, rescue a light one, or clamp the batch —
    /// but it never upgrades the tier, and the batch stays in range: at least
    /// 1, and at most 5 on the light tier.
    #[test]
    fn demand_never_upgrades_the_tier_and_the_batch_stays_in_range(
        cpu in 1u32..64, load1 in 0u32..80,
        mem_total in 1u64..256, mem_free in 0u64..256, disk in 0u64..500,
        battery in prop::bool::ANY, busy in prop::bool::ANY,
        defects in 0u32..300, p0 in 0u32..40,
    ) {
        let supply = Supply {
            cpu, load1,
            mem_total_gb: mem_total,
            mem_free_gb: mem_free.min(mem_total),
            disk_free_gb: disk,
            on_battery: battery,
            busy,
        };
        let demand = Demand { open_defects: defects, p0: p0.min(defects) };
        let with = plan_cycle(supply, demand, &ceilings(), Floors::default());
        let without = plan_cycle(supply, Demand::default(), &ceilings(), Floors::default());
        prop_assert_eq!(with.tier, without.tier, "demand moved the tier");
        prop_assert!(with.batch >= 1);
        if with.tier == Tier::Light {
            prop_assert!(with.batch <= 5, "light tier batch {} > 5", with.batch);
        }
    }
}

// ---------------------------------------------------------------------------
// metrics — the loop's evidence about itself
// ---------------------------------------------------------------------------

fn ledger_row(cycle_n: u64, fixed: u64, filed: u64, new: u64, gate: &str) -> CycleRecord {
    CycleRecord {
        fixed,
        filed,
        new_findings: new,
        gate: gate.into(),
        dry: new == 0,
        ..cycle(cycle_n, "rubric", new == 0)
    }
}

#[test]
fn three_zero_fix_cycles_raise_stuck_and_a_healthy_loop_raises_nothing() {
    let stuck: Vec<CycleRecord> = (1..=3).map(|i| ledger_row(i, 0, 1, 1, "green")).collect();
    let codes: Vec<&str> = metrics(&stuck).signals.iter().map(|s| s.code).collect();
    assert!(codes.contains(&"STUCK"), "got {codes:?}");

    let healthy: Vec<CycleRecord> = (1..=6).map(|i| ledger_row(i, 4, 1, 2, "green")).collect();
    let m = metrics(&healthy);
    assert!(
        m.signals.is_empty(),
        "a dashboard that always warns teaches the reader to ignore it: {:?}",
        m.signals
    );
    assert_eq!(m.fixed, 24);
}

#[test]
fn noisy_and_fragile_fire_on_their_exact_thresholds() {
    // n=5, discovery 2 (2*2 < 5), filed 11 (> 2*5): dedup is leaking.
    let mut rows: Vec<CycleRecord> = (1..=4).map(|i| ledger_row(i, 1, 2, 0, "green")).collect();
    rows.push(ledger_row(5, 1, 3, 2, "green"));
    let codes: Vec<&str> = metrics(&rows).signals.iter().map(|s| s.code).collect();
    assert!(codes.contains(&"NOISY"), "got {codes:?}");

    let rows: Vec<CycleRecord> = (1..=4)
        .map(|i| ledger_row(i, 1, 0, 1, if i <= 2 { "red" } else { "green" }))
        .collect();
    let codes: Vec<&str> = metrics(&rows).signals.iter().map(|s| s.code).collect();
    assert!(codes.contains(&"FRAGILE"), "got {codes:?}");
}

#[test]
fn starved_reads_the_controller_not_the_ledger() {
    let mut cal = Calibration::seeded(&AimdLimits::default());
    assert!(starved(&cal).is_none());
    cal.batch_ceiling = 4;
    cal.clean_run = 5;
    assert_eq!(starved(&cal).map(|s| s.code), Some("STARVED"));
}

// ---------------------------------------------------------------------------
// queue — ranked P0 > P1 > P2, oldest first inside a rank
// ---------------------------------------------------------------------------

#[test]
fn rank_beats_age_across_ranks_triage_counts_and_features_do_not() {
    let issues: Vec<QueueIssue> = serde_json::from_value(json!([
        {"number": 101, "title": "fresh P1",  "createdAt": "2026-08-01T00:00:00Z", "url": "u",
         "labels": [{"name": "bug"}, {"name": "P1"}]},
        {"number": 102, "title": "aged P1",   "createdAt": "2026-01-01T00:00:00Z", "url": "u",
         "labels": [{"name": "bug"}, {"name": "P1"}]},
        {"number": 103, "title": "the P0",    "createdAt": "2026-08-01T00:00:00Z", "url": "u",
         "labels": [{"name": "bug"}, {"name": "P0"}]},
        {"number": 104, "title": "untriaged", "createdAt": "2025-01-01T00:00:00Z", "url": "u",
         "labels": [{"name": "triage"}]},
        {"number": 105, "title": "a feature", "createdAt": "2025-01-01T00:00:00Z", "url": "u",
         "labels": [{"name": "enhancement"}]}
    ]))
    .expect("fixture parses");

    let ranked: Vec<u64> = rank_defects(issues).iter().map(|i| i.number).collect();
    assert_eq!(ranked, [103, 102, 101, 104]);
}

// ---------------------------------------------------------------------------
// the run fold — the status the file cannot state on its own
// ---------------------------------------------------------------------------

fn run_rec(id: &str, status: &str) -> serde_json::Value {
    json!({"run_id": id, "status": status, "at_unix": 1000, "driver": "daemon"})
}

#[test]
fn a_stale_heartbeat_reports_crashed_not_running() {
    let live = json!({"run_id": "r-1", "phase": "audit", "heartbeat_unix": 0});
    let rows = fold_runs(&[run_rec("r-1", "running")], &[], Some(&live), 10_000, 900);
    assert_eq!(rows[0].status, "crashed");
}

#[test]
fn a_fresh_heartbeat_stays_running_and_carries_the_phase() {
    let live = json!({"run_id": "r-1", "phase": "audit", "heartbeat_unix": 9_990});
    let rows = fold_runs(&[run_rec("r-1", "running")], &[], Some(&live), 10_000, 900);
    assert_eq!(rows[0].status, "running");
    assert_eq!(rows[0].phase, "audit (10s ago)");
}

#[test]
fn a_run_the_live_pointer_moved_on_from_reports_crashed() {
    let live = json!({"run_id": "r-new", "phase": "cycle", "heartbeat_unix": 9_990});
    let rows = fold_runs(
        &[run_rec("r-old", "running"), run_rec("r-new", "running")],
        &[],
        Some(&live),
        10_000,
        900,
    );
    let status = |id: &str| {
        rows.iter()
            .find(|r| r.run_id == id)
            .map(|r| r.status.clone())
            .unwrap_or_default()
    };
    assert_eq!(status("r-old"), "crashed");
    assert_eq!(status("r-new"), "running");
}

#[test]
fn last_write_wins_and_cycles_aggregate_into_their_run() {
    let mut c1 = cycle(1, "rubric", false);
    c1.run_id = "r-1".into();
    c1.fixed = 4;
    let mut c2 = cycle(2, "rubric", false);
    c2.run_id = "r-1".into();
    c2.fixed = 2;
    let rows = fold_runs(
        &[
            run_rec("r-1", "running"),
            run_rec("r-1", "completed"),
            run_rec("r-2", "cancelled"),
        ],
        &[c1, c2],
        None,
        10_000,
        900,
    );
    let r1 = rows.iter().find(|r| r.run_id == "r-1").expect("r-1 folded");
    assert_eq!(r1.status, "completed", "last write wins");
    assert_eq!((r1.cycles, r1.fixed), (2, 6));
    assert_eq!(
        rows.iter()
            .find(|r| r.run_id == "r-2")
            .map(|r| r.status.as_str()),
        Some("cancelled")
    );
}

// ---------------------------------------------------------------------------
// serde — the record shapes are a cross-process contract
// ---------------------------------------------------------------------------

/// The ledger is written here, read by the observatory, and appended to by
/// future writers; a round-trip that drops unknown keys would destroy what it
/// did not understand (invariant 4's discipline applied to a file format).
#[test]
fn cycle_records_round_trip_and_preserve_foreign_keys() {
    let raw = json!({
        "cycle": 7, "run_id": "r-1", "ended_at": "2026-08-05T00:00:00Z",
        "ended_at_unix": 1, "fixed": 2, "filed": 1, "new_findings": 0,
        "bench": "loop", "gate": "green", "prs": ["#9"], "tier": "normal",
        "aperture": "rubric", "lens_tool": "/ultraudit", "outcome": "ok",
        "minutes": 12, "dry": true,
        "a_future_key": {"nested": true}
    });
    let rec: CycleRecord = serde_json::from_value(raw.clone()).expect("parses");
    assert_eq!(rec.lens_tool.as_deref(), Some("/ultraudit"));
    let back = serde_json::to_value(&rec).expect("serializes");
    assert_eq!(back, raw, "byte-stable round-trip, foreign keys included");
}
