#!/usr/bin/env python3
"""Regenerate every Stella brand asset -- and every colour token -- from one source.

The identity is a wordmark, one mark, and one palette:

  wordmark  lowercase "stella", Space Grotesk Medium (wght 500) tracked -0.02em,
            converted to outlines so nothing at build or render time needs a font
  mark      a six-arm concave asterisk. It reads as `*` -- glob, wildcard, the
            first character of a doc comment -- and as a stellar burst. Used only
            where a square or very small footprint rules the wordmark out.
  palette   gold on deep navy: a star against night sky. Defined once in
            tokens.json and generated into every consumer.

The repo used to carry three rival palettes -- the docs site's neutral paper-&-
ink, the TUI's aurora-on-navy, and the observatory's cyan. They are collapsed
into tokens.json, and this script is what keeps them collapsed: it writes the
TUI's palette.rs, the docs site's tokens.css, and the observatory's :root block
from those exact values. Nothing downstream is hand-synced.

The wordmark stays ink/paper; the mark carries the gold. That asymmetry is
deliberate -- gold is 1.35:1 on white, so it can never be text on a light
ground. See tokens.json `rules` and README.md's Colour section.

Every run verifies tokens.json's `contracts` (pairs that must meet WCAG AA) and
`forbidden` (pairs that must stay illegible, so the asymmetry cannot be
"fixed" by accident). A token edit that breaks either fails the build with the
measured ratio instead of shipping.

Usage:  make brand          (or)  python3 docs/brand/build.py

Requires: fonttools, uharfbuzz (pip) and rsvg-convert (brew install librsvg).
The typeface is fetched once and cached under docs/brand/.cache/.
"""

from __future__ import annotations

import hashlib
import importlib.util
import json
import math
import re
import shutil
import subprocess
import sys
import urllib.request
from pathlib import Path

# ---------------------------------------------------------------- configuration

FONT_URL = "https://github.com/google/fonts/raw/main/ofl/spacegrotesk/SpaceGrotesk%5Bwght%5D.ttf"
FONT_SHA256 = "acad6de1fc93436f5c0f1f4137751ef04f1aea3063e7036535970ffcfbd79f72"
FONT_WEIGHT = 500  # Medium
TRACKING_EM = -0.02  # tightened from the default fit; see docs/brand/README.md

WORD = "stella"

ROOT = Path(__file__).resolve().parents[2]
BRAND = ROOT / "docs" / "brand"
CACHE = BRAND / ".cache"
SITE_BRAND = ROOT / "stella-docs" / "public" / "brand"
SITE_ICONS = ROOT / "stella-docs" / "public" / "icons"
SITE_APP = ROOT / "stella-docs" / "src" / "app"
OBSERVATORY = ROOT / "stella-observatory" / "src" / "assets"
TUI = ROOT / "stella-tui" / "src"

GENERATED = "Generated by docs/brand/build.py (edit that, not this file)."
TOKENS_NOTE = "Generated from docs/brand/tokens.json by docs/brand/build.py (edit those, not this file)."


# ----------------------------------------------------------------------- tokens

TOKENS = json.loads((BRAND / "tokens.json").read_text())
# name -> "#RRGGBB", flattened across groups. Names are unique across the whole
# palette by construction; the check below is what guarantees it stays that way.
COLOR: dict[str, str] = {}
for _group in TOKENS["groups"]:
    for _token in _group["tokens"]:
        if _token["name"] in COLOR:
            sys.exit(f"duplicate token name in tokens.json: {_token['name']}")
        COLOR[_token["name"]] = _token["value"]

# The three cuts the wordmark and mark ship in. The wordmark stays ink/paper;
# only the mark takes the gold (tokens.json rule 4).
INK = COLOR["ink"]
PAPER = COLOR["paper"]
GOLD = COLOR["gold"]
NAVY = COLOR["night"]


def _rgb(value: str) -> tuple[int, int, int]:
    h = value.lstrip("#")
    return int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16)


def _luminance(value: str) -> float:
    """WCAG 2.1 relative luminance."""

    def channel(raw: int) -> float:
        c = raw / 255.0
        return c / 12.92 if c <= 0.04045 else ((c + 0.055) / 1.055) ** 2.4

    r, g, b = (channel(c) for c in _rgb(value))
    return 0.2126 * r + 0.7152 * g + 0.0722 * b


def contrast(fg: str, bg: str) -> float:
    """WCAG 2.1 contrast ratio between two hex colours, 1.0 -- 21.0."""
    a, b = _luminance(fg), _luminance(bg)
    hi, lo = max(a, b), min(a, b)
    return (hi + 0.05) / (lo + 0.05)


def verify_contrast() -> None:
    """Enforce tokens.json's `contracts` and `forbidden`.

    `contracts` are pairs that must clear a WCAG floor. `forbidden` are pairs
    that must *stay* below one -- the gold-on-paper asymmetry is load-bearing,
    so a well-meaning edit that made gold legible on white would silently
    dissolve rule 1. Both directions fail loudly, with the measured ratio.
    """
    failures: list[str] = []

    for rule in TOKENS["contracts"]:
        fg, bg, floor = rule["fg"], rule["bg"], rule["min"]
        ratio = contrast(COLOR[fg], COLOR[bg])
        if ratio < floor:
            failures.append(
                f"  {fg} on {bg}: {ratio:.2f}:1 -- needs {floor}:1 ({rule['note']})"
            )

    for rule in TOKENS["forbidden"]:
        fg, bg, ceiling = rule["fg"], rule["bg"], rule["max"]
        ratio = contrast(COLOR[fg], COLOR[bg])
        if ratio >= ceiling:
            failures.append(
                f"  {fg} on {bg}: {ratio:.2f}:1 -- must stay under {ceiling}:1. {rule['why']}"
            )

    if failures:
        sys.exit(
            "tokens.json fails its own contrast contract:\n"
            + "\n".join(failures)
            + "\n\nFix the token values, or amend the contract in tokens.json if "
            "the design genuinely changed."
        )

    print(
        f"contrast  {len(TOKENS['contracts'])} contracts, "
        f"{len(TOKENS['forbidden'])} forbidden pairs -- all hold"
    )


def replace_region(text: str, marker: str, body: str) -> str:
    """Swap the lines between `BEGIN <marker>` / `END <marker>` for `body`.

    Used for the files this script only partly owns -- the observatory's single
    HTML page and the brand README -- so a generated block can live inside a
    hand-written file without the generator claiming the whole thing.
    """
    pattern = re.compile(
        rf"([ \t]*(?://|/\*|<!--|#)[^\n]*BEGIN[^\n]*{re.escape(marker)}[^\n]*\n)"
        rf".*?"
        rf"([ \t]*(?://|/\*|<!--|#)[^\n]*END[^\n]*{re.escape(marker)}[^\n]*)",
        re.DOTALL,
    )
    if not pattern.search(text):
        sys.exit(
            f"could not find the generated region markers for {marker!r}.\n"
            f"  Expected a 'BEGIN {marker}' ... 'END {marker}' comment pair."
        )
    return pattern.sub(lambda m: f"{m.group(1)}{body}{m.group(2)}", text, count=1)


# ------------------------------------------------------------------------ fonts


def font_path() -> Path:
    CACHE.mkdir(parents=True, exist_ok=True)
    dest = CACHE / "SpaceGrotesk[wght].ttf"
    if dest.exists() and hashlib.sha256(dest.read_bytes()).hexdigest() == FONT_SHA256:
        return dest
    print(f"fetching {FONT_URL}")
    with urllib.request.urlopen(FONT_URL) as response:  # noqa: S310 - pinned URL
        blob = response.read()
    digest = hashlib.sha256(blob).hexdigest()
    if digest != FONT_SHA256:
        sys.exit(f"font hash mismatch: expected {FONT_SHA256}, got {digest}")
    dest.write_bytes(blob)
    return dest


def outline_word(word: str) -> tuple[str, tuple[float, float, float, float]]:
    """Shape `word` and return (path data, ink bounding box).

    Coordinates are y-down with the baseline at y=0, so the emitted path drops
    straight into an SVG with no wrapping transform.
    """
    import uharfbuzz as hb
    from fontTools.pens.boundsPen import BoundsPen
    from fontTools.pens.svgPathPen import SVGPathPen
    from fontTools.pens.transformPen import TransformPen
    from fontTools.misc.transform import Transform
    from fontTools.ttLib import TTFont
    from fontTools.varLib import instancer

    source = font_path()

    # Pin the variable font to Medium so shaping and outlines agree.
    ttfont = instancer.instantiateVariableFont(
        TTFont(source), {"wght": FONT_WEIGHT}, inplace=False
    )
    pinned = CACHE / f"SpaceGrotesk-{FONT_WEIGHT}.ttf"
    ttfont.save(pinned)

    upem = ttfont["head"].unitsPerEm
    tracking = TRACKING_EM * upem

    # HarfBuzz gives us real shaping -- kerning included -- rather than naive
    # advance-width stacking.
    blob = hb.Blob.from_file_path(str(pinned))
    hbfont = hb.Font(hb.Face(blob))
    buf = hb.Buffer()
    buf.add_str(word)
    buf.guess_segment_properties()
    hb.shape(hbfont, buf)

    glyph_set = ttfont.getGlyphSet()
    glyph_order = ttfont.getGlyphOrder()

    segments: list[str] = []
    bounds = BoundsPen(glyph_set)
    pen_x = 0.0

    for index, (info, pos) in enumerate(zip(buf.glyph_infos, buf.glyph_positions)):
        name = glyph_order[info.codepoint]
        # Flip y (font units are y-up, SVG is y-down) and place at the pen.
        transform = Transform(1, 0, 0, -1, pen_x + pos.x_offset, -pos.y_offset)

        svg_pen = SVGPathPen(glyph_set, ntos=lambda v: f"{v:.1f}")
        glyph_set[name].draw(TransformPen(svg_pen, transform))
        drawn = svg_pen.getCommands()
        if drawn:
            segments.append(drawn)
        glyph_set[name].draw(TransformPen(bounds, transform))

        pen_x += pos.x_advance
        if index < len(buf.glyph_infos) - 1:
            pen_x += tracking

    if bounds.bounds is None:
        sys.exit("no outlines produced")
    return " ".join(segments), bounds.bounds


# ------------------------------------------------------------------------- mark


def asterisk_path(
    cx: float,
    cy: float,
    radius: float,
    *,
    arms: int = 6,
    concavity: float = 0.52,
    waist: float = 0.31,
    tip: float = 0.055,
) -> str:
    """A six-arm asterisk with concave flanks, as one transform-free path.

    Each arm is a wedge: wide at the hub, waisted by a quadratic pulled inward,
    and capped with a small radius so the tips read as drawn rather than clipped.
    """
    half = radius * waist
    tip_r = radius * tip
    control = half * (1 - concavity)
    waist_y = -radius * 0.55

    def place(x: float, y: float, angle: float) -> tuple[float, float]:
        rad = math.radians(angle)
        sin, cos = math.sin(rad), math.cos(rad)
        return (cx + x * cos - y * sin, cy + x * sin + y * cos)

    def fmt(point: tuple[float, float]) -> str:
        return f"{point[0]:.2f} {point[1]:.2f}"

    parts: list[str] = []
    for index in range(arms):
        angle = index * 360.0 / arms
        start = place(-half, 0, angle)
        left_ctl = place(-control, waist_y, angle)
        left_tip = place(-tip_r, -radius, angle)
        cap_ctl = place(0, -radius - tip_r, angle)
        right_tip = place(tip_r, -radius, angle)
        right_ctl = place(control, waist_y, angle)
        end = place(half, 0, angle)
        parts.append(
            f"M {fmt(start)} Q {fmt(left_ctl)} {fmt(left_tip)} "
            f"Q {fmt(cap_ctl)} {fmt(right_tip)} "
            f"Q {fmt(right_ctl)} {fmt(end)} Z"
        )
    return " ".join(parts)


# ------------------------------------------------------------------------ emit


def svg(body: str, view_box: str, *, width: float, height: float, label: str) -> str:
    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="{view_box}" '
        f'width="{width:.0f}" height="{height:.0f}" fill="none" '
        f'role="img" aria-label="{label}">\n'
        f"  <!-- {GENERATED} -->\n"
        f"{body}\n"
        f"</svg>\n"
    )


def write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text)
    print(f"  {path.relative_to(ROOT)}")


def rasterize(source: Path, dest: Path, size: int) -> None:
    subprocess.run(
        ["rsvg-convert", "-w", str(size), "-h", str(size), str(source), "-o", str(dest)],
        check=True,
    )
    print(f"  {dest.relative_to(ROOT)} ({size}px)")


def emit_palette_rs() -> None:
    """stella-tui/src/palette.rs -- raw colour consts, nothing semantic.

    theme.rs keeps the semantic layer (ACCENT, OK, RULE, the status mapping) and
    consumes these. Splitting them is what lets a recolour be a tokens.json edit
    instead of a hunt through the crate.
    """
    lines = [
        f"//! {TOKENS_NOTE}",
        "//!",
        "//! Raw palette values -- the single normative colour source, shared with",
        "//! the docs site and the observatory. Nothing here is semantic: for role",
        "//! names (accent, ink, rule, status) see [`crate::theme`], which is the",
        "//! only module that should be referencing these directly.",
        "//!",
        f"//! The identity is {TOKENS['identity']}.",
        "",
        "use ratatui::style::Color;",
        "",
    ]
    for group in TOKENS["groups"]:
        lines.append(f"// ── {group['title']} {'─' * max(0, 60 - len(group['title']))}")
        lines.append("//")
        for chunk in _wrap(group["doc"], 74):
            lines.append(f"// {chunk}")
        lines.append("")
        for token in group["tokens"]:
            for chunk in _wrap(token["doc"], 74):
                lines.append(f"/// {chunk}")
            r, g, b = _rgb(token["value"])
            lines.append(
                f"pub const {_rust_name(token['name'])}: Color = "
                f"Color::Rgb(0x{r:02X}, 0x{g:02X}, 0x{b:02X});"
            )
            lines.append("")

    names = [t["name"] for group in TOKENS["groups"] for t in group["tokens"]]
    lines.append("/// Every palette colour, paired with its tokens.json name.")
    lines.append("///")
    lines.append("/// Lets a test walk the whole palette -- see theme.rs's colour-depth")
    lines.append("/// fallback coverage check -- without a hand-maintained second list.")
    lines.append(f"pub const ALL: [(&str, Color); {len(names)}] = [")
    for name in names:
        lines.append(f'    ("{name}", {_rust_name(name)}),')
    lines.append("];")
    write(TUI / "palette.rs", "\n".join(lines) + "\n")


def emit_tokens_css() -> None:
    """stella-docs/src/app/tokens.css -- the raw palette as custom properties.

    Mode-aware semantics (which token is "foreground" in dark vs light) stay in
    global.css. This file is the CSS twin of palette.rs: values only.
    """
    lines = [
        "/**",
        f" * {TOKENS_NOTE}",
        " *",
        " * Raw palette values, imported by global.css. Nothing here is mode-aware:",
        " * global.css maps these onto the light/dark semantic layer, the same way",
        " * stella-tui's theme.rs maps palette.rs.",
        " *",
        f" * The identity is {TOKENS['identity']}.",
        " */",
        "",
        ":root {",
    ]
    for group in TOKENS["groups"]:
        lines.append(f"  /* {group['title']} — {group['doc'].split('.')[0]}. */")
        for token in group["tokens"]:
            lines.append(f"  --stella-{token['name']}: {token['value'].lower()};")
        lines.append("")
    if lines[-1] == "":
        lines.pop()
    lines.append("}")
    write(SITE_APP / "tokens.css", "\n".join(lines) + "\n")


def emit_observatory_tokens() -> None:
    """Rewrite the observatory's :root colour block in place.

    The observatory is a single self-contained HTML page served by `include_str!`
    and guarded by a test that forbids any external reference, so its tokens must
    stay inlined -- no @import of tokens.css. Only the region between the markers
    is generated; the font stacks and everything else in :root are left alone.
    """
    index = OBSERVATORY / "index.html"
    text = index.read_text()

    rows = [
        "  --night:{night}; --ground:{ground}; --surface:{surface};",
        "  --raised:{raised}; --hairline:{hairline};",
        "  --gold:{gold}; --gold-deep:{gold_deep};",
        "  --text:{text_primary}; --text-2:{text_secondary}; --text-3:{text_tertiary};",
        "  --ok:{success}; --warn:{warning}; --bad:{danger};",
    ]
    values = {key.replace("-", "_"): value.upper() for key, value in COLOR.items()}
    body = "\n".join(row.format(**values) for row in rows)
    body = (
        f"{body}\n"
        "  /* Semantic alias. The dashboard is dark-only, so this resolves once.\n"
        "     Only ONE alias, and only for brand/active/progress: the page's quiet\n"
        "     structural labels take --text-3. An `--accent-2` here would just be a\n"
        "     licence to paint everything gold, which is what rule 3 forbids. */\n"
        "  --accent:var(--gold);\n"
    )
    write(index, replace_region(text, "brand palette", body))


def emit_readme_colour() -> None:
    """Rewrite README.md's Colour section from the tokens, ratios measured live.

    The table, the rules, and every ratio quoted are computed here, so the
    documentation cannot drift from the values it documents.
    """
    out: list[str] = [""]
    out.append(f"The identity is **{TOKENS['identity']}**.")
    out.append("")
    out.append(
        "Defined once in [`tokens.json`](tokens.json) and generated into every"
    )
    out.append(
        "consumer by `build.py` — the TUI's `palette.rs`, the docs site's"
    )
    out.append(
        "`tokens.css`, and the observatory's `:root` block. Hand-syncing a hex code"
    )
    out.append("across three crates is what produced the palettes this replaced.")
    out.append("")

    for group in TOKENS["groups"]:
        out.append(f"### {group['title']}")
        out.append("")
        out.append(group["doc"])
        out.append("")
        out.append("| Token | Value | Use |")
        out.append("| --- | --- | --- |")
        for token in group["tokens"]:
            out.append(
                f"| `{token['name']}` | `{token['value']}` | {token['doc']} |"
            )
        out.append("")

    out.append("### The four rules")
    out.append("")
    for index, rule in enumerate(TOKENS["rules"], start=1):
        out.append(f"{index}. {rule}")
        out.append("")

    out.append("### Why gold is asymmetric")
    out.append("")
    gold_paper = contrast(COLOR["gold"], COLOR["paper"])
    ink_gold = contrast(COLOR["ink"], COLOR["gold"])
    goldink_paper = contrast(COLOR["gold-ink"], COLOR["paper"])
    gold_ground = contrast(COLOR["gold"], COLOR["ground"])
    out.append(
        f"Gold is a light colour. On the navy ground it is **{gold_ground:.2f}:1** — "
        f"brilliant, and comfortably past the 4.5 body-text floor. On white it is"
    )
    out.append(
        f"**{gold_paper:.2f}:1**, which is not a near miss: it is roughly a third of"
    )
    out.append(
        "what legibility requires, and no amount of weight or size fixes it."
    )
    out.append("")
    out.append(
        "So gold behaves differently in the two modes, and that is a design"
    )
    out.append("decision rather than an oversight:")
    out.append("")
    out.append(
        f"- On dark, gold is **text** — the accent, the active state, the progress fill."
    )
    out.append(
        f"- On light, gold is only ever a **fill**, with an ink label on top at"
        f" **{ink_gold:.2f}:1**."
    )
    out.append(
        f"- When light mode genuinely needs a warm *text* tone, it uses `gold-ink`"
        f" at **{goldink_paper:.2f}:1** — the only warm text tone permitted on paper."
    )
    out.append("")
    out.append(
        "A palette that behaved identically in both modes would have to give up"
    )
    out.append(
        "either the brilliance of the gold on dark or legibility on light. This"
    )
    out.append("one gives up neither.")
    out.append("")

    out.append("### Measured contrast")
    out.append("")
    out.append(
        "Every pair below is asserted by `build.py` on each run, computed with the"
    )
    out.append(
        "WCAG 2.1 relative-luminance formula. AA is 4.5:1 for body text and 3.0:1"
    )
    out.append("for large text and UI.")
    out.append("")
    out.append("| Foreground | Ground | Ratio | Floor | |")
    out.append("| --- | --- | --- | --- | --- |")
    for rule in TOKENS["contracts"]:
        ratio = contrast(COLOR[rule["fg"]], COLOR[rule["bg"]])
        out.append(
            f"| `{rule['fg']}` | `{rule['bg']}` | {ratio:.2f}:1 | {rule['min']} | "
            f"{rule['note']} |"
        )
    out.append("")
    out.append(
        "And the pairs that must *stay* illegible, so the asymmetry cannot be"
    )
    out.append('"fixed" by accident:')
    out.append("")
    out.append("| Foreground | Ground | Ratio | Ceiling | |")
    out.append("| --- | --- | --- | --- | --- |")
    for rule in TOKENS["forbidden"]:
        ratio = contrast(COLOR[rule["fg"]], COLOR[rule["bg"]])
        out.append(
            f"| `{rule['fg']}` | `{rule['bg']}` | {ratio:.2f}:1 | &lt; {rule['max']} | "
            f"{rule['why']} |"
        )
    out.append("")

    readme = BRAND / "README.md"
    write(readme, replace_region(readme.read_text(), "colour", "\n".join(out) + "\n"))


def _rust_name(name: str) -> str:
    return name.replace("-", "_").upper()


def _wrap(text: str, width: int) -> list[str]:
    words, lines, current = text.split(), [], ""
    for word in words:
        candidate = f"{current} {word}".strip()
        if len(candidate) > width and current:
            lines.append(current)
            current = word
        else:
            current = candidate
    if current:
        lines.append(current)
    return lines or [""]


def main() -> None:
    if not shutil.which("rsvg-convert"):
        sys.exit("rsvg-convert not found — brew install librsvg")
    missing = [
        package
        for module, package in (("fontTools", "fonttools"), ("uharfbuzz", "uharfbuzz"))
        if importlib.util.find_spec(module) is None
    ]
    if missing:
        sys.exit(
            f"missing Python packages: {', '.join(missing)}\n"
            f"  pip install {' '.join(missing)}"
        )

    # Before anything is written: if the palette does not satisfy its own
    # contract there is no point generating assets from it.
    verify_contrast()

    print("colour tokens")
    emit_palette_rs()
    emit_tokens_css()
    emit_observatory_tokens()
    emit_readme_colour()

    print("wordmark")
    path_data, (x0, y0, x1, y1) = outline_word(WORD)
    # Pad the ink box by a hair so antialiased edges are never clipped.
    pad = (x1 - x0) * 0.004
    x0, y0, x1, y1 = x0 - pad, y0 - pad, x1 + pad, y1 + pad
    w, h = x1 - x0, y1 - y0
    view = f"{x0:.1f} {y0:.1f} {w:.1f} {h:.1f}"
    # Nominal display size: 28px tall, the docs-site nav height.
    nominal_h = 28.0
    nominal_w = nominal_h * w / h

    for name, fill in (
        ("wordmark.svg", "currentColor"),
        ("wordmark-ink.svg", INK),
        ("wordmark-paper.svg", PAPER),
    ):
        body = f'  <path d="{path_data}" fill="{fill}"/>'
        write(
            BRAND / name,
            svg(body, view, width=nominal_w, height=nominal_h, label="Stella"),
        )

    print("mark")
    mark_box = 100.0
    mark = asterisk_path(mark_box / 2, mark_box / 2, mark_box * 0.46)
    mark_view = f"0 0 {mark_box:.0f} {mark_box:.0f}"
    # The mark is the one place the brand hue lives -- hence the gold cut, which
    # the wordmark deliberately has no counterpart for (tokens.json rule 4).
    for name, fill in (
        ("mark.svg", "currentColor"),
        ("mark-ink.svg", INK),
        ("mark-paper.svg", PAPER),
        ("mark-gold.svg", GOLD),
    ):
        write(
            BRAND / name,
            svg(
                f'  <path d="{mark}" fill="{fill}"/>',
                mark_view,
                width=mark_box,
                height=mark_box,
                label="Stella",
            ),
        )

    print("lockup")
    # Mark set to cap height, one wordmark-x-height of air between the two.
    for name, fill in (("lockup-ink.svg", INK), ("lockup-paper.svg", PAPER)):
        mark_size = h * 0.94
        gap = h * 0.42
        total_w = mark_size + gap + w
        lock_view = f"0 0 {total_w:.1f} {h:.1f}"
        inner = asterisk_path(mark_size / 2, h / 2, mark_size * 0.46)
        body = (
            f'  <path d="{inner}" fill="{fill}"/>\n'
            f'  <g transform="translate({mark_size + gap - x0:.1f} {-y0:.1f})">'
            f'<path d="{path_data}" fill="{fill}"/></g>'
        )
        write(
            BRAND / name,
            svg(
                body,
                lock_view,
                width=nominal_h * total_w / h,
                height=nominal_h,
                label="Stella",
            ),
        )

    print("icons")
    # Tile + mark. A tile keeps the favicon legible against any tab colour, which
    # a bare glyph on transparency does not. Gold on navy, not paper on ink: at
    # 16px the icon is the only brand surface a user sees, so it carries the hue.
    def tile(size: float, mark_ratio: float, radius_ratio: float) -> str:
        radius = size * radius_ratio
        inner = asterisk_path(size / 2, size / 2, size * mark_ratio / 2)
        return (
            f'  <rect width="{size:.0f}" height="{size:.0f}" rx="{radius:.1f}" fill="{NAVY}"/>\n'
            f'  <path d="{inner}" fill="{GOLD}"/>'
        )

    favicon = svg(
        tile(200, 0.70, 0.22), "0 0 200 200", width=200, height=200, label="Stella"
    )
    appicon = svg(
        tile(512, 0.58, 0.2237), "0 0 512 512", width=512, height=512, label="Stella"
    )
    # Maskable art gets cropped to the inner ~80%; keep the mark well inside.
    maskable = svg(
        f'  <rect width="512" height="512" fill="{NAVY}"/>\n'
        f'  <path d="{asterisk_path(256, 256, 512 * 0.42 / 2)}" fill="{GOLD}"/>',
        "0 0 512 512",
        width=512,
        height=512,
        label="Stella",
    )

    write(BRAND / "favicon.svg", favicon)
    write(BRAND / "appicon.svg", appicon)
    write(CACHE / "maskable.svg", maskable)

    print("site copies")
    # The site consumes docs/brand/ verbatim. Copying here is what keeps the two
    # trees from drifting the way the previous generation did.
    for name in (
        "wordmark.svg",
        "wordmark-ink.svg",
        "wordmark-paper.svg",
        "mark.svg",
        "mark-ink.svg",
        "mark-paper.svg",
        "mark-gold.svg",
        "lockup-ink.svg",
        "lockup-paper.svg",
    ):
        shutil.copyfile(BRAND / name, SITE_BRAND / name)
        print(f"  {(SITE_BRAND / name).relative_to(ROOT)}")

    write(SITE_ICONS / "favicon.svg", favicon)
    write(SITE_ICONS / "appicon.svg", appicon)
    write(SITE_APP / "icon.svg", favicon)  # Next.js file convention
    # The observatory serves this as an <img> and as its favicon, so it needs a
    # literal colour -- currentColor would resolve to black on the navy ground.
    # It takes the gold cut: the mark carries the hue, the wordmark stays paper.
    shutil.copyfile(BRAND / "mark-gold.svg", OBSERVATORY / "mark.svg")
    print(f"  {(OBSERVATORY / 'mark.svg').relative_to(ROOT)}")
    shutil.copyfile(BRAND / "wordmark-paper.svg", OBSERVATORY / "wordmark.svg")
    print(f"  {(OBSERVATORY / 'wordmark.svg').relative_to(ROOT)}")

    print("site brand module")
    # Emitting the geometry as TS keeps the landing page's inline mark and the
    # generated OG card on exactly the same paths as the SVG assets.
    write(
        ROOT / "stella-docs" / "src" / "components" / "brand.tsx",
        f"""// {GENERATED}
//
// Inline brand geometry. Both components paint with `currentColor`, so they
// invert with the theme without needing a per-mode asset.

export const WORDMARK_VIEW_BOX = "{view}";
export const WORDMARK_PATH =
  "{path_data}";

export const MARK_VIEW_BOX = "{mark_view}";
export const MARK_PATH =
  "{mark}";

export function Wordmark({{ className }}: {{ className?: string }}) {{
  return (
    <svg
      viewBox={{WORDMARK_VIEW_BOX}}
      fill="currentColor"
      className={{className}}
      role="img"
      aria-label="Stella"
    >
      <path d={{WORDMARK_PATH}} />
    </svg>
  );
}}

export function Mark({{ className }}: {{ className?: string }}) {{
  return (
    <svg viewBox={{MARK_VIEW_BOX}} fill="currentColor" className={{className}} aria-hidden>
      <path d={{MARK_PATH}} />
    </svg>
  );
}}
""",
    )

    print("rasters")
    for size in (16, 32, 48):
        rasterize(BRAND / "favicon.svg", SITE_ICONS / f"favicon-{size}.png", size)
    rasterize(BRAND / "appicon.svg", SITE_ICONS / "apple-touch-icon-180.png", 180)
    rasterize(BRAND / "appicon.svg", SITE_APP / "apple-icon.png", 180)
    for size in (192, 512):
        rasterize(BRAND / "appicon.svg", SITE_ICONS / f"icon-{size}.png", size)
        rasterize(CACHE / "maskable.svg", SITE_ICONS / f"maskable-{size}.png", size)

    print(f"\nwordmark ink box {w:.0f}x{h:.0f} units, aspect {w / h:.3f}")


if __name__ == "__main__":
    main()
