#!/usr/bin/env python3
"""Regenerate every Stella brand asset from a single source of truth.

The identity is a wordmark and one mark:

  wordmark  lowercase "stella", Space Grotesk Medium (wght 500) tracked -0.02em,
            converted to outlines so nothing at build or render time needs a font
  mark      a six-arm concave asterisk. It reads as `*` -- glob, wildcard, the
            first character of a doc comment -- and as a stellar burst. Used only
            where a square or very small footprint rules the wordmark out.

Everything is monochrome. The repo carries three rival palettes (docs-site
neutral, TUI aurora-on-navy, observatory cyan); a monochrome mark sits on all
three without arbitrating between them.

Usage:  make brand          (or)  python3 docs/brand/build.py

Requires: fonttools, uharfbuzz (pip) and rsvg-convert (brew install librsvg).
The typeface is fetched once and cached under docs/brand/.cache/.
"""

from __future__ import annotations

import hashlib
import importlib.util
import math
import shutil
import subprocess
import sys
import urllib.request
from pathlib import Path

# ---------------------------------------------------------------- configuration

FONT_URL = "https://github.com/google/fonts/raw/main/ofl/spacegrotesk/SpaceGrotesk%5Bwght%5D.ttf"
FONT_SHA256 = "acad6de1fc93436f5c0f1f4137751ef04f1aea3063e7036535970ffcfbd79f72"
FONT_WEIGHT = 500  # Medium
TRACKING_EM = -0.02  # tightened from the default fit; see docs/brand/README.md

WORD = "stella"

INK = "#0A0A0A"  # letters on light ground -- matches --stella-ink in global.css
PAPER = "#FAFAFA"  # letters on dark ground

ROOT = Path(__file__).resolve().parents[2]
BRAND = ROOT / "docs" / "brand"
CACHE = BRAND / ".cache"
SITE_BRAND = ROOT / "stella-docs" / "public" / "brand"
SITE_ICONS = ROOT / "stella-docs" / "public" / "icons"
SITE_APP = ROOT / "stella-docs" / "src" / "app"
OBSERVATORY = ROOT / "stella-observatory" / "src" / "assets"

GENERATED = "Generated by docs/brand/build.py (edit that, not this file)."


# ------------------------------------------------------------------------ fonts


def font_path() -> Path:
    CACHE.mkdir(parents=True, exist_ok=True)
    dest = CACHE / "SpaceGrotesk[wght].ttf"
    if dest.exists() and hashlib.sha256(dest.read_bytes()).hexdigest() == FONT_SHA256:
        return dest
    print(f"fetching {FONT_URL}")
    with urllib.request.urlopen(FONT_URL) as response:  # noqa: S310 - pinned URL
        blob = response.read()
    digest = hashlib.sha256(blob).hexdigest()
    if digest != FONT_SHA256:
        sys.exit(f"font hash mismatch: expected {FONT_SHA256}, got {digest}")
    dest.write_bytes(blob)
    return dest


def outline_word(word: str) -> tuple[str, tuple[float, float, float, float]]:
    """Shape `word` and return (path data, ink bounding box).

    Coordinates are y-down with the baseline at y=0, so the emitted path drops
    straight into an SVG with no wrapping transform.
    """
    import uharfbuzz as hb
    from fontTools.pens.boundsPen import BoundsPen
    from fontTools.pens.svgPathPen import SVGPathPen
    from fontTools.pens.transformPen import TransformPen
    from fontTools.misc.transform import Transform
    from fontTools.ttLib import TTFont
    from fontTools.varLib import instancer

    source = font_path()

    # Pin the variable font to Medium so shaping and outlines agree.
    ttfont = instancer.instantiateVariableFont(
        TTFont(source), {"wght": FONT_WEIGHT}, inplace=False
    )
    pinned = CACHE / f"SpaceGrotesk-{FONT_WEIGHT}.ttf"
    ttfont.save(pinned)

    upem = ttfont["head"].unitsPerEm
    tracking = TRACKING_EM * upem

    # HarfBuzz gives us real shaping -- kerning included -- rather than naive
    # advance-width stacking.
    blob = hb.Blob.from_file_path(str(pinned))
    hbfont = hb.Font(hb.Face(blob))
    buf = hb.Buffer()
    buf.add_str(word)
    buf.guess_segment_properties()
    hb.shape(hbfont, buf)

    glyph_set = ttfont.getGlyphSet()
    glyph_order = ttfont.getGlyphOrder()

    segments: list[str] = []
    bounds = BoundsPen(glyph_set)
    pen_x = 0.0

    for index, (info, pos) in enumerate(zip(buf.glyph_infos, buf.glyph_positions)):
        name = glyph_order[info.codepoint]
        # Flip y (font units are y-up, SVG is y-down) and place at the pen.
        transform = Transform(1, 0, 0, -1, pen_x + pos.x_offset, -pos.y_offset)

        svg_pen = SVGPathPen(glyph_set, ntos=lambda v: f"{v:.1f}")
        glyph_set[name].draw(TransformPen(svg_pen, transform))
        drawn = svg_pen.getCommands()
        if drawn:
            segments.append(drawn)
        glyph_set[name].draw(TransformPen(bounds, transform))

        pen_x += pos.x_advance
        if index < len(buf.glyph_infos) - 1:
            pen_x += tracking

    if bounds.bounds is None:
        sys.exit("no outlines produced")
    return " ".join(segments), bounds.bounds


# ------------------------------------------------------------------------- mark


def asterisk_path(
    cx: float,
    cy: float,
    radius: float,
    *,
    arms: int = 6,
    concavity: float = 0.52,
    waist: float = 0.31,
    tip: float = 0.055,
) -> str:
    """A six-arm asterisk with concave flanks, as one transform-free path.

    Each arm is a wedge: wide at the hub, waisted by a quadratic pulled inward,
    and capped with a small radius so the tips read as drawn rather than clipped.
    """
    half = radius * waist
    tip_r = radius * tip
    control = half * (1 - concavity)
    waist_y = -radius * 0.55

    def place(x: float, y: float, angle: float) -> tuple[float, float]:
        rad = math.radians(angle)
        sin, cos = math.sin(rad), math.cos(rad)
        return (cx + x * cos - y * sin, cy + x * sin + y * cos)

    def fmt(point: tuple[float, float]) -> str:
        return f"{point[0]:.2f} {point[1]:.2f}"

    parts: list[str] = []
    for index in range(arms):
        angle = index * 360.0 / arms
        start = place(-half, 0, angle)
        left_ctl = place(-control, waist_y, angle)
        left_tip = place(-tip_r, -radius, angle)
        cap_ctl = place(0, -radius - tip_r, angle)
        right_tip = place(tip_r, -radius, angle)
        right_ctl = place(control, waist_y, angle)
        end = place(half, 0, angle)
        parts.append(
            f"M {fmt(start)} Q {fmt(left_ctl)} {fmt(left_tip)} "
            f"Q {fmt(cap_ctl)} {fmt(right_tip)} "
            f"Q {fmt(right_ctl)} {fmt(end)} Z"
        )
    return " ".join(parts)


# ------------------------------------------------------------------------ emit


def svg(body: str, view_box: str, *, width: float, height: float, label: str) -> str:
    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="{view_box}" '
        f'width="{width:.0f}" height="{height:.0f}" fill="none" '
        f'role="img" aria-label="{label}">\n'
        f"  <!-- {GENERATED} -->\n"
        f"{body}\n"
        f"</svg>\n"
    )


def write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text)
    print(f"  {path.relative_to(ROOT)}")


def rasterize(source: Path, dest: Path, size: int) -> None:
    subprocess.run(
        ["rsvg-convert", "-w", str(size), "-h", str(size), str(source), "-o", str(dest)],
        check=True,
    )
    print(f"  {dest.relative_to(ROOT)} ({size}px)")


def main() -> None:
    if not shutil.which("rsvg-convert"):
        sys.exit("rsvg-convert not found — brew install librsvg")
    missing = [
        package
        for module, package in (("fontTools", "fonttools"), ("uharfbuzz", "uharfbuzz"))
        if importlib.util.find_spec(module) is None
    ]
    if missing:
        sys.exit(
            f"missing Python packages: {', '.join(missing)}\n"
            f"  pip install {' '.join(missing)}"
        )

    print("wordmark")
    path_data, (x0, y0, x1, y1) = outline_word(WORD)
    # Pad the ink box by a hair so antialiased edges are never clipped.
    pad = (x1 - x0) * 0.004
    x0, y0, x1, y1 = x0 - pad, y0 - pad, x1 + pad, y1 + pad
    w, h = x1 - x0, y1 - y0
    view = f"{x0:.1f} {y0:.1f} {w:.1f} {h:.1f}"
    # Nominal display size: 28px tall, the docs-site nav height.
    nominal_h = 28.0
    nominal_w = nominal_h * w / h

    for name, fill in (
        ("wordmark.svg", "currentColor"),
        ("wordmark-ink.svg", INK),
        ("wordmark-paper.svg", PAPER),
    ):
        body = f'  <path d="{path_data}" fill="{fill}"/>'
        write(
            BRAND / name,
            svg(body, view, width=nominal_w, height=nominal_h, label="Stella"),
        )

    print("mark")
    mark_box = 100.0
    mark = asterisk_path(mark_box / 2, mark_box / 2, mark_box * 0.46)
    mark_view = f"0 0 {mark_box:.0f} {mark_box:.0f}"
    for name, fill in (
        ("mark.svg", "currentColor"),
        ("mark-ink.svg", INK),
        ("mark-paper.svg", PAPER),
    ):
        write(
            BRAND / name,
            svg(
                f'  <path d="{mark}" fill="{fill}"/>',
                mark_view,
                width=mark_box,
                height=mark_box,
                label="Stella",
            ),
        )

    print("lockup")
    # Mark set to cap height, one wordmark-x-height of air between the two.
    for name, fill in (("lockup-ink.svg", INK), ("lockup-paper.svg", PAPER)):
        mark_size = h * 0.94
        gap = h * 0.42
        total_w = mark_size + gap + w
        lock_view = f"0 0 {total_w:.1f} {h:.1f}"
        inner = asterisk_path(mark_size / 2, h / 2, mark_size * 0.46)
        body = (
            f'  <path d="{inner}" fill="{fill}"/>\n'
            f'  <g transform="translate({mark_size + gap - x0:.1f} {-y0:.1f})">'
            f'<path d="{path_data}" fill="{fill}"/></g>'
        )
        write(
            BRAND / name,
            svg(
                body,
                lock_view,
                width=nominal_h * total_w / h,
                height=nominal_h,
                label="Stella",
            ),
        )

    print("icons")
    # Tile + mark. A tile keeps the favicon legible against any tab colour, which
    # a bare glyph on transparency does not.
    def tile(size: float, mark_ratio: float, radius_ratio: float) -> str:
        radius = size * radius_ratio
        inner = asterisk_path(size / 2, size / 2, size * mark_ratio / 2)
        return (
            f'  <rect width="{size:.0f}" height="{size:.0f}" rx="{radius:.1f}" fill="{INK}"/>\n'
            f'  <path d="{inner}" fill="{PAPER}"/>'
        )

    favicon = svg(
        tile(200, 0.70, 0.22), "0 0 200 200", width=200, height=200, label="Stella"
    )
    appicon = svg(
        tile(512, 0.58, 0.2237), "0 0 512 512", width=512, height=512, label="Stella"
    )
    # Maskable art gets cropped to the inner ~80%; keep the mark well inside.
    maskable = svg(
        f'  <rect width="512" height="512" fill="{INK}"/>\n'
        f'  <path d="{asterisk_path(256, 256, 512 * 0.42 / 2)}" fill="{PAPER}"/>',
        "0 0 512 512",
        width=512,
        height=512,
        label="Stella",
    )

    write(BRAND / "favicon.svg", favicon)
    write(BRAND / "appicon.svg", appicon)
    write(CACHE / "maskable.svg", maskable)

    print("site copies")
    # The site consumes docs/brand/ verbatim. Copying here is what keeps the two
    # trees from drifting the way the previous generation did.
    for name in (
        "wordmark.svg",
        "wordmark-ink.svg",
        "wordmark-paper.svg",
        "mark.svg",
        "mark-ink.svg",
        "mark-paper.svg",
        "lockup-ink.svg",
        "lockup-paper.svg",
    ):
        shutil.copyfile(BRAND / name, SITE_BRAND / name)
        print(f"  {(SITE_BRAND / name).relative_to(ROOT)}")

    write(SITE_ICONS / "favicon.svg", favicon)
    write(SITE_ICONS / "appicon.svg", appicon)
    write(SITE_APP / "icon.svg", favicon)  # Next.js file convention
    # The observatory serves this as an <img> and as its favicon, so it needs a
    # literal colour -- currentColor would resolve to black on the navy ground.
    shutil.copyfile(BRAND / "mark-paper.svg", OBSERVATORY / "mark.svg")
    print(f"  {(OBSERVATORY / 'mark.svg').relative_to(ROOT)}")
    shutil.copyfile(BRAND / "wordmark-paper.svg", OBSERVATORY / "wordmark.svg")
    print(f"  {(OBSERVATORY / 'wordmark.svg').relative_to(ROOT)}")

    print("site brand module")
    # Emitting the geometry as TS keeps the landing page's inline mark and the
    # generated OG card on exactly the same paths as the SVG assets.
    write(
        ROOT / "stella-docs" / "src" / "components" / "brand.tsx",
        f"""// {GENERATED}
//
// Inline brand geometry. Both components paint with `currentColor`, so they
// invert with the theme without needing a per-mode asset.

export const WORDMARK_VIEW_BOX = "{view}";
export const WORDMARK_PATH =
  "{path_data}";

export const MARK_VIEW_BOX = "{mark_view}";
export const MARK_PATH =
  "{mark}";

export function Wordmark({{ className }}: {{ className?: string }}) {{
  return (
    <svg
      viewBox={{WORDMARK_VIEW_BOX}}
      fill="currentColor"
      className={{className}}
      role="img"
      aria-label="Stella"
    >
      <path d={{WORDMARK_PATH}} />
    </svg>
  );
}}

export function Mark({{ className }}: {{ className?: string }}) {{
  return (
    <svg viewBox={{MARK_VIEW_BOX}} fill="currentColor" className={{className}} aria-hidden>
      <path d={{MARK_PATH}} />
    </svg>
  );
}}
""",
    )

    print("rasters")
    for size in (16, 32, 48):
        rasterize(BRAND / "favicon.svg", SITE_ICONS / f"favicon-{size}.png", size)
    rasterize(BRAND / "appicon.svg", SITE_ICONS / "apple-touch-icon-180.png", 180)
    rasterize(BRAND / "appicon.svg", SITE_APP / "apple-icon.png", 180)
    for size in (192, 512):
        rasterize(BRAND / "appicon.svg", SITE_ICONS / f"icon-{size}.png", size)
        rasterize(CACHE / "maskable.svg", SITE_ICONS / f"maskable-{size}.png", size)

    print(f"\nwordmark ink box {w:.0f}x{h:.0f} units, aspect {w / h:.3f}")


if __name__ == "__main__":
    main()
