//! The palette and its hue clamp -- SPEC-stella-tui-v2.md sections 3.1 and 3.2.
//!
//! GENERATED by `scripts/gen-tokens.py` from `design/tokens/stella-tokens.json`.
//! Do not edit this file. Edit the JSON and run `make tokens-update`.
//!
//! Every value is [`Color::Rgb`]; there are no indexed or named colours here,
//! because the clamp can only speak about channels. [`ALL`] pairs each token
//! with the [`Clamp`] its value is held to, and the tests at the bottom walk
//! that table -- so a new hex cannot enter the palette without declaring what
//! kind of colour it is, and the warm-drift predicates reject the declaration
//! that would kill the scheme.

use ratatui::style::Color;

// ── Clamp bounds ─────────────────────────────────────────────────

/// The green ratio a gold must clear, as a percentage of red.
///
/// The green ratio is the load-bearing half: below it the hue is orange, and orange on a near-black ground reads brown on cheap panels.
pub const GOLD_GREEN_PCT: u32 = 78;

/// The blue ceiling a resting gold must stay under, as a percentage of red.
pub const GOLD_BLUE_PCT: u32 = 35;

/// The blue ceiling for the *lift* -- the one gold that sits above
/// [`GOLD_BLUE_PCT`], used only for single-cell live indicators.
///
/// A recorded exception, not a relaxation. SPEC 3.2 states one clamp for
/// 'every color in the gold role', and SPEC 3.1's own gold_bright #F7D96B
/// does not satisfy it: b/r measures 107/247 = 0.433 against a stated
/// ceiling of 0.35. The spec contradicts itself. The canonical-token rule
/// forbids inventing a colour, so the value stands exactly as specified and
/// the ceiling that admits it is recorded here instead -- at 44, the
/// tightest whole percent that does (0.44 * 247 = 108.7, over the token's
/// 107; 0.43 * 247 = 106.2, under it). The bound is tight enough that any
/// drift bluer than the one token it was measured from fails. A maintainer
/// who wants 0.35 to hold everywhere should re-cut gold_bright; the number
/// to beat is in this paragraph.
pub const GOLD_LIFT_BLUE_PCT: u32 = 44;

// ── Tokens ─────────────────────────────────────────────────────────

/// Canvas. `#0A0A0C`
pub const BG: Color = Color::Rgb(0x0A, 0x0A, 0x0C);

/// Panels, cards, code blocks. `#0F0F12`
pub const PANEL: Color = Color::Rgb(0x0F, 0x0F, 0x12);

/// Selected and hover rows. `#17171B`
pub const HL: Color = Color::Rgb(0x17, 0x17, 0x1B);

/// Hairlines, dividers, unfilled meter track. `#26262C`
pub const BORDER: Color = Color::Rgb(0x26, 0x26, 0x2C);

/// Section rules, turn boundaries. `#2C2C33`
pub const RULE: Color = Color::Rgb(0x2C, 0x2C, 0x33);

/// The brand metal: actions, active states, money, the mark. `#EFC53F`
pub const GOLD: Color = Color::Rgb(0xEF, 0xC5, 0x3F);

/// Tiny live indicators only: spinner, hot marker, drift glyph. `#F7D96B`
pub const GOLD_BRIGHT: Color = Color::Rgb(0xF7, 0xD9, 0x6B);

/// Secondary emphasis, incoming context, syntax strings. `#A9AAB5`
pub const SILVER: Color = Color::Rgb(0xA9, 0xAA, 0xB5);

/// Syntax types, tertiary labels. `#BFC1CC`
pub const SILVER_TYPE: Color = Color::Rgb(0xBF, 0xC1, 0xCC);

/// Primary text on dark. `#E8E8EC`
pub const TEXT: Color = Color::Rgb(0xE8, 0xE8, 0xEC);

/// Secondary text. `#777782`
pub const MUTED: Color = Color::Rgb(0x77, 0x77, 0x82);

/// Hints, captions, line numbers. `#4B4B56`
pub const DIM: Color = Color::Rgb(0x4B, 0x4B, 0x56);

/// Code comments. `#565660`
pub const COMMENT: Color = Color::Rgb(0x56, 0x56, 0x60);

/// Pass, additive diff sign. `#74C991`
pub const GREEN: Color = Color::Rgb(0x74, 0xC9, 0x91);

/// Fail, destructive, removal diff sign. `#E0687A`
pub const RED: Color = Color::Rgb(0xE0, 0x68, 0x7A);

/// Added diff row background. `#10201A`
pub const DIFF_ADD_BG: Color = Color::Rgb(0x10, 0x20, 0x1A);

/// Removed diff row background. `#241019`
pub const DIFF_DEL_BG: Color = Color::Rgb(0x24, 0x10, 0x19);

/// Primary text on light surfaces (web light mode only). `#141416`
pub const INK: Color = Color::Rgb(0x14, 0x14, 0x16);

/// Light canvas. `#FFFFFF`
pub const PAPER: Color = Color::Rgb(0xFF, 0xFF, 0xFF);

/// Light panel. `#F6F6F8`
pub const PAPER_PANEL: Color = Color::Rgb(0xF6, 0xF6, 0xF8);

/// Light border. `#E3E3E8`
pub const PAPER_BORDER: Color = Color::Rgb(0xE3, 0xE3, 0xE8);

// ── The walkable table ─────────────────────────────────────────────

/// Which predicate a token's value is held to.
///
/// The role is declared per token in the source JSON rather than inferred from
/// the name, because inference is what lets a warm hex in under a cool name.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Clamp {
    /// `r > g > b`, `100 g >= GOLD_GREEN_PCT r`, `100 b <= GOLD_BLUE_PCT r`.
    RestingGold,
    /// The resting clamp with [`GOLD_LIFT_BLUE_PCT`] in place of the blue ceiling.
    LiftedGold,
    /// `b > r` and `g >= r` -- the second metal, never warm.
    CoolSilver,
    /// `r == g` and `b >= g` -- neutral, or tipped toward blue, never toward red.
    NeutralGray,
    /// Pass and fail. Deliberately neither metal nor gray; no channel predicate.
    Verdict,
    /// A tint carrying a sign column, not a hue in a role; no channel predicate.
    Surface,
}

/// Every token, paired with its name and the clamp it must satisfy.
pub const ALL: &[(&str, Color, Clamp)] = &[
    ("bg", BG, Clamp::NeutralGray),
    ("panel", PANEL, Clamp::NeutralGray),
    ("hl", HL, Clamp::NeutralGray),
    ("border", BORDER, Clamp::NeutralGray),
    ("rule", RULE, Clamp::NeutralGray),
    ("gold", GOLD, Clamp::RestingGold),
    ("gold-bright", GOLD_BRIGHT, Clamp::LiftedGold),
    ("silver", SILVER, Clamp::CoolSilver),
    ("silver-type", SILVER_TYPE, Clamp::CoolSilver),
    ("text", TEXT, Clamp::NeutralGray),
    ("muted", MUTED, Clamp::NeutralGray),
    ("dim", DIM, Clamp::NeutralGray),
    ("comment", COMMENT, Clamp::NeutralGray),
    ("green", GREEN, Clamp::Verdict),
    ("red", RED, Clamp::Verdict),
    ("diff-add-bg", DIFF_ADD_BG, Clamp::Surface),
    ("diff-del-bg", DIFF_DEL_BG, Clamp::Surface),
    ("ink", INK, Clamp::NeutralGray),
    ("paper", PAPER, Clamp::NeutralGray),
    ("paper-panel", PAPER_PANEL, Clamp::NeutralGray),
    ("paper-border", PAPER_BORDER, Clamp::NeutralGray),
];

// ── Predicates ───────────────────────────────────────────────────

/// Split a colour into its channels, or `None` if it is not a 24-bit value.
///
/// Every token here is [`Color::Rgb`] by construction, so `None` means a caller
/// handed us an ANSI or indexed colour -- which no clamp can speak about.
#[must_use]
pub const fn channels(color: Color) -> Option<(u8, u8, u8)> {
    match color {
        Color::Rgb(r, g, b) => Some((r, g, b)),
        _ => None,
    }
}

/// The half of the gold clamp both bounds share: descending channels and the
/// green ratio that separates gold from orange.
#[must_use]
const fn gold_shape(r: u8, g: u8, b: u8) -> bool {
    r > g && g > b && 100 * (g as u32) >= GOLD_GREEN_PCT * (r as u32)
}

/// Does this colour belong to the resting gold role?
#[must_use]
pub const fn is_resting_gold(r: u8, g: u8, b: u8) -> bool {
    gold_shape(r, g, b) && 100 * (b as u32) <= GOLD_BLUE_PCT * (r as u32)
}

/// Does this colour belong to the lifted gold role?
#[must_use]
pub const fn is_lifted_gold(r: u8, g: u8, b: u8) -> bool {
    gold_shape(r, g, b) && 100 * (b as u32) <= GOLD_LIFT_BLUE_PCT * (r as u32)
}

/// Is this colour a cool silver -- the second metal, never warm?
#[must_use]
pub const fn is_cool_silver(r: u8, g: u8, b: u8) -> bool {
    b > r && g >= r
}

/// Is this colour a neutral or blue-tipped gray?
#[must_use]
pub const fn is_neutral_gray(r: u8, g: u8, b: u8) -> bool {
    r == g && b >= g
}

/// Does `color` satisfy `clamp`? [`Clamp::Verdict`] and [`Clamp::Surface`]
/// assert nothing, so they hold for any 24-bit value.
#[must_use]
pub const fn satisfies(color: Color, clamp: Clamp) -> bool {
    let Some((r, g, b)) = channels(color) else {
        return false;
    };
    match clamp {
        Clamp::RestingGold => is_resting_gold(r, g, b),
        Clamp::LiftedGold => is_lifted_gold(r, g, b),
        Clamp::CoolSilver => is_cool_silver(r, g, b),
        Clamp::NeutralGray => is_neutral_gray(r, g, b),
        Clamp::Verdict | Clamp::Surface => true,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The anti-drift test SPEC 3.2 asks for: every shipped token against the
    /// predicate it declares. This is what makes the palette unable to rot.
    #[test]
    fn every_token_satisfies_its_clamp() {
        for (name, color, clamp) in ALL {
            assert!(
                satisfies(*color, *clamp),
                "{name} ({color:?}) violates {clamp:?}"
            );
        }
    }

    /// The retired brand metals must still fail, or the clamp has gone slack.
    /// Bronze Gold is the live case: it is what this system supersedes.
    #[test]
    fn retired_brand_golds_are_rejected() {
        // #C58A32 -- brand v4.0 Bronze Gold. 100*g = 13800, 78*r = 15366.
        assert!(!is_resting_gold(0xC5, 0x8A, 0x32));
        assert!(!is_lifted_gold(0xC5, 0x8A, 0x32));
        // #FFB000 -- brand v1.0 Phosphor Gold.
        assert!(!is_resting_gold(0xFF, 0xB0, 0x00));
        // #070B10 -- brand v4.0 Obsidian. Green-tipped, so not a neutral gray.
        assert!(!is_neutral_gray(0x07, 0x0B, 0x10));
    }

    /// The lift is an exception with a tight bound, not an open door: a gold
    /// one point bluer than `gold_bright` still fails it.
    #[test]
    fn the_gold_lift_is_bounded() {
        assert!(
            is_lifted_gold(0xF7, 0xD9, 0x6B),
            "gold_bright must pass the lift"
        );
        assert!(
            !is_resting_gold(0xF7, 0xD9, 0x6B),
            "and must fail the resting clamp"
        );
        assert!(
            !is_lifted_gold(0xF7, 0xD9, 0x6D),
            "two points bluer must fail"
        );
    }
}
