//! The palette -- SPEC-stella-tui-v2.md section 3.1.
//!
//! GENERATED by `scripts/gen-tokens.py` from `design/tokens/stella-tokens.json`.
//! Do not edit this file. Edit the JSON and run `make tokens-update`.
//!
//! Every value is [`Color::Rgb`]; there are no indexed or named colours here,
//! because the clamp can only speak about channels. [`ALL`] pairs each token
//! with the [`Clamp`] its value is held to -- so a new hex cannot enter the
//! palette without declaring what kind of colour it is, and the warm-drift
//! predicates reject the declaration that would kill the scheme.
//!
//! **Values and role tags only.** The predicates themselves live in
//! [`crate::clamp`], which is hand-written, and the tests that walk this table
//! live beside them. That split exists because the gold clamp is not a
//! templatable expression but an argument with a geometric proof behind it
//! (a lift is anchored to the gold it lifts, because the resting blue ceiling
//! is unsatisfiable above lightness 0.6745), and a generator that emitted it
//! would put the algorithm somewhere its proof could not follow.

use ratatui::style::Color;

// ── Clamp bounds ─────────────────────────────────────────────────
//
// The numbers the JSON declares. The predicates that read them are in
// `crate::clamp`.

/// The green ratio a gold must clear, as a percentage of red.
///
/// The green ratio is the hue clause: below it the hue is orange, and orange on
/// a near-black ground reads brown on cheap panels. It moved from 78 to 70 with
/// the house gold, and the account of that is plain: 78 was never measured. It
/// was the ratio v5.0's own gold happened to sit at, written down as a law.
/// #D6962C is at 0.701 and is unmistakably gold, so 78 excluded golds rather
/// than oranges.
///
/// 70 is a floor with an argument behind it: sRGB hue 30 deg is the orange the
/// clause exists to exclude, and a colour at r > g > b with g = 0.70 r sits at
/// or above sRGB hue 36 deg, six degrees clear of it. Anything below 0.70
/// crosses into that band.
///
/// The ratio carries one role. `gold-ink` is a dark SHADE of the gold, which a
/// hue ratio polices badly because darkening moves a colour's channel ratios;
/// the shade is anchored instead. See `gold-shade`.
pub const GOLD_GREEN_PCT: u32 = 70;

/// The blue ceiling a resting gold must stay under, as a percentage of red.
///
/// Governs the resting gold alone. See [`GOLD_LIFT_HUE_TOLERANCE_DEG`] for a
/// lift, and `crate::clamp` for why the two cannot be one bound.
pub const GOLD_BLUE_PCT: u32 = 35;

/// How far a lift's hue may sit from the gold it lifts, in degrees.
///
/// A lift is anchored to the gold it lifts, never held to a second blue
/// ceiling. A revision of this file carried `lifted-gold` with blue_pct 44 -- a
/// bound reverse-engineered from the one token it had to admit, which can say
/// no to nothing in principle. It was answering the wrong question: in a
/// gold, lightness is (r + b) / 510, so the resting ceiling 100*b <= 35*r
/// caps lightness for ANY colour, and a lift sits above that line. There the
/// ceiling is not strict, it is unsatisfiable.
///
/// So the two clauses are stated where each is coherent. The green ratio is
/// the HUE rule -- gold versus orange -- and it holds at every lightness, so
/// every gold carries it. The blue ceiling is the SATURATION rule and governs
/// only the resting gold, which is not lightened. A lift is then pinned to
/// the anchor: same hue within hue_tolerance_deg, strictly lighter.
///
/// An anchor is the stronger constraint, not the looser one. A ceiling admits
/// every colour beneath it and keeps passing after the gold it was cut for is
/// gone; an anchor admits only the authored gold, brighter. Recolour `gold`
/// and leave `gold-bright` behind and the check fails, naming the hue
/// distance.
///
/// hue_tolerance_deg is derived, not chosen: stella-tui's v1 theme records
/// that its warning amber sat 4.0 deg from gold 'so an outcome may never be
/// told from chrome by hue alone'. 4 deg is the distance this repository
/// already treats as indistinguishable, so a lift -- which must be the SAME
/// hue -- sits inside it. It was written as 3 while the only lift on file
/// happened to sit at 2.9; the house pair sits at 3.0, which is what exposed
/// the number as a measurement of one sample rather than a law.
pub const GOLD_LIFT_HUE_TOLERANCE_DEG: f64 = 4.0;

/// The name, in [`ALL`], of the token a lift is anchored to.
///
/// `crate::clamp::satisfies` resolves the anchor through this name rather
/// than naming [`GOLD`] itself, so renaming the anchored token is one edit
/// in the source JSON and a failing lookup everywhere else, never a silent
/// mismatch.
pub const GOLD_LIFT_ANCHOR: &str = "gold";

/// How far a shade's hue may sit from the gold it darkens, in degrees.
///
/// The mirror of `gold-lift`. `gold-ink` is the gold where the metal itself is
/// illegible: as text or a hairline on paper, where #D6962C is 2.2:1. Same hue,
/// darkened.
///
/// A ratio is the wrong tool for it. Darkening squeezes a colour's channels
/// unevenly, so a shade's g/r drifts from its parent's for reasons that are not
/// about hue. Hold a shade to a ratio and the ratio has to drop until it lets
/// the shade in. A ratio that wide stops holding the hue of the bright one.
///
/// An anchor asks the question that counts: is this the SAME gold, darker?
/// Recolour `gold` and `gold-ink` fails by name. A ratio cannot do that.
pub const GOLD_SHADE_HUE_TOLERANCE_DEG: f64 = 4.0;

/// The name, in [`ALL`], of the token a shade is anchored to.
pub const GOLD_SHADE_ANCHOR: &str = "gold";

/// The green floor every neutral must clear, as a percentage of red.
///
/// One neutral clamp for the whole system, in place of v5.0's `neutral-gray`,
/// `cool-silver` and `warm-paper`. Three clamps answered to three neutral
/// families: a blue-tipped dark ramp, two silvers sitting off neutral in the
/// same direction, and a warm paper ramp. The house system has ONE -- every
/// neutral, from #0A0A09 to #FBFAF6, is warm or exactly neutral, never blue --
/// and three predicates over one family is three places for it to drift.
///
/// `r >= g >= b` is the direction: warm or neutral, never cool. The floors stop
/// it turning tan or sepia. That is the way a black-and-gold scheme fails:
/// the greys creep warm one reasonable step at a time
/// until the gold stops reading as a separate colour. 94 and 82 are the tightest
/// integer floors the house ramp clears, measured against its two extremes: the
/// hairline on ink (#292722, g/r 0.951) and the hairline on paper (#D8CDBD, b/r
/// 0.875).
///
/// Equality is admitted on both sides because the darkest stops are neutral to
/// the byte -- #10100F is r == g -- and rounding at that lightness has nowhere
/// else to land.
pub const NEUTRAL_GREEN_PCT: u32 = 94;

/// The blue floor every neutral must clear, as a percentage of red.
pub const NEUTRAL_BLUE_PCT: u32 = 82;

// ── Tokens ─────────────────────────────────────────────────────────

/// Canvas. `#10100F`
pub const BG: Color = Color::Rgb(0x10, 0x10, 0x0F);

/// Panels, cards, code blocks. `#181715`
pub const PANEL: Color = Color::Rgb(0x18, 0x17, 0x15);

/// Selected and hover rows. `#201F1C`
pub const HL: Color = Color::Rgb(0x20, 0x1F, 0x1C);

/// Hairlines, dividers, unfilled meter track. `#292722`
pub const BORDER: Color = Color::Rgb(0x29, 0x27, 0x22);

/// Section rules, turn boundaries. `#34322D`
pub const RULE: Color = Color::Rgb(0x34, 0x32, 0x2D);

/// The brand metal: actions, active states, money, the mark. `#D6962C`
pub const GOLD: Color = Color::Rgb(0xD6, 0x96, 0x2C);

/// Tiny live indicators only: spinner, hot marker, drift glyph. `#F1C364`
pub const GOLD_BRIGHT: Color = Color::Rgb(0xF1, 0xC3, 0x64);

/// Secondary emphasis, incoming context, syntax strings. `#9B958A`
pub const SILVER: Color = Color::Rgb(0x9B, 0x95, 0x8A);

/// Syntax types, tertiary labels. `#DDD8CD`
pub const SILVER_TYPE: Color = Color::Rgb(0xDD, 0xD8, 0xCD);

/// Primary text on the dark canvas, in the deck and off it. `#F2EEE5`
pub const TEXT: Color = Color::Rgb(0xF2, 0xEE, 0xE5);

/// Secondary text. `#8C877C`
pub const MUTED: Color = Color::Rgb(0x8C, 0x87, 0x7C);

/// Hints, captions, line numbers. `#6E6A62`
pub const DIM: Color = Color::Rgb(0x6E, 0x6A, 0x62);

/// Pass, additive diff sign. `#74C991`
pub const GREEN: Color = Color::Rgb(0x74, 0xC9, 0x91);

/// Fail, destructive, removal diff sign. `#E0687D`
pub const RED: Color = Color::Rgb(0xE0, 0x68, 0x7D);

/// Added diff row background. `#10201A`
pub const DIFF_ADD_BG: Color = Color::Rgb(0x10, 0x20, 0x1A);

/// Removed diff row background. `#241019`
pub const DIFF_DEL_BG: Color = Color::Rgb(0x24, 0x10, 0x19);

/// Primary text on light surfaces (web light mode only). `#10100F`
pub const INK: Color = Color::Rgb(0x10, 0x10, 0x0F);

/// The warm light canvas. `#FBFAF6`
pub const PAPER: Color = Color::Rgb(0xFB, 0xFA, 0xF6);

/// Light panel. `#F5F2EA`
pub const PAPER_PANEL: Color = Color::Rgb(0xF5, 0xF2, 0xEA);

/// Light border. `#DED5C7`
pub const PAPER_BORDER: Color = Color::Rgb(0xDE, 0xD5, 0xC7);

/// The warm paper page ground, one step under the panel. `#F2EEE5`
pub const PAPER_GROUND: Color = Color::Rgb(0xF2, 0xEE, 0xE5);

/// Light surface raised above the page ground. `#F8F5EE`
pub const PAPER_RAISED: Color = Color::Rgb(0xF8, 0xF5, 0xEE);

/// Light hover and selected rows. `#E5DED1`
pub const PAPER_ROW: Color = Color::Rgb(0xE5, 0xDE, 0xD1);

/// Light seam: the hairline under a border. `#D8CDBD`
pub const PAPER_SEAM: Color = Color::Rgb(0xD8, 0xCD, 0xBD);

/// Secondary text on light surfaces. `#6B665C`
pub const INK_MUTED: Color = Color::Rgb(0x6B, 0x66, 0x5C);

/// Warning: the one status the core palette does not name. `#EB8960`
pub const WARNING: Color = Color::Rgb(0xEB, 0x89, 0x60);

// ── The walkable table ─────────────────────────────────────────────

/// Which predicate a token's value is held to.
///
/// The role is declared per token in the source JSON rather than inferred from
/// the name, because inference is what lets a warm hex in under a cool name.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Clamp {
    /// `r > g > b`, `100 g >= GOLD_GREEN_PCT r`, `100 b <= GOLD_BLUE_PCT r`.
    RestingGold,
    /// Anchored to the resting gold: the same hue within
    /// [`GOLD_LIFT_HUE_TOLERANCE_DEG`], strictly lighter. Never a second blue
    /// ceiling -- `crate::clamp` carries the argument.
    GoldLift,
    /// Anchored to the resting gold: the same hue within
    /// [`GOLD_SHADE_HUE_TOLERANCE_DEG`], strictly darker. The mirror of
    /// [`Clamp::GoldLift`], and what frees the green ratio from policing
    /// a value that darkening moves off it.
    GoldShade,
    /// `r >= g >= b`, `100 g >= NEUTRAL_GREEN_PCT r`,
    /// `100 b >= NEUTRAL_BLUE_PCT r` -- every neutral in the system, ink to
    /// paper. Warm or exactly neutral, never cool.
    WarmNeutral,
    /// Pass and fail. Neither metal nor gray; no channel predicate.
    Verdict,
    /// A tint carrying a sign column, not a hue in a role; no channel predicate.
    Surface,
}

/// Every token, paired with its name and the clamp it must satisfy.
pub const ALL: &[(&str, Color, Clamp)] = &[
    ("bg", BG, Clamp::WarmNeutral),
    ("panel", PANEL, Clamp::WarmNeutral),
    ("hl", HL, Clamp::WarmNeutral),
    ("border", BORDER, Clamp::WarmNeutral),
    ("rule", RULE, Clamp::WarmNeutral),
    ("gold", GOLD, Clamp::RestingGold),
    ("gold-bright", GOLD_BRIGHT, Clamp::GoldLift),
    ("silver", SILVER, Clamp::WarmNeutral),
    ("silver-type", SILVER_TYPE, Clamp::WarmNeutral),
    ("text", TEXT, Clamp::WarmNeutral),
    ("muted", MUTED, Clamp::WarmNeutral),
    ("dim", DIM, Clamp::WarmNeutral),
    ("green", GREEN, Clamp::Verdict),
    ("red", RED, Clamp::Verdict),
    ("diff-add-bg", DIFF_ADD_BG, Clamp::Surface),
    ("diff-del-bg", DIFF_DEL_BG, Clamp::Surface),
    ("ink", INK, Clamp::WarmNeutral),
    ("paper", PAPER, Clamp::WarmNeutral),
    ("paper-panel", PAPER_PANEL, Clamp::WarmNeutral),
    ("paper-border", PAPER_BORDER, Clamp::WarmNeutral),
    ("paper-ground", PAPER_GROUND, Clamp::WarmNeutral),
    ("paper-raised", PAPER_RAISED, Clamp::WarmNeutral),
    ("paper-row", PAPER_ROW, Clamp::WarmNeutral),
    ("paper-seam", PAPER_SEAM, Clamp::WarmNeutral),
    ("ink-muted", INK_MUTED, Clamp::WarmNeutral),
    ("amber", WARNING, Clamp::Verdict),
];

// The predicates that read this table are in `crate::clamp`, and the
// tests that walk it live beside them. See this file's module doc for why
// the algorithm is not generated.

/// The colour [`GOLD_LIFT_ANCHOR`] names, or `None` if [`ALL`] has no
/// such entry.
#[must_use]
pub fn lift_anchor() -> Option<Color> {
    ALL.iter()
        .find(|(name, _, _)| *name == GOLD_LIFT_ANCHOR)
        .map(|(_, color, _)| *color)
}

/// The colour [`GOLD_SHADE_ANCHOR`] names, or `None` if [`ALL`] has no
/// such entry.
#[must_use]
pub fn shade_anchor() -> Option<Color> {
    ALL.iter()
        .find(|(name, _, _)| *name == GOLD_SHADE_ANCHOR)
        .map(|(_, color, _)| *color)
}
