//! The palette -- SPEC-stella-tui-v2.md section 3.1.
//!
//! GENERATED by `scripts/gen-tokens.py` from `design/tokens/stella-tokens.json`.
//! Do not edit this file. Edit the JSON and run `make tokens-update`.
//!
//! Every value is [`Color::Rgb`]; there are no indexed or named colours here,
//! because the clamp can only speak about channels. [`ALL`] pairs each token
//! with the [`Clamp`] its value is held to -- so a new hex cannot enter the
//! palette without declaring what kind of colour it is, and the warm-drift
//! predicates reject the declaration that would kill the scheme.
//!
//! **Values and role tags only.** The predicates themselves live in
//! [`crate::clamp`], which is hand-written, and the tests that walk this table
//! live beside them. That split is deliberate: the gold clamp is not a
//! templatable expression but an argument with a geometric proof behind it
//! (a lift is anchored to the gold it lifts, because the resting blue ceiling
//! is unsatisfiable above lightness 0.6745), and a generator that emitted it
//! would put the algorithm somewhere its proof could not follow.

use ratatui::style::Color;

// ── Clamp bounds ─────────────────────────────────────────────────
//
// The numbers the JSON declares. The predicates that read them are in
// `crate::clamp`.

/// The green ratio a gold must clear, as a percentage of red.
///
/// The green ratio is the decisive half: below it the hue is orange, and orange on a near-black ground reads brown on cheap panels.
pub const GOLD_GREEN_PCT: u32 = 78;

/// The blue ceiling a resting gold must stay under, as a percentage of red.
///
/// Governs the resting gold alone. See [`GOLD_LIFT_HUE_TOLERANCE_DEG`] for a
/// lift, and `crate::clamp` for why the two cannot be one bound.
pub const GOLD_BLUE_PCT: u32 = 35;

/// How far a lift's hue may sit from the gold it lifts, in degrees.
///
/// A lift is anchored to the gold it lifts, never held to a second blue
/// ceiling. An earlier revision of this file carried `lifted-gold` with
/// blue_pct 44 -- a bound reverse-engineered from the one token it had to
/// admit, which can say no to nothing in principle. It was answering the
/// wrong question: in a gold, lightness is (r + b) / 510, so the resting
/// ceiling 100*b <= 35*r caps lightness at (255 + 89) / 510 = 0.6745 for
/// ANY colour, and gold_bright sits at 0.6941. Above that line the resting
/// ceiling is not strict, it is unsatisfiable -- so a lift could never have
/// been held to it, and a looser ceiling repeats the category error one
/// notch down.
///
/// So the two clauses are stated where each is coherent. `100*g >= 78*r` is
/// the HUE rule -- gold versus orange, the argument SPEC 3.2 actually makes
/// -- and it holds at every lightness, so every gold carries it. The blue
/// ceiling is the SATURATION rule and governs only the resting gold, which
/// is not lightened. A lift is then pinned to the anchor: same hue within
/// hue_tolerance_deg, strictly lighter.
///
/// An anchor is the stronger constraint, not the looser one. A ceiling
/// admits every colour beneath it and keeps passing after the gold it was
/// cut for is gone; an anchor admits only the authored gold, brighter.
/// Recolour `gold` and leave `gold-bright` behind and the check fails,
/// naming the hue distance.
///
/// hue_tolerance_deg is derived, not chosen: stella-tui's v1 theme records
/// that its warning amber sits 4.0 deg from gold 'so an outcome may never
/// be told from chrome by hue alone'. 4 deg is the distance this repository
/// already treats as indistinguishable, so a lift -- which must be the SAME
/// hue -- sits inside it.
pub const GOLD_LIFT_HUE_TOLERANCE_DEG: f64 = 3.0;

/// The token a lift is anchored to.
pub const GOLD_LIFT_ANCHOR: &str = "gold";

/// The green floor warm paper must clear, as a percentage of red.
///
/// The light ground's clamp: warm or neutral, never blue. The floors keep paper from becoming tan, and are taken from brand v1.0's own light neutrals, which sit at g = 0.988 r and b = 0.960 r.
pub const PAPER_GREEN_PCT: u32 = 97;

/// The blue floor warm paper must clear, as a percentage of red.
pub const PAPER_BLUE_PCT: u32 = 93;

// ── Tokens ─────────────────────────────────────────────────────────

/// Canvas. `#0A0A0C`
pub const BG: Color = Color::Rgb(0x0A, 0x0A, 0x0C);

/// Panels, cards, code blocks. `#0F0F12`
pub const PANEL: Color = Color::Rgb(0x0F, 0x0F, 0x12);

/// Selected and hover rows. `#17171B`
pub const HL: Color = Color::Rgb(0x17, 0x17, 0x1B);

/// Hairlines, dividers, unfilled meter track. `#26262C`
pub const BORDER: Color = Color::Rgb(0x26, 0x26, 0x2C);

/// Section rules, turn boundaries. `#2C2C33`
pub const RULE: Color = Color::Rgb(0x2C, 0x2C, 0x33);

/// The brand metal: actions, active states, money, the mark. `#EFC53F`
pub const GOLD: Color = Color::Rgb(0xEF, 0xC5, 0x3F);

/// Tiny live indicators only: spinner, hot marker, drift glyph. `#F7D96B`
pub const GOLD_BRIGHT: Color = Color::Rgb(0xF7, 0xD9, 0x6B);

/// Secondary emphasis, incoming context, syntax strings. `#A9AAB5`
pub const SILVER: Color = Color::Rgb(0xA9, 0xAA, 0xB5);

/// Syntax types, tertiary labels. `#BFC1CC`
pub const SILVER_TYPE: Color = Color::Rgb(0xBF, 0xC1, 0xCC);

/// Primary text on dark, in the deck. `#E8E8EC`
pub const TEXT: Color = Color::Rgb(0xE8, 0xE8, 0xEC);

/// Secondary text. `#777782`
pub const MUTED: Color = Color::Rgb(0x77, 0x77, 0x82);

/// Hints, captions, line numbers. `#4B4B56`
pub const DIM: Color = Color::Rgb(0x4B, 0x4B, 0x56);

/// Code comments. `#565660`
pub const COMMENT: Color = Color::Rgb(0x56, 0x56, 0x60);

/// Pass, additive diff sign. `#74C991`
pub const GREEN: Color = Color::Rgb(0x74, 0xC9, 0x91);

/// Fail, destructive, removal diff sign. `#E0687A`
pub const RED: Color = Color::Rgb(0xE0, 0x68, 0x7A);

/// Added diff row background. `#10201A`
pub const DIFF_ADD_BG: Color = Color::Rgb(0x10, 0x20, 0x1A);

/// Removed diff row background. `#241019`
pub const DIFF_DEL_BG: Color = Color::Rgb(0x24, 0x10, 0x19);

/// Primary text on light surfaces (web light mode only). `#141413`
pub const INK: Color = Color::Rgb(0x14, 0x14, 0x13);

/// The warm light canvas. `#FFFCF5`
pub const PAPER: Color = Color::Rgb(0xFF, 0xFC, 0xF5);

/// Light panel. `#F9F6EF`
pub const PAPER_PANEL: Color = Color::Rgb(0xF9, 0xF6, 0xEF);

/// Light border. `#E6E3DD`
pub const PAPER_BORDER: Color = Color::Rgb(0xE6, 0xE3, 0xDD);

// ── The walkable table ─────────────────────────────────────────────

/// Which predicate a token's value is held to.
///
/// The role is declared per token in the source JSON rather than inferred from
/// the name, because inference is what lets a warm hex in under a cool name.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Clamp {
    /// `r > g > b`, `100 g >= GOLD_GREEN_PCT r`, `100 b <= GOLD_BLUE_PCT r`.
    RestingGold,
    /// Anchored to the resting gold: the same hue within
    /// [`GOLD_LIFT_HUE_TOLERANCE_DEG`], strictly lighter. Never a second blue
    /// ceiling -- `crate::clamp` carries the argument.
    GoldLift,
    /// `b > r` and `g >= r` -- the second metal, never warm.
    CoolSilver,
    /// `r == g` and `b >= g` -- neutral, or tipped toward blue, never toward red.
    NeutralGray,
    /// `r >= g >= b`, `100 g >= PAPER_GREEN_PCT r`, `100 b >= PAPER_BLUE_PCT r`
    /// -- the light ground, warm or neutral, never blue.
    WarmPaper,
    /// Pass and fail. Deliberately neither metal nor gray; no channel predicate.
    Verdict,
    /// A tint carrying a sign column, not a hue in a role; no channel predicate.
    Surface,
}

/// Every token, paired with its name and the clamp it must satisfy.
pub const ALL: &[(&str, Color, Clamp)] = &[
    ("bg", BG, Clamp::NeutralGray),
    ("panel", PANEL, Clamp::NeutralGray),
    ("hl", HL, Clamp::NeutralGray),
    ("border", BORDER, Clamp::NeutralGray),
    ("rule", RULE, Clamp::NeutralGray),
    ("gold", GOLD, Clamp::RestingGold),
    ("gold-bright", GOLD_BRIGHT, Clamp::GoldLift),
    ("silver", SILVER, Clamp::CoolSilver),
    ("silver-type", SILVER_TYPE, Clamp::CoolSilver),
    ("text", TEXT, Clamp::NeutralGray),
    ("muted", MUTED, Clamp::NeutralGray),
    ("dim", DIM, Clamp::NeutralGray),
    ("comment", COMMENT, Clamp::NeutralGray),
    ("green", GREEN, Clamp::Verdict),
    ("red", RED, Clamp::Verdict),
    ("diff-add-bg", DIFF_ADD_BG, Clamp::Surface),
    ("diff-del-bg", DIFF_DEL_BG, Clamp::Surface),
    ("ink", INK, Clamp::WarmPaper),
    ("paper", PAPER, Clamp::WarmPaper),
    ("paper-panel", PAPER_PANEL, Clamp::WarmPaper),
    ("paper-border", PAPER_BORDER, Clamp::WarmPaper),
];

// The predicates that read this table are in `crate::clamp`, and the
// tests that walk it live beside them. See this file's module doc for why
// the algorithm is not generated.
