//! The palette -- SPEC-stella-tui-v2.md section 3.1.
//!
//! GENERATED by `scripts/gen-tokens.py` from `design/tokens/stella-tokens.json`.
//! Do not edit this file. Edit the JSON and run `make tokens-update`.
//!
//! Every value is [`Color::Rgb`]; there are no indexed or named colours here,
//! because the clamp can only speak about channels. [`ALL`] pairs each token
//! with the [`Clamp`] its value is held to -- so a new hex cannot enter the
//! palette without declaring what kind of colour it is, and the warm-drift
//! predicates reject the declaration that would kill the scheme.
//!
//! **Values and role tags only.** The predicates themselves live in
//! [`crate::clamp`], which is hand-written, and the tests that walk this table
//! live beside them. That split exists because the gold clamp is not a
//! templatable expression but an argument with a geometric proof behind it
//! (a lift is anchored to the gold it lifts, because the resting blue ceiling
//! is unsatisfiable above lightness 0.6745), and a generator that emitted it
//! would put the algorithm somewhere its proof could not follow.

use ratatui::style::Color;

// ── Clamp bounds ─────────────────────────────────────────────────
//
// The numbers the JSON declares. The predicates that read them are in
// `crate::clamp`.

/// The green ratio a gold must clear, as a percentage of red.
///
/// The green ratio is the hue clause: below it the hue is orange, and orange on
/// a near-black ground reads brown on cheap panels. It moved from 78 to 70 with
/// the house gold, and the account of that is plain: 78 was never measured. It
/// was the ratio v5.0's own gold happened to sit at, written down as a law.
/// #D6962C is at 0.701 and is unmistakably gold, so 78 excluded golds rather
/// than oranges.
///
/// 70 is a floor with an argument behind it: sRGB hue 30 deg is the orange the
/// clause exists to exclude, and a colour at r > g > b with g = 0.70 r sits at
/// or above sRGB hue 36 deg, six degrees clear of it. Anything below 0.70
/// crosses into that band.
///
/// The ratio carries one role. `gold-ink` is a dark SHADE of the gold, which a
/// hue ratio polices badly because darkening moves a colour's channel ratios;
/// the shade is anchored instead. See `gold-shade`.
pub const GOLD_GREEN_PCT: u32 = 70;

/// The blue ceiling a resting gold must stay under, as a percentage of red.
///
/// Governs the resting gold alone. See [`GOLD_LIFT_HUE_TOLERANCE_DEG`] for a
/// lift, and `crate::clamp` for why the two cannot be one bound.
pub const GOLD_BLUE_PCT: u32 = 35;

/// How far a lift's hue may sit from the gold it lifts, in degrees.
///
/// A lift is anchored to the gold it lifts, never held to a second blue
/// ceiling. A revision of this file carried `lifted-gold` with blue_pct 44 -- a
/// bound reverse-engineered from the one token it had to admit, which can say
/// no to nothing in principle. It was answering the wrong question: in a
/// gold, lightness is (r + b) / 510, so the resting ceiling 100*b <= 35*r
/// caps lightness for ANY colour, and a lift sits above that line. There the
/// ceiling is not strict, it is unsatisfiable.
///
/// So the two clauses are stated where each is coherent. The green ratio is
/// the HUE rule -- gold versus orange -- and it holds at every lightness, so
/// every gold carries it. The blue ceiling is the SATURATION rule and governs
/// only the resting gold, which is not lightened. A lift is then pinned to
/// the anchor: same hue within hue_tolerance_deg, strictly lighter.
///
/// An anchor is the stronger constraint, not the looser one. A ceiling admits
/// every colour beneath it and keeps passing after the gold it was cut for is
/// gone; an anchor admits only the authored gold, brighter. Recolour `gold`
/// and leave `gold-bright` behind and the check fails, naming the hue
/// distance.
///
/// hue_tolerance_deg is derived, not chosen: stella-tui's v1 theme records
/// that its warning amber sat 4.0 deg from gold 'so an outcome may never be
/// told from chrome by hue alone'. 4 deg is the distance this repository
/// already treats as indistinguishable, so a lift -- which must be the SAME
/// hue -- sits inside it. It was written as 3 while the only lift on file
/// happened to sit at 2.9; the house pair sits at 3.0, which is what exposed
/// the number as a measurement of one sample rather than a law.
pub const GOLD_LIFT_HUE_TOLERANCE_DEG: f64 = 4.0;

/// The name, in [`ALL`], of the token a lift is anchored to.
///
/// `crate::clamp::satisfies` resolves the anchor through this name rather
/// than naming [`GOLD`] itself, so renaming the anchored token is one edit
/// in the source JSON and a failing lookup everywhere else, never a silent
/// mismatch.
pub const GOLD_LIFT_ANCHOR: &str = "gold";

/// How far a shade's hue may sit from the gold it darkens, in degrees.
///
/// The mirror of `gold-lift`. `gold-ink` is the gold where the metal itself is
/// illegible: as text or a hairline on paper, where #D6962C is 2.2:1. Same hue,
/// darkened.
///
/// A ratio is the wrong tool for it. Darkening squeezes a colour's channels
/// unevenly, so a shade's g/r drifts from its parent's for reasons that are not
/// about hue. Hold a shade to a ratio and the ratio has to drop until it lets
/// the shade in. A ratio that wide stops holding the hue of the bright one.
///
/// An anchor asks the question that counts: is this the SAME gold, darker?
/// Recolour `gold` and `gold-ink` fails by name. A ratio cannot do that.
pub const GOLD_SHADE_HUE_TOLERANCE_DEG: f64 = 4.0;

/// The name, in [`ALL`], of the token a shade is anchored to.
pub const GOLD_SHADE_ANCHOR: &str = "gold";

/// The widest spread of channels a neutral may have: max - min.
///
/// One neutral clamp for the whole system, ink to paper. The house system's
/// zinc ramp leans a few units blue (its 500 step has b - r = 9).
///
/// A black-and-gold scheme must not let a grey carry a hue: a tan grey competes
/// with the gold, a blue one fights it. A bound on the spread of the channels
/// says exactly that, in both directions. 12 is the tightest bound the zinc
/// ramp clears with room (its widest stop spreads 9) and the loosest that still
/// rejects a sepia grey spreading 13.
pub const NEUTRAL_SPREAD: u8 = 12;

// ── Tokens ─────────────────────────────────────────────────────────

/// Canvas. `#09090B`
pub const BG: Color = Color::Rgb(0x09, 0x09, 0x0B);

/// Panels, cards, code blocks. `#18181B`
pub const PANEL: Color = Color::Rgb(0x18, 0x18, 0x1B);

/// Selected and hover rows. `#1F1F23`
pub const HL: Color = Color::Rgb(0x1F, 0x1F, 0x23);

/// Hairlines, dividers, unfilled meter track. `#27272A`
pub const BORDER: Color = Color::Rgb(0x27, 0x27, 0x2A);

/// Section rules, turn boundaries. `#3F3F46`
pub const RULE: Color = Color::Rgb(0x3F, 0x3F, 0x46);

/// The brand metal: actions, active states, money, the mark. `#D4AF37`
pub const GOLD: Color = Color::Rgb(0xD4, 0xAF, 0x37);

/// Tiny live indicators only: spinner, hot marker, drift glyph. `#F1CE65`
pub const GOLD_BRIGHT: Color = Color::Rgb(0xF1, 0xCE, 0x65);

/// Secondary emphasis, incoming context, syntax strings. `#A1A1AA`
pub const SILVER: Color = Color::Rgb(0xA1, 0xA1, 0xAA);

/// Syntax types, tertiary labels. `#E4E4E7`
pub const SILVER_TYPE: Color = Color::Rgb(0xE4, 0xE4, 0xE7);

/// Primary text on the dark canvas, in the deck and off it. `#FFFFFF`
pub const TEXT: Color = Color::Rgb(0xFF, 0xFF, 0xFF);

/// Secondary text. `#8A8A93`
pub const MUTED: Color = Color::Rgb(0x8A, 0x8A, 0x93);

/// Hints, captions, line numbers. `#71717A`
pub const DIM: Color = Color::Rgb(0x71, 0x71, 0x7A);

/// Pass, additive diff sign. `#74C991`
pub const GREEN: Color = Color::Rgb(0x74, 0xC9, 0x91);

/// Fail, destructive, removal diff sign. `#E0687D`
pub const RED: Color = Color::Rgb(0xE0, 0x68, 0x7D);

/// Added diff row background. `#10201A`
pub const DIFF_ADD_BG: Color = Color::Rgb(0x10, 0x20, 0x1A);

/// Removed diff row background. `#241019`
pub const DIFF_DEL_BG: Color = Color::Rgb(0x24, 0x10, 0x19);

/// Primary text on light surfaces (web light mode only). `#09090B`
pub const INK: Color = Color::Rgb(0x09, 0x09, 0x0B);

/// The warm light canvas. `#FFFFFF`
pub const PAPER: Color = Color::Rgb(0xFF, 0xFF, 0xFF);

/// Light panel. `#FFFFFF`
pub const PAPER_PANEL: Color = Color::Rgb(0xFF, 0xFF, 0xFF);

/// Light border. `#E4E4E7`
pub const PAPER_BORDER: Color = Color::Rgb(0xE4, 0xE4, 0xE7);

/// The warm paper page ground, one step under the panel. `#FFFFFF`
pub const PAPER_GROUND: Color = Color::Rgb(0xFF, 0xFF, 0xFF);

/// Light surface raised above the page ground. `#FFFFFF`
pub const PAPER_RAISED: Color = Color::Rgb(0xFF, 0xFF, 0xFF);

/// Light hover and selected rows. `#F4F4F5`
pub const PAPER_ROW: Color = Color::Rgb(0xF4, 0xF4, 0xF5);

/// Light seam: the hairline under a border. `#E4E4E7`
pub const PAPER_SEAM: Color = Color::Rgb(0xE4, 0xE4, 0xE7);

/// Secondary text on light surfaces. `#71717A`
pub const INK_MUTED: Color = Color::Rgb(0x71, 0x71, 0x7A);

/// Warning: the one status the core palette does not name. `#EB8960`
pub const WARNING: Color = Color::Rgb(0xEB, 0x89, 0x60);

// ── The walkable table ─────────────────────────────────────────────

/// Which predicate a token's value is held to.
///
/// The role is declared per token in the source JSON rather than inferred from
/// the name, because inference is what lets a warm hex in under a cool name.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Clamp {
    /// `r > g > b`, `100 g >= GOLD_GREEN_PCT r`, `100 b <= GOLD_BLUE_PCT r`.
    RestingGold,
    /// Anchored to the resting gold: the same hue within
    /// [`GOLD_LIFT_HUE_TOLERANCE_DEG`], strictly lighter. Never a second blue
    /// ceiling -- `crate::clamp` carries the argument.
    GoldLift,
    /// Anchored to the resting gold: the same hue within
    /// [`GOLD_SHADE_HUE_TOLERANCE_DEG`], strictly darker. The mirror of
    /// [`Clamp::GoldLift`], and what frees the green ratio from policing
    /// a value that darkening moves off it.
    GoldShade,
    /// `max(r, g, b) - min(r, g, b) <= NEUTRAL_SPREAD` -- every neutral in
    /// the system, ink to paper. A grey carries no hue, in either direction.
    Neutral,
    /// Pass and fail. Neither metal nor gray; no channel predicate.
    Verdict,
    /// A tint carrying a sign column, not a hue in a role; no channel predicate.
    Surface,
}

/// Every token, paired with its name and the clamp it must satisfy.
pub const ALL: &[(&str, Color, Clamp)] = &[
    ("bg", BG, Clamp::Neutral),
    ("panel", PANEL, Clamp::Neutral),
    ("hl", HL, Clamp::Neutral),
    ("border", BORDER, Clamp::Neutral),
    ("rule", RULE, Clamp::Neutral),
    ("gold", GOLD, Clamp::RestingGold),
    ("gold-bright", GOLD_BRIGHT, Clamp::GoldLift),
    ("silver", SILVER, Clamp::Neutral),
    ("silver-type", SILVER_TYPE, Clamp::Neutral),
    ("text", TEXT, Clamp::Neutral),
    ("muted", MUTED, Clamp::Neutral),
    ("dim", DIM, Clamp::Neutral),
    ("green", GREEN, Clamp::Verdict),
    ("red", RED, Clamp::Verdict),
    ("diff-add-bg", DIFF_ADD_BG, Clamp::Surface),
    ("diff-del-bg", DIFF_DEL_BG, Clamp::Surface),
    ("ink", INK, Clamp::Neutral),
    ("paper", PAPER, Clamp::Neutral),
    ("paper-panel", PAPER_PANEL, Clamp::Neutral),
    ("paper-border", PAPER_BORDER, Clamp::Neutral),
    ("paper-ground", PAPER_GROUND, Clamp::Neutral),
    ("paper-raised", PAPER_RAISED, Clamp::Neutral),
    ("paper-row", PAPER_ROW, Clamp::Neutral),
    ("paper-seam", PAPER_SEAM, Clamp::Neutral),
    ("ink-muted", INK_MUTED, Clamp::Neutral),
    ("amber", WARNING, Clamp::Verdict),
];

// The predicates that read this table are in `crate::clamp`, and the
// tests that walk it live beside them. See this file's module doc for why
// the algorithm is not generated.

/// The colour [`GOLD_LIFT_ANCHOR`] names, or `None` if [`ALL`] has no
/// such entry.
#[must_use]
pub fn lift_anchor() -> Option<Color> {
    ALL.iter()
        .find(|(name, _, _)| *name == GOLD_LIFT_ANCHOR)
        .map(|(_, color, _)| *color)
}

/// The colour [`GOLD_SHADE_ANCHOR`] names, or `None` if [`ALL`] has no
/// such entry.
#[must_use]
pub fn shade_anchor() -> Option<Color> {
    ALL.iter()
        .find(|(name, _, _)| *name == GOLD_SHADE_ANCHOR)
        .map(|(_, color, _)| *color)
}
