// GENERATED by build/build.py from build/typeset.py. Do not edit.
//
// The three house faces for next/font/local. The paths are relative to
// this file: tokens/ beside fonts/, as in the kit. Keep that layout where
// the two are vendored, or rewrite the paths there. In the root layout:
//
//   import { fontVariables } from "@/styles/next-fonts";
//   <html lang="en" className={fontVariables}>
//
// Each loader sets one CSS variable on <html>; tokens/house-tailwind.css
// reads them into --font-display, --font-sans and --font-mono.

import localFont from "next/font/local";

/** Space Grotesk: wordmarks, h1, h2, h3. */
export const spaceGrotesk = localFont({
  src: [
    { path: "../fonts/space-grotesk-latin-400.woff2", weight: "400", style: "normal" },
    { path: "../fonts/space-grotesk-latin-500.woff2", weight: "500", style: "normal" },
    { path: "../fonts/space-grotesk-latin-600.woff2", weight: "600", style: "normal" },
    { path: "../fonts/space-grotesk-latin-700.woff2", weight: "700", style: "normal" },
  ],
  variable: "--font-space-grotesk",
  display: "swap",
  fallback: ["Helvetica Neue", "Arial"],
});

/** Geist: h4 to h6, body, labels, buttons, tables, navigation. */
export const geist = localFont({
  src: "../fonts/geist-latin-wght.woff2",
  weight: "100 900",
  variable: "--font-geist",
  display: "swap",
  fallback: ["system-ui", "-apple-system", "Segoe UI"],
});

/** Monaspace Neon: code, terminal output, logs, digests, paths, ids, and numbers in tables. */
export const monaspaceNeon = localFont({
  src: "../fonts/monaspace-neon-latin-wght.woff2",
  weight: "200 800",
  variable: "--font-monaspace-neon",
  display: "swap",
  fallback: ["SF Mono", "Menlo", "Consolas"],
  adjustFontFallback: false,
});

/** Every variable, for the <html> className. */
export const fontVariables = [spaceGrotesk.variable, geist.variable, monaspaceNeon.variable].join(" ");
