// GENERATED by build/build.py from theme/theme.json. Do not edit.
//
// The three house faces for next/font/local. The paths are relative to
// this file: tokens/ beside fonts/, as in the kit. Keep that layout where
// the two are vendored, or rewrite the paths there. In the root layout:
//
//   import { fontVariables } from "@/styles/next-fonts";
//   <html lang="en" className={fontVariables}>
//
// Each loader sets one CSS variable on <html>. tokens/house-tailwind.css
// reads Geist into --font-sans, Space Grotesk into --font-display,
// Monaspace Neon into --font-mono, and Space Grotesk into --font-wordmark.
//
// Aeonik, Aeonik Mono and Aeonik Fono load too, with preload off, so a page
// pays for one only when it names the family. No role token reads them yet.

import localFont from "next/font/local";

/** Space Grotesk: the oxagen and stella wordmarks and Stella's asterisk, set as text. It is fixed. It also sets h1 to h3 on a marketing or customer site. */
export const spaceGrotesk = localFont({
  src: [
    { path: "../fonts/space-grotesk-latin-400.woff2", weight: "400", style: "normal" },
    { path: "../fonts/space-grotesk-latin-500.woff2", weight: "500", style: "normal" },
    { path: "../fonts/space-grotesk-latin-600.woff2", weight: "600", style: "normal" },
    { path: "../fonts/space-grotesk-latin-700.woff2", weight: "700", style: "normal" },
  ],
  variable: "--font-space-grotesk",
  display: "swap",
  fallback: ["Helvetica Neue", "Arial"],
});

/** Geist: body, labels, buttons, tables, navigation, every app heading, and every h4 to h6. */
export const geist = localFont({
  src: "../fonts/geist-latin-wght.woff2",
  weight: "100 900",
  variable: "--font-geist",
  display: "swap",
  fallback: ["system-ui", "-apple-system", "Segoe UI"],
});

/** Monaspace Neon: code, terminal output, logs, digests, paths, ids, and numbers in tables. */
export const monaspaceNeon = localFont({
  src: "../fonts/monaspace-neon-latin-wght.woff2",
  weight: "200 800",
  variable: "--font-monaspace-neon",
  display: "swap",
  fallback: ["SF Mono", "Menlo", "Consolas"],
  adjustFontFallback: false,
});

/** Aeonik: loads for a page that names it. No role reads it yet. */
export const aeonik = localFont({
  src: [
    { path: "../fonts/aeonik-wght.woff2", weight: "100 900", style: "normal" },
    { path: "../fonts/aeonik-italic-wght.woff2", weight: "100 900", style: "italic" },
  ],
  variable: "--font-aeonik",
  display: "swap",
  fallback: ["system-ui", "-apple-system", "Segoe UI"],
  preload: false,
});

/** Aeonik Mono: loads for a page that names it. No role reads it yet. */
export const aeonikMono = localFont({
  src: "../fonts/aeonik-mono-wght.woff2",
  weight: "100 900",
  variable: "--font-aeonik-mono",
  display: "swap",
  fallback: ["SF Mono", "Menlo", "Consolas"],
  adjustFontFallback: false,
  preload: false,
});

/** Aeonik Fono: loads for a page that names it. No role reads it yet. */
export const aeonikFono = localFont({
  src: "../fonts/aeonik-fono-wght.woff2",
  weight: "100 900",
  variable: "--font-aeonik-fono",
  display: "swap",
  fallback: ["SF Mono", "Menlo", "Consolas"],
  adjustFontFallback: false,
  preload: false,
});

/** Every variable, for the <html> className. */
export const fontVariables = [spaceGrotesk.variable, geist.variable, monaspaceNeon.variable, aeonik.variable, aeonikMono.variable, aeonikFono.variable].join(" ");
