//! `stella migrate config` — write the `stella.toml` equivalent of an existing
//! `settings.json`.
//!
//! # What this does NOT do
//!
//! It never deletes the JSON. The user removes it once satisfied, and until
//! they do, [`Settings::load`] announces that the JSON is being shadowed. A
//! migration that deleted its own input would make "check the diff, then
//! commit" impossible for the one file most likely to carry an org's authority
//! ceiling.
//!
//! # Where the values come from
//!
//! Every emitted value is serialized from the parsed [`Settings`] — never
//! transcribed. Drafting the reference config by hand, seven of ten
//! `[context.retrieval]` defaults came out wrong (plausible round numbers
//! instead of the real constants). A documented-defaults file is a second copy
//! of every default in the system, and second copies drift silently, so the
//! only safe generator is one that cannot hold an opinion about a value.
//!
//! The COMMENTS are static prose about the schema, which is the one thing that
//! cannot drift from a value it never states.

use std::path::{Path, PathBuf};

use super::toml_config::{self, CURRENT_SCHEMA_VERSION, ConfigScope};
use super::{Settings, toml_io};

/// One scope's migration outcome, for the report.
#[derive(Debug)]
pub enum Outcome {
    /// No `settings.json` at this scope — nothing to do.
    NothingToDo,
    /// A `stella.toml` already exists; refused rather than overwriting.
    AlreadyMigrated(PathBuf),
    /// Written (or, under `--dry-run`, would be).
    Written { from: PathBuf, to: PathBuf },
}

/// Render `settings` as a commented `stella.toml` document.
///
/// Built by writing sections into an empty `toml_edit` document and then
/// prefixing the header, so the output goes through the same writer that will
/// later edit it — a migration that produced a file its own editor could not
/// round-trip would be a trap.
pub fn render(settings: &Settings, scope: ConfigScope) -> Result<String, String> {
    let mut doc = toml_edit::DocumentMut::new();

    let mut meta = toml_edit::Table::new();
    meta.insert(
        "schema_version",
        toml_edit::value(i64::from(CURRENT_SCHEMA_VERSION)),
    );
    meta.insert("scope", toml_edit::value(scope.label()));
    meta.set_implicit(false);
    doc["meta"] = toml_edit::Item::Table(meta);

    if let Some(recap) = settings.enable_recap {
        let mut run = toml_edit::Table::new();
        run.insert(
            "recap",
            toml_edit::value(if recap.is_on() { "on" } else { "off" }),
        );
        run.set_implicit(false);
        doc["run"] = toml_edit::Item::Table(run);
    }

    if !settings.providers.is_empty() {
        doc["providers"] = toml_io::item_for(&settings.providers, "providers")?;
    }
    if let Some(engine) = &settings.agent_engine_config {
        for (key, item) in toml_config::agent_sections(engine)? {
            if let Some(item) = item {
                doc[key] = item;
            }
        }
    }
    if let Some(tools) = &settings.tools
        && !tools.entries.is_empty()
    {
        doc["tools"] = toml_io::item_for(tools, "tools")?;
    }
    if let Some(hooks) = &settings.hooks {
        doc["hooks"] = toml_io::item_for(hooks, "hooks")?;
    }
    if let Some(mcp) = &settings.mcp
        && mcp.registry_url.is_some()
    {
        doc["mcp"] = toml_io::item_for(mcp, "mcp")?;
    }
    if let Some(context) = &settings.context {
        doc["context"] = toml_io::item_for(context, "context")?;
    }
    if !settings.context_providers.is_empty() {
        doc["context_providers"] =
            toml_io::item_for(&settings.context_providers, "context_providers")?;
    }
    if let Some(ui) = &settings.ui
        && ui.theme.is_some()
    {
        doc["ui"] = toml_io::item_for(ui, "ui")?;
    }
    if let Some(authority) = &settings.managed_authority {
        doc["authority"] = toml_io::item_for(authority, "authority")?;
    }

    Ok(format!("{}{doc}", header(scope)))
}

fn header(scope: ConfigScope) -> String {
    let located = match scope {
        ConfigScope::User => "~/.stella/stella.toml — your machine, every project.",
        ConfigScope::Managed => {
            "the administrator-managed config. Its LOCATION is what grants it authority."
        }
        ConfigScope::Project => {
            "<repo>/stella.toml — this repository. Commit it; it is reviewed like source."
        }
    };
    format!(
        "# stella.toml — generated by `stella migrate config`.\n\
         #\n\
         # {located}\n\
         #\n\
         # Values were serialized from the settings.json beside it, not\n\
         # transcribed, so nothing here can disagree with what stella read.\n\
         # Comments you add below survive every future write.\n\
         #\n\
         # The original settings.json was NOT deleted. Check this file, then\n\
         # remove the JSON — until you do, stella reads this one and says so.\n\
         #\n\
         # Full reference: docs/design/config-system/stella.today.toml\n\n"
    )
}

/// Migrate one scope. `dry_run` renders and reports without writing.
pub fn migrate_scope(
    json_path: &Path,
    toml_path: &Path,
    scope: ConfigScope,
    dry_run: bool,
) -> Result<Outcome, String> {
    if !json_path.exists() {
        return Ok(Outcome::NothingToDo);
    }
    if toml_path.exists() {
        return Ok(Outcome::AlreadyMigrated(toml_path.to_path_buf()));
    }
    // The scope's OWN contents, not a merge — a migration must reproduce
    // this file, not the chain it happens to sit in.
    let settings = Settings::load_scope(json_path)?;
    let rendered = render(&settings, scope)?;

    // Parse what we just produced before writing it. A migration that emits a
    // file stella cannot read would be discovered on the user's NEXT launch,
    // with their working config already shadowed by the broken one.
    let reparsed = toml_config::TomlConfig::parse(&rendered, toml_path)?;
    reparsed.validate_meta(toml_path, scope)?;
    // A project-scope `stella.toml` lives at the repo root and is committed, so
    // the loader refuses an inline `api_key` there. Apply the SAME rule before
    // writing: `render` serializes `providers` verbatim, so without this a key
    // sitting in `.stella/settings.json` would be copied into the committed
    // file — leaking it — and produce a config stella then refuses to load.
    //
    // The refusal happens BEFORE `write_settings`, so the secret never reaches
    // disk. The loader's message names `toml_path`, which does not exist yet at
    // this point, so name the file the secret is actually in — that is the one
    // the user has to edit. Scoped to THIS file rather than "nothing was
    // written", because `run` migrates the user scope first and has already
    // printed what it wrote by the time the project scope is refused.
    reparsed
        .validate_project_secrets(toml_path, scope)
        .map_err(|err| {
            format!(
                "{err}\nThe key is in {} — move it out of that file, then re-run \
                 `stella migrate config`. {} was not written.",
                json_path.display(),
                toml_path.display()
            )
        })?;

    if !dry_run {
        let user_private = scope == ConfigScope::User;
        super::private::write_settings(toml_path, rendered.as_bytes(), user_private)?;
    }
    Ok(Outcome::Written {
        from: json_path.to_path_buf(),
        to: toml_path.to_path_buf(),
    })
}

/// `stella migrate config` — migrate the user and project scopes.
///
/// The managed scope is deliberately NOT migrated: it is administrator-owned,
/// lives outside the user's home, and its hardened reader requires an
/// ownership and mode the CLI has no business establishing on someone else's
/// behalf. An operator deploying it writes it directly.
pub fn run(workspace_root: &Path, dry_run: bool) -> Result<(), String> {
    let mut any = false;

    let scopes: Vec<(ConfigScope, Option<PathBuf>, Option<PathBuf>)> = vec![
        (
            ConfigScope::User,
            super::user_settings_path(),
            toml_config::user_toml_path(),
        ),
        (
            ConfigScope::Project,
            Some(super::project_settings_path(workspace_root)),
            Some(toml_config::project_toml_path(workspace_root)),
        ),
    ];

    for (scope, json, toml) in scopes {
        let (Some(json), Some(toml)) = (json, toml) else {
            continue;
        };
        match migrate_scope(&json, &toml, scope, dry_run)? {
            Outcome::NothingToDo => {}
            Outcome::AlreadyMigrated(path) => {
                any = true;
                println!(
                    "  {} scope: {} already exists — left untouched.",
                    scope.label(),
                    path.display()
                );
            }
            Outcome::Written { from, to } => {
                any = true;
                let verb = if dry_run { "would write" } else { "wrote" };
                println!(
                    "  {} scope: {verb} {}\n            from {}",
                    scope.label(),
                    to.display(),
                    from.display()
                );
            }
        }
    }

    if !any {
        println!("  no settings.json found at either scope — nothing to migrate.");
        return Ok(());
    }
    if dry_run {
        println!("\n  --dry-run: nothing was written.");
    } else {
        println!(
            "\n  The settings.json files were kept. Review the TOML, then delete them.\n  \
             Until you do, stella reads the TOML and warns that the JSON is shadowed."
        );
    }
    Ok(())
}
