// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (c) 2026 Oxagen, Inc. Commercial licensing: licensing@oxagen.sh

//! Applying and reverting a `[[configure]]` table, over a real `stella.toml`.
//!
//! These drive the write path against a temporary workspace root rather than
//! the process's cwd, so nothing here reads or writes the developer's own
//! configuration — `plugin_cmd::tests`' rule, and it matters more here because
//! this module writes a file a developer has.

use std::path::{Path, PathBuf};

use super::*;

/// The motivating package: a distribution overriding how stella signs its
/// work.
fn manifest(entries: &str) -> PluginManifest {
    PluginManifest::from_toml_str(&format!("name = \"oxagen\"\n\n{entries}"))
        .expect("fixture manifest must load")
}

/// The #3999 acceptance declaration, verbatim from the issue's own example.
fn attribution_manifest() -> PluginManifest {
    manifest(
        "[[configure]]\n\
         key = \"self_driving.attribution.commit\"\n\
         value = \"Generated by Oxagen\"\n\
         purpose = \"sign this workspace's commits in the distribution's name\"\n",
    )
}

fn temp_root(label: &str) -> PathBuf {
    let root = std::env::temp_dir().join(format!(
        "stella-configure-{label}-{}-{:?}",
        std::process::id(),
        std::thread::current().id()
    ));
    let _ = std::fs::remove_dir_all(&root);
    std::fs::create_dir_all(&root).expect("temp root");
    root
}

/// A target pointed straight at a file, bypassing tier resolution — which is
/// tested on its own below and needs `crate::paths` for the user tier.
fn target_at(path: &Path) -> ConfigTarget {
    ConfigTarget {
        path: path.to_path_buf(),
    }
}

/// Run the whole install-time sequence the way `plugin_cmd::install` does:
/// plan, journal, commit.
fn install(target: &ConfigTarget, manifest: &PluginManifest, plugin_dir: &Path) -> ConfigJournal {
    std::fs::create_dir_all(plugin_dir).expect("plugin dir");
    let plan = plan(target, manifest).expect("planning must succeed");
    write_journal(plugin_dir, &plan.journal).expect("journal must be writable");
    plan.commit().expect("commit must succeed");
    plan.journal
}

/// **Witness for #3999, the acceptance criterion.** A plugin declares an
/// attribution override, install applies it, and removal restores what was
/// there before — including the case the issue is really about, where "what
/// was there before" is nothing at all.
#[test]
fn install_applies_the_declared_value_and_removal_puts_the_workspace_back() {
    let root = temp_root("roundtrip");
    let config = root.join("stella.toml");
    let before = "# a comment the user wrote\n[agents]\ndefault_model = \"x\"\n";
    std::fs::write(&config, before).expect("seed config");
    let plugin_dir = root.join("plugins").join("oxagen");
    let manifest = attribution_manifest();

    install(&target_at(&config), &manifest, &plugin_dir);

    let after = std::fs::read_to_string(&config).expect("read back");
    assert!(
        after.contains(r#"commit = "Generated by Oxagen""#),
        "the declared value landed:\n{after}"
    );
    assert!(
        after.contains("[self_driving.attribution]"),
        "written as a real table:\n{after}"
    );

    // The half that makes this the issue's criterion rather than a file-write
    // test: the loop's own reader sees the plugin's value. A key written to
    // the right path that nothing reads would pass every assertion above.
    assert_eq!(
        crate::self_driving_cmd::config::load(&root)
            .attribution
            .commit,
        "Generated by Oxagen",
        "the self-driving loop reads what the package configured"
    );

    let reverted = revert(&plugin_dir, &manifest);
    assert_eq!(reverted.keys, ["self_driving.attribution.commit"]);
    assert!(reverted.unaccounted.is_empty(), "{reverted:?}");
    assert_eq!(
        std::fs::read_to_string(&config).expect("read back"),
        before,
        "removal restores the file byte for byte, table header included"
    );
    // ...and the loop is back to signing in its own name.
    assert_eq!(
        crate::self_driving_cmd::config::load(&root)
            .attribution
            .commit,
        stella_autonomy::Attribution::default().commit,
        "removing the package puts the loop's identity back"
    );
}

/// The other half of "what was there before": a key that already held a value
/// is restored to *that* value, not to a default and not to absent.
#[test]
fn a_key_that_held_a_value_is_restored_to_it() {
    let root = temp_root("prior");
    let config = root.join("stella.toml");
    std::fs::write(&config, "[self_driving.attribution]\ncommit = \"mine\"\n")
        .expect("seed config");
    let plugin_dir = root.join("oxagen");
    let manifest = attribution_manifest();

    let journal = install(&target_at(&config), &manifest, &plugin_dir);
    assert_eq!(
        journal.prior[0].value.as_deref(),
        Some("\"mine\""),
        "the prior value is recorded as its literal TOML text"
    );
    assert!(
        journal.prior[0].created.is_none(),
        "no table was created, so none is removed on revert"
    );
    assert!(
        std::fs::read_to_string(&config)
            .unwrap()
            .contains(r#""Generated by Oxagen""#)
    );

    revert(&plugin_dir, &manifest);
    let after = std::fs::read_to_string(&config).expect("read back");
    assert!(after.contains(r#"commit = "mine""#), "{after}");
    assert!(!after.contains("Oxagen"), "{after}");
}

/// Comments, ordering and every untouched key survive the write — the
/// `settings::toml_io` contract, which this module writes through the same
/// file as and would otherwise be free to break.
#[test]
fn a_configure_write_preserves_comments_and_untouched_keys() {
    let root = temp_root("comments");
    let config = root.join("stella.toml");
    std::fs::write(
        &config,
        "# banner\n[meta]\nschema_version = 1\n\n# why this model\n[agents]\n\
         default_model = \"x\"  # trailing\n\n[ui]\ntheme = \"dark\"\n",
    )
    .expect("seed config");
    let plugin_dir = root.join("oxagen");

    install(&target_at(&config), &attribution_manifest(), &plugin_dir);

    let after = std::fs::read_to_string(&config).expect("read back");
    for fragment in [
        "# banner",
        "# why this model",
        "# trailing",
        "schema_version = 1",
        r#"theme = "dark""#,
    ] {
        assert!(after.contains(fragment), "{fragment} survives:\n{after}");
    }
    assert!(
        after.find("[meta]").unwrap() < after.find("[agents]").unwrap(),
        "key order survives:\n{after}"
    );
}

/// **The bound on a planted journal.** The keys come from the manifest — the
/// list a human consented to — so a journal naming anything else is inert.
/// Without this, `stella plugin remove` would be a primitive for rewriting
/// arbitrary configuration out of a file a package controls.
#[test]
fn a_journal_naming_an_undeclared_key_cannot_change_it() {
    let root = temp_root("planted");
    let config = root.join("stella.toml");
    std::fs::write(&config, "[agents]\ndefault_model = \"mine\"\n").expect("seed config");
    let plugin_dir = root.join("oxagen");
    let manifest = attribution_manifest();

    install(&target_at(&config), &manifest, &plugin_dir);

    // A journal that also claims authority over a key the manifest never
    // declared, as a hostile package would plant it.
    let mut planted: ConfigJournal =
        serde_json::from_str(&std::fs::read_to_string(plugin_dir.join(REVERT_FILE)).unwrap())
            .expect("journal parses");
    planted.prior.push(PriorValue {
        key: "agents.default_model".into(),
        value: Some("\"hijacked\"".into()),
        created: None,
    });
    std::fs::write(
        plugin_dir.join(REVERT_FILE),
        serde_json::to_string(&planted).unwrap(),
    )
    .expect("plant it");

    let reverted = revert(&plugin_dir, &manifest);
    assert_eq!(
        reverted.keys,
        ["self_driving.attribution.commit"],
        "only the declared key is touched"
    );
    let after = std::fs::read_to_string(&config).expect("read back");
    assert!(after.contains(r#"default_model = "mine""#), "{after}");
    assert!(!after.contains("hijacked"), "{after}");
}

/// A journal belonging to another package is not replayed, and the keys it
/// would have restored are reported as unaccounted rather than silently
/// dropped — a `remove` that claimed success while leaving configuration in
/// force is the failure this mechanism exists to prevent.
#[test]
fn a_missing_or_foreign_journal_is_reported_not_swallowed() {
    let root = temp_root("foreign");
    let plugin_dir = root.join("oxagen");
    std::fs::create_dir_all(&plugin_dir).expect("plugin dir");
    let manifest = attribution_manifest();

    let reverted = revert(&plugin_dir, &manifest);
    assert!(reverted.keys.is_empty());
    assert_eq!(reverted.unaccounted, ["self_driving.attribution.commit"]);
    assert!(reverted.config.is_none(), "nothing was written");

    let foreign = ConfigJournal {
        plugin: "somebody-else".into(),
        config: root.join("stella.toml"),
        prior: vec![PriorValue {
            key: "self_driving.attribution.commit".into(),
            value: None,
            created: None,
        }],
    };
    std::fs::write(
        plugin_dir.join(REVERT_FILE),
        serde_json::to_string(&foreign).unwrap(),
    )
    .expect("plant it");
    let reverted = revert(&plugin_dir, &manifest);
    assert_eq!(reverted.unaccounted, ["self_driving.attribution.commit"]);
}

/// A package that configures nothing writes nothing and reports nothing, so
/// the overwhelming majority of installs are unchanged by all of this.
#[test]
fn a_package_that_configures_nothing_is_silent() {
    let root = temp_root("silent");
    let plugin_dir = root.join("plain");
    std::fs::create_dir_all(&plugin_dir).expect("plugin dir");
    let manifest = PluginManifest::from_toml_str("name = \"plain\"").expect("fixture");
    let reverted = revert(&plugin_dir, &manifest);
    assert!(reverted.keys.is_empty() && reverted.unaccounted.is_empty());
}

/// A tier still on `settings.json` is refused rather than migrated behind the
/// user's back: creating `stella.toml` beside it would take precedence over
/// the whole file and silently disable every setting in it.
#[test]
fn a_json_only_workspace_is_refused_with_the_reason() {
    let root = temp_root("json-only");
    std::fs::create_dir_all(root.join(".stella")).expect("dot dir");
    std::fs::write(root.join(".stella").join("settings.json"), "{}").expect("seed json");

    let err = ConfigTarget::resolve(&root, PluginScope::Project)
        .expect_err("a JSON-only workspace must be refused");
    assert!(err.contains("settings.json"), "{err}");
    assert!(err.contains("silently disable"), "{err}");
    assert!(err.contains("stella migrate config"), "{err}");

    // ...and a workspace that has migrated is accepted.
    std::fs::write(root.join("stella.toml"), "[meta]\nschema_version = 1\n").expect("seed toml");
    ConfigTarget::resolve(&root, PluginScope::Project).expect("a migrated workspace is writable");
}

/// A key whose ancestor is an existing scalar is refused, not overwritten.
///
/// The revert contract is what forces this: the journal records the value at
/// the *leaf*, and there is no leaf under `self_driving = 1` to record — so
/// clobbering it would be a destructive change with nothing able to undo it.
/// Refused during `plan`, which writes nothing, so the file is untouched.
#[test]
fn a_key_whose_ancestor_is_a_value_is_refused_before_anything_is_written() {
    let root = temp_root("scalar-ancestor");
    let config = root.join("stella.toml");
    let before = "self_driving = 1\n";
    std::fs::write(&config, before).expect("seed config");

    let err = plan(&target_at(&config), &attribution_manifest())
        .expect_err("a scalar ancestor must be refused");
    assert!(err.contains("self_driving"), "{err}");
    assert!(err.contains("could not undo"), "{err}");
    assert_eq!(
        std::fs::read_to_string(&config).expect("read back"),
        before,
        "planning writes nothing, so the refusal costs the file nothing"
    );
}

/// A workspace with neither file is writable: there is no JSON to shadow, so
/// the package's keys create the config it did not have.
#[test]
fn a_workspace_with_no_config_at_all_is_writable() {
    let root = temp_root("greenfield");
    let target =
        ConfigTarget::resolve(&root, PluginScope::Project).expect("nothing to shadow, so writable");
    let plugin_dir = root.join("oxagen");
    install(&target, &attribution_manifest(), &plugin_dir);
    assert!(
        std::fs::read_to_string(root.join("stella.toml"))
            .unwrap()
            .contains("Generated by Oxagen")
    );
}
