-- Durable store for Terminal-Bench head-to-head runs.
--
-- Written to be valid on BOTH SQLite and PostgreSQL, because the local copy is
-- the working set and the Postgres copy is the durable one, and a schema that
-- drifts between them stops being a mirror. That rules out a few conveniences:
-- no AUTOINCREMENT (Postgres spells it differently), no BOOLEAN literals
-- (SQLite has no such type — integers 0/1), no JSONB (SQLite has TEXT).
-- Identifiers are supplied by the ingester rather than generated by the engine.
--
-- What is deliberately NOT stored: raw artifact bytes. One 89-task run is
-- ~900 MB, and nearly all of it is per-token streaming deltas — one JSON
-- object per fragment of reasoning. Those answer no question anyone asks
-- twice. `artifacts` records every file's path, size and SHA-256 instead, so
-- the bytes stay findable and verifiable while the database stays small enough
-- to mirror.
--
-- The unit of truth is the TRIAL. A run is a bag of trials; a comparison is a
-- join of two arms over `task_name`. Nothing here stores a derived verdict:
-- pass/fail is `reward >= 1` from the benchmark's own grader, recorded raw so
-- a later reader can re-derive it rather than trust it.

CREATE TABLE IF NOT EXISTS runs (
    run_id            TEXT PRIMARY KEY,
    tag               TEXT NOT NULL,
    -- 'scored' or 'smoke'. A smoke is unregistered by design and must never be
    -- mistaken for evidence.
    kind              TEXT NOT NULL,
    -- Non-null when a run was invalidated AFTER the fact, with the reason.
    -- Voided runs are kept, not deleted: the record of what went wrong is the
    -- only thing that stops it recurring.
    void_reason       TEXT,
    model             TEXT NOT NULL,
    api_surface       TEXT,
    dataset_digest    TEXT,
    sut_commit        TEXT,
    binary_sha256     TEXT,
    taskset_sha256    TEXT,
    task_count        INTEGER,
    -- The pre-registration as registered, verbatim, and the preflight output
    -- that licensed the launch. Both are evidence and neither is regenerable.
    prereg_json       TEXT,
    preflight_text    TEXT,
    started_at        TEXT,
    finished_at       TEXT,
    ingested_at       TEXT NOT NULL,
    notes             TEXT
);

CREATE TABLE IF NOT EXISTS trials (
    trial_id          TEXT PRIMARY KEY,
    run_id            TEXT NOT NULL REFERENCES runs(run_id) ON DELETE CASCADE,
    arm               TEXT NOT NULL,          -- 'stella' | 'claude-code'
    agent             TEXT NOT NULL,
    task_name         TEXT NOT NULL,          -- suffix stripped; the join key
    trial_dir         TEXT NOT NULL,          -- suffixed dir as it exists on disk
    -- Raw grader output. `passed` is derived at ingest for convenience but the
    -- reward is kept so the derivation can be checked.
    reward            REAL,
    passed            INTEGER,
    exception_type    TEXT,
    exception_message TEXT,
    n_input_tokens    INTEGER,
    n_cache_tokens    INTEGER,
    n_output_tokens   INTEGER,
    -- Self-reported by the agent. NOT comparable across arms: two harnesses
    -- price the same tokens off different tables, which is how a 5x gap
    -- appeared between arms on one model. Kept because it is the only figure
    -- reconcilable against that arm's own invoice.
    cost_usd_self     REAL,
    -- Recomputed from token counts and one price table applied to both arms.
    -- This is the comparable one. Populated AT INGEST, not deferred: the
    -- ingester holds every input the computation needs (token counts, the
    -- model the trial ran, the day it ran on), and when this column was
    -- inserted as a placeholder NULL "for the analysis step" nothing ever
    -- filled it -- so a reader who summed it got 0.00 and published that as
    -- the normalized cost.
    cost_usd_norm     REAL,
    -- Why cost_usd_norm is or is not populated, so an absent figure can never
    -- be mistaken for a computed zero. One of: 'priced' (the ONLY state in
    -- which cost_usd_norm means anything -- and in it, a genuine $0.00 is a
    -- real measurement), 'no_model', 'unpriced_model', 'no_tokens',
    -- 'no_run_date', or 'unmigrated' for rows written before this column
    -- existed. Any query that aggregates cost_usd_norm must filter on this.
    cost_norm_status  TEXT NOT NULL DEFAULT 'unmigrated',
    wall_seconds      REAL,
    started_at        TEXT,
    finished_at       TEXT
);

CREATE INDEX IF NOT EXISTS trials_run_idx  ON trials(run_id);
CREATE INDEX IF NOT EXISTS trials_task_idx ON trials(task_name);
CREATE INDEX IF NOT EXISTS trials_arm_idx  ON trials(run_id, arm);

-- Structural events only. Streaming text/reasoning deltas are dropped at
-- ingest: they are ~99% of the volume and carry no answerable question.
CREATE TABLE IF NOT EXISTS events (
    event_id          TEXT PRIMARY KEY,
    trial_id          TEXT NOT NULL REFERENCES trials(trial_id) ON DELETE CASCADE,
    seq               INTEGER NOT NULL,
    type              TEXT NOT NULL,
    payload_json      TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS events_trial_idx ON events(trial_id, seq);
CREATE INDEX IF NOT EXISTS events_type_idx  ON events(trial_id, type);

-- Denormalized from `events` so "how many bash calls" is one scan rather than
-- a JSON extract across dialects. Both arms populate it where their telemetry
-- allows; an arm whose format hides tool calls simply has no rows, which is
-- visibly different from having zero calls.
CREATE TABLE IF NOT EXISTS tool_calls (
    id                TEXT PRIMARY KEY,
    trial_id          TEXT NOT NULL REFERENCES trials(trial_id) ON DELETE CASCADE,
    seq               INTEGER NOT NULL,
    tool              TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS tool_calls_trial_idx ON tool_calls(trial_id);
CREATE INDEX IF NOT EXISTS tool_calls_tool_idx  ON tool_calls(tool);

-- The grader's own per-test detail, from the verifier's CTRF report. This is
-- what makes a "fail" inspectable: which assertions failed, not merely that
-- reward was 0.
CREATE TABLE IF NOT EXISTS verifier_tests (
    id                TEXT PRIMARY KEY,
    trial_id          TEXT NOT NULL REFERENCES trials(trial_id) ON DELETE CASCADE,
    name              TEXT NOT NULL,
    status            TEXT,
    duration_ms       INTEGER,
    message           TEXT
);

CREATE INDEX IF NOT EXISTS verifier_tests_trial_idx ON verifier_tests(trial_id);

-- Provenance for what was NOT ingested. Every artifact on disk gets a row, so
-- the raw bytes remain locatable and checkable long after the database has
-- outlived the machine that produced them.
CREATE TABLE IF NOT EXISTS artifacts (
    id                TEXT PRIMARY KEY,
    trial_id          TEXT NOT NULL REFERENCES trials(trial_id) ON DELETE CASCADE,
    kind              TEXT NOT NULL,
    rel_path          TEXT NOT NULL,
    bytes             INTEGER NOT NULL,
    sha256            TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS artifacts_trial_idx ON artifacts(trial_id);
