-- Durable store for Terminal-Bench head-to-head runs.
--
-- Written to be valid on BOTH SQLite and PostgreSQL, because the local copy is
-- the working set and the Postgres copy is the durable one, and a schema that
-- drifts between them stops being a mirror. That rules out a few conveniences:
-- no AUTOINCREMENT (Postgres spells it differently), no BOOLEAN literals
-- (SQLite has no such type — integers 0/1), no JSONB (SQLite has TEXT).
-- Identifiers are supplied by the ingester rather than generated by the engine.
--
-- What is deliberately NOT stored: raw artifact bytes. One 89-task run is
-- ~900 MB, and nearly all of it is per-token streaming deltas — one JSON
-- object per fragment of reasoning. Those answer no question anyone asks
-- twice. `artifacts` records every file's path, size and SHA-256 instead, so
-- the bytes stay findable and verifiable while the database stays small enough
-- to mirror.
--
-- The unit of truth is the TRIAL. A run is a bag of trials; a comparison is a
-- join of two arms over `task_name`. Nothing here stores a derived verdict:
-- pass/fail is `reward >= 1` from the benchmark's own grader, recorded raw so
-- a later reader can re-derive it rather than trust it.

CREATE TABLE IF NOT EXISTS runs (
    run_id            TEXT PRIMARY KEY,
    tag               TEXT NOT NULL,
    -- 'scored' or 'smoke'. A smoke is unregistered by design and must never be
    -- mistaken for evidence.
    kind              TEXT NOT NULL,
    -- Non-null when a run was invalidated AFTER the fact, with the reason.
    -- Voided runs are kept, not deleted: the record of what went wrong is the
    -- only thing that stops it recurring.
    void_reason       TEXT,
    model             TEXT NOT NULL,
    api_surface       TEXT,
    dataset_digest    TEXT,
    sut_commit        TEXT,
    binary_sha256     TEXT,
    taskset_sha256    TEXT,
    task_count        INTEGER,
    -- The pre-registration as registered, verbatim, and the preflight output
    -- that licensed the launch. Both are evidence and neither is regenerable.
    prereg_json       TEXT,
    preflight_text    TEXT,
    started_at        TEXT,
    finished_at       TEXT,
    ingested_at       TEXT NOT NULL,
    notes             TEXT,
    -- Mirror provenance. When a run is copied from a working-set database
    -- into the durable one, `migrated` flips to 1 and `migration_source`
    -- records the machine@tier label the copy came from (`Mac@local`), so
    -- the durable copy can always answer which machine produced a row.
    -- 0/NULL on rows written in place. Declared last so a database that
    -- gains them through ingest.py's ALTER TABLE migration ends up with
    -- the same column order as one created fresh.
    migrated          INTEGER NOT NULL DEFAULT 0,
    migration_source  TEXT
);

CREATE TABLE IF NOT EXISTS trials (
    trial_id          TEXT PRIMARY KEY,
    run_id            TEXT NOT NULL REFERENCES runs(run_id) ON DELETE CASCADE,
    arm               TEXT NOT NULL,          -- 'stella' | 'claude-code'
    agent             TEXT NOT NULL,
    task_name         TEXT NOT NULL,          -- suffix stripped; the join key
    trial_dir         TEXT NOT NULL,          -- suffixed dir as it exists on disk
    -- Raw grader output. `passed` is derived at ingest for convenience but the
    -- reward is kept so the derivation can be checked.
    reward            REAL,
    passed            INTEGER,
    exception_type    TEXT,
    exception_message TEXT,
    n_input_tokens    INTEGER,
    n_cache_tokens    INTEGER,
    n_output_tokens   INTEGER,
    -- Self-reported by the agent. NOT comparable across arms: two harnesses
    -- price the same tokens off different tables, which is how a 5x gap
    -- appeared between arms on one model. Kept because it is the only figure
    -- reconcilable against that arm's own invoice.
    cost_usd_self     REAL,
    -- Recomputed from token counts and one price table applied to both arms.
    -- This is the comparable one. Populated AT INGEST, not deferred: the
    -- ingester holds every input the computation needs (token counts, the
    -- model the trial ran, the day it ran on), and when this column was
    -- inserted as a placeholder NULL "for the analysis step" nothing ever
    -- filled it -- so a reader who summed it got 0.00 and published that as
    -- the normalized cost.
    cost_usd_norm     REAL,
    -- Why cost_usd_norm is or is not populated, so an absent figure can never
    -- be mistaken for a computed zero. One of: 'priced' (the ONLY state in
    -- which cost_usd_norm means anything -- and in it, a genuine $0.00 is a
    -- real measurement), 'no_model', 'unpriced_model', 'no_tokens',
    -- 'no_run_date', or 'unmigrated' for rows written before this column
    -- existed. Any query that aggregates cost_usd_norm must filter on this.
    cost_norm_status  TEXT NOT NULL DEFAULT 'unmigrated',
    wall_seconds      REAL,
    started_at        TEXT,
    finished_at       TEXT
);

CREATE INDEX IF NOT EXISTS trials_run_idx  ON trials(run_id);
CREATE INDEX IF NOT EXISTS trials_task_idx ON trials(task_name);
CREATE INDEX IF NOT EXISTS trials_arm_idx  ON trials(run_id, arm);

-- Structural events only. Streaming text/reasoning deltas are dropped at
-- ingest: they are ~99% of the volume and carry no answerable question.
CREATE TABLE IF NOT EXISTS events (
    event_id          TEXT PRIMARY KEY,
    trial_id          TEXT NOT NULL REFERENCES trials(trial_id) ON DELETE CASCADE,
    seq               INTEGER NOT NULL,
    type              TEXT NOT NULL,
    payload_json      TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS events_trial_idx ON events(trial_id, seq);
CREATE INDEX IF NOT EXISTS events_type_idx  ON events(trial_id, type);

-- Denormalized from `events` so "how many bash calls" is one scan rather than
-- a JSON extract across dialects. Both arms populate it where their telemetry
-- allows; an arm whose format hides tool calls simply has no rows, which is
-- visibly different from having zero calls.
CREATE TABLE IF NOT EXISTS tool_calls (
    id                TEXT PRIMARY KEY,
    trial_id          TEXT NOT NULL REFERENCES trials(trial_id) ON DELETE CASCADE,
    seq               INTEGER NOT NULL,
    tool              TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS tool_calls_trial_idx ON tool_calls(trial_id);
CREATE INDEX IF NOT EXISTS tool_calls_tool_idx  ON tool_calls(tool);

-- The grader's own per-test detail, from the verifier's CTRF report. This is
-- what makes a "fail" inspectable: which assertions failed, not merely that
-- reward was 0.
CREATE TABLE IF NOT EXISTS verifier_tests (
    id                TEXT PRIMARY KEY,
    trial_id          TEXT NOT NULL REFERENCES trials(trial_id) ON DELETE CASCADE,
    name              TEXT NOT NULL,
    status            TEXT,
    duration_ms       INTEGER,
    message           TEXT
);

CREATE INDEX IF NOT EXISTS verifier_tests_trial_idx ON verifier_tests(trial_id);

-- Provenance for what was NOT ingested. Every artifact on disk gets a row, so
-- the raw bytes remain locatable and checkable long after the database has
-- outlived the machine that produced them.
CREATE TABLE IF NOT EXISTS artifacts (
    id                TEXT PRIMARY KEY,
    trial_id          TEXT NOT NULL REFERENCES trials(trial_id) ON DELETE CASCADE,
    kind              TEXT NOT NULL,
    rel_path          TEXT NOT NULL,
    bytes             INTEGER NOT NULL,
    sha256            TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS artifacts_trial_idx ON artifacts(trial_id);

-- Step/turn/execution grading (docs/designs/step-grading-and-productive-ratio.md).
-- A second pass over the tables above, run after ingest rather than during
-- it: nothing here is raw fact `events`/`tool_calls`/`verifier_tests` don't
-- already hold, and every `*_grades` row must be reproducible by re-running
-- the grader against them. Like `trials.cost_usd_norm`, a grade is versioned
-- rather than overwritten -- `grader_version` lets an improved ruleset add a
-- new row set beside the old one instead of erasing what the old ruleset saw.

-- One row per graded step-window: the span covered by one model call for one
-- (trial, turn_instance, step, call_index). `call_index` disambiguates
-- auxiliary calls sharing a step the same way the wire's own `StepManifest`
-- key does (the worker call is 0; triage/plan/verifier/compaction calls
-- riding the same step take 1, 2, ...).
CREATE TABLE IF NOT EXISTS step_grades (
    step_grade_id     TEXT PRIMARY KEY,
    trial_id          TEXT NOT NULL REFERENCES trials(trial_id) ON DELETE CASCADE,
    turn_instance     INTEGER NOT NULL,
    step              INTEGER NOT NULL,
    call_index        INTEGER NOT NULL DEFAULT 0,
    -- The event range this grade covers, inclusive, into events(seq) for the
    -- same trial_id -- the join key a report uses to pair a grade with the
    -- transcript lines it judged.
    event_seq_start   INTEGER NOT NULL,
    event_seq_end     INTEGER NOT NULL,
    -- Price-clocked timestamps: milliseconds from the trial's own first
    -- stamped event, the same origin the live transcript reader anchors to.
    -- Never wall-clock read time -- a trial read live and one read six
    -- months later must grade identically.
    ts_start_ms       INTEGER,
    ts_end_ms         INTEGER,
    wall_clock_ms     INTEGER,        -- ts_end_ms - ts_start_ms
    -- Time actually inside the provider call, summed over this window --
    -- distinct from wall_clock_ms, which also counts tool execution between
    -- calls.
    model_time_ms     INTEGER,
    cost_usd          REAL,
    -- Mirrors trials.cost_norm_status: 'priced' is the only state in which
    -- cost_usd means anything; a query that aggregates it must filter here.
    cost_norm_status  TEXT NOT NULL DEFAULT 'unmigrated',
    tool_calls_count  INTEGER NOT NULL DEFAULT 0,
    -- 'productive' | 'unproductive' | 'neutral'. Neutral is a real verdict,
    -- not a default -- a step with no measurable effect is neither credit
    -- nor blame.
    direction         TEXT NOT NULL,
    -- 'deterministic' | 'agent_judge' | 'escalated_human'. Which path
    -- produced this row -- never inferred from direction alone.
    direction_source  TEXT NOT NULL,
    -- The specific rule or judge note that fired, e.g. 'verifier_delta:+2',
    -- 'loop_detected', 'agent_judge:low_confidence'.
    direction_reason  TEXT,
    -- 1.0 for every deterministic rule (exact by construction); the agent
    -- judge's self-reported confidence otherwise. NULL only for
    -- escalated_human rows pending a decision.
    confidence        REAL,
    grader_version    TEXT NOT NULL,
    graded_at         TEXT NOT NULL
);

-- One grader_version's grade for a given step-window is a single fact, never
-- duplicated by re-running the same grader over the same trial.
CREATE UNIQUE INDEX IF NOT EXISTS step_grades_identity_idx
    ON step_grades(trial_id, turn_instance, step, call_index, grader_version);
CREATE INDEX IF NOT EXISTS step_grades_trial_idx ON step_grades(trial_id);
CREATE INDEX IF NOT EXISTS step_grades_turn_idx  ON step_grades(trial_id, turn_instance);

-- One row per (trial, turn_instance, grader_version): the roll-up of that
-- turn's step_grades. A turn is Stella's own unit (one run_turn / one
-- LoopDetected turn_instance), matching the key the wire's StepManifest and
-- LoopDetected events already carry.
CREATE TABLE IF NOT EXISTS turn_grades (
    turn_grade_id       TEXT PRIMARY KEY,
    trial_id            TEXT NOT NULL REFERENCES trials(trial_id) ON DELETE CASCADE,
    turn_instance       INTEGER NOT NULL,
    ts_start_ms         INTEGER,
    ts_end_ms           INTEGER,
    wall_clock_ms       INTEGER,
    model_time_ms       INTEGER,     -- sum of step_grades.model_time_ms
    cost_usd            REAL,        -- sum of step_grades.cost_usd
    cost_norm_status    TEXT NOT NULL DEFAULT 'unmigrated',
    step_count          INTEGER NOT NULL DEFAULT 0,
    productive_steps    INTEGER NOT NULL DEFAULT 0,
    unproductive_steps  INTEGER NOT NULL DEFAULT 0,
    neutral_steps       INTEGER NOT NULL DEFAULT 0,
    -- productive_steps / step_count. NULL when step_count = 0 (never 0/0 --
    -- an absent ratio must never render as a comparable zero).
    productive_step_ratio REAL,
    -- Mirrors how the turn ended on the wire: 'complete', 'error',
    -- 'loop_aborted', or 'in_progress' for a prefix graded before the turn
    -- closed.
    outcome             TEXT,
    grader_version      TEXT NOT NULL,
    graded_at           TEXT NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS turn_grades_identity_idx
    ON turn_grades(trial_id, turn_instance, grader_version);
CREATE INDEX IF NOT EXISTS turn_grades_trial_idx ON turn_grades(trial_id);

-- One row per (trial, grader_version): the roll-up of that trial's whole
-- execution -- every turn it ran, start to finish or to whatever prefix was
-- graded.
CREATE TABLE IF NOT EXISTS execution_grades (
    execution_grade_id  TEXT PRIMARY KEY,
    trial_id            TEXT NOT NULL REFERENCES trials(trial_id) ON DELETE CASCADE,
    -- Denormalized from trials.run_id so a cross-run rollup (e.g. "productive
    -- ratio by model, across every run this month") is one scan of this
    -- table rather than a join for every query.
    run_id              TEXT NOT NULL REFERENCES runs(run_id) ON DELETE CASCADE,
    ts_start_ms         INTEGER,
    ts_end_ms           INTEGER,
    -- Derived independently from the graded events, not copied from
    -- trials.wall_seconds -- the two are expected to agree, and a report
    -- that shows both is a cheap cross-check on the ingester and the grader
    -- agreeing about where a trial started and ended.
    wall_clock_ms       INTEGER,
    model_time_ms       INTEGER,
    cost_usd            REAL,
    cost_norm_status    TEXT NOT NULL DEFAULT 'unmigrated',
    turn_count          INTEGER NOT NULL DEFAULT 0,
    step_count          INTEGER NOT NULL DEFAULT 0,
    productive_steps    INTEGER NOT NULL DEFAULT 0,
    unproductive_steps  INTEGER NOT NULL DEFAULT 0,
    neutral_steps       INTEGER NOT NULL DEFAULT 0,
    -- THE metric: productive_steps / step_count over the whole execution.
    -- NULL when step_count = 0, same rule as turn_grades.
    agent_productive_step_ratio REAL,
    -- Does the ratio's trend agree with trials.passed? One of 'consistent'
    -- (high ratio + passed, or low ratio + failed), 'discordant' (passed
    -- despite a low ratio, or failed despite a high one -- both worth a
    -- human look), or NULL when trials.passed is itself NULL/unjudged. A
    -- sanity signal only -- never fed back into pass/fail.
    verdict_alignment   TEXT,
    grader_version      TEXT NOT NULL,
    graded_at           TEXT NOT NULL,
    notes               TEXT
);

CREATE UNIQUE INDEX IF NOT EXISTS execution_grades_identity_idx
    ON execution_grades(trial_id, grader_version);
CREATE INDEX IF NOT EXISTS execution_grades_run_idx ON execution_grades(run_id);
