#!/usr/bin/env python3
"""The diagnostic-code registry: scan the tree, check the reference, regenerate it.

`docs/spec/diagnostics.md` §11 makes a record's `code` versioned public
surface, the way rustc's E0308 is: operators alert on it, docs link it, and it
outlives its message text. A surface is only public if it is written down, so
`docs/reference/diagnostics.md` documents every code the workspace emits — and
this script is what keeps that sentence true (#2507).

Three modes:

    check   exit non-zero, with a buffered report, when the committed reference
            and the tree disagree: a code emitted but not documented, a section
            for a code nothing emits any more, two crates claiming one code,
            stale generated facts, or a section whose prose is still the
            placeholder. This is the gate step (`make diagnostic-codes`, via
            scripts/check-diagnostic-codes.sh).
    write   regenerate docs/reference/diagnostics.md in place. Facts blocks and
            structure are rewritten from the tree; the hand-written prose under
            each code is preserved by code, so a rename shows up as a dropped
            section plus a new placeholder — visible in the diff, which is the
            point.
    list    print the extracted inventory as JSON (a debugging aid, not an
            interface; nothing may parse this).

## How codes are found, and why by reading source

The generator must not need to run a binary to enumerate codes — the gate has
to work in `make guards-fast`, which compiles nothing. So this scans source,
and it reads exactly the three shapes an emit site can take:

  1. `diag!(dx, level, "a.b.c", …)` — the macro takes its code as a literal
     (crates/stella-diag/src/dx.rs), which is what makes this enumerable.
  2. `impl Facet for T { fn code(&self) … }` — returning a literal or a
     `const NAME: &str` defined in the same file.
  3. A call whose argument list pairs a `Level::…` expression immediately
     followed by a dotted-string literal — `dx.emit(Record::new(Level::Warn,
     "diag.filter.bad_clause", …))` and the domain bridge's
     `self.emit(Level::Debug, "agent.tool.call", …)` helper. The Level-then-code
     pair is the discriminator: the workspace has three *other* planes with an
     `emit` method (AgentEvent, the hook bus, serve's Observer) and none of
     them takes a Level.

A fourth shape would be invisible here. That is a known edge, accepted on the
same grounds as check-invariants.sh's greps: the reviewable convention is that
codes reach a record through these three doors, and a PR inventing a fourth
has to touch this script or ship an undocumented code past review.

Test code does not count as an emit site: `#[cfg(test)]` modules, doc comments
(where every `diag!` example in stella-diag lives), and `tests/` trees are all
stripped before scanning, so `test.doomed` and friends never reach the
reference.

Stdlib only, like the other Python guards (check-doc-links.py &c.), so it runs
on a bare CI runner.
"""

from __future__ import annotations

import json
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
CRATES = REPO / "crates"
REFERENCE = REPO / "docs" / "reference" / "diagnostics.md"

# The code grammar: lowercase dotted segments, at least two of them. This is
# deliberately narrower than "any string" — it is what keeps shape 3's
# Level-then-literal heuristic from matching a message.
CODE_RE = re.compile(r'^"([a-z][a-z0-9_]*(?:\.[a-z0-9_]+)+)"$')
CODE_ANY = re.compile(r'"([a-z][a-z0-9_]*(?:\.[a-z0-9_]+)+)"')
CONST_STR = re.compile(
    r"const\s+(\w+)\s*:\s*&(?:'static\s+)?str\s*=\s*\"([^\"]+)\""
)
WITH_FIELD = re.compile(r'\.with\(\s*"([a-z0-9_]+)"')
LEVELS = re.compile(r"Level::(\w+)")

PLACEHOLDER = "_TODO: say what this code means and what to do about it._"
FACTS_BEGIN = "<!-- facts:begin — generated by `make diag-reference`; do not edit by hand -->"
FACTS_END = "<!-- facts:end -->"


@dataclass
class Emit:
    """One code, as the union of everything the tree says about it."""

    code: str
    crates: set[str] = field(default_factory=set)
    files: set[str] = field(default_factory=set)
    levels: set[str] = field(default_factory=set)
    # Insertion-ordered union of statically visible field names.
    fields: dict[str, None] = field(default_factory=dict)
    # True when at least one emit site builds its fields somewhere this
    # scanner cannot see (e.g. a helper returning `Fields`).
    dynamic: bool = False


# ── Source preprocessing ─────────────────────────────────────────────────────


def strip_comments(src: str) -> str:
    """Remove line comments (incl. `///`/`//!` docs), block comments, and the
    contents of string literals' escapes — leaving strings themselves intact.

    Doc comments are where every `diag!` *example* lives, so stripping them is
    load-bearing, not tidiness. Block comments nest in Rust and are handled so.
    Comment characters are replaced with spaces, not deleted, so byte offsets
    stay meaningful for error reporting.
    """
    out = list(src)
    i, n = 0, len(src)
    while i < n:
        c = src[i]
        nxt = src[i + 1] if i + 1 < n else ""
        if c == "/" and nxt == "/":
            while i < n and src[i] != "\n":
                out[i] = " "
                i += 1
        elif c == "/" and nxt == "*":
            depth = 1
            out[i] = out[i + 1] = " "
            i += 2
            while i < n and depth:
                if src[i] == "/" and i + 1 < n and src[i + 1] == "*":
                    depth += 1
                    out[i] = out[i + 1] = " "
                    i += 2
                elif src[i] == "*" and i + 1 < n and src[i + 1] == "/":
                    depth -= 1
                    out[i] = out[i + 1] = " "
                    i += 2
                else:
                    if src[i] != "\n":
                        out[i] = " "
                    i += 1
        elif c == '"':
            i += 1
            while i < n:
                if src[i] == "\\":
                    i += 2
                elif src[i] == '"':
                    i += 1
                    break
                else:
                    i += 1
        elif c == "'":
            # A char literal ('x', '\n') or a lifetime ('static). Only the
            # former has a closing quote to skip.
            if i + 2 < n and (src[i + 1] == "\\" or src[i + 2] == "'"):
                j = i + 2 if src[i + 1] != "\\" else i + 3
                i = j + 1 if j < n and src[j] == "'" else i + 1
            else:
                i += 1
        else:
            i += 1
    return "".join(out)


def matching_brace(src: str, open_idx: int) -> int:
    """Index just past the `}` matching the `{` at open_idx. Comment-stripped
    input; string literals are honoured."""
    depth = 0
    i = open_idx
    n = len(src)
    while i < n:
        c = src[i]
        if c == '"':
            i += 1
            while i < n:
                if src[i] == "\\":
                    i += 2
                elif src[i] == '"':
                    break
                else:
                    i += 1
        elif c == "{":
            depth += 1
        elif c == "}":
            depth -= 1
            if depth == 0:
                return i + 1
        i += 1
    return n


def strip_cfg_test(src: str) -> str:
    """Blank out every `#[cfg(test)]`-gated item (in practice: `mod tests`).

    Test emit sites are not public surface — `test.doomed` must never demand a
    reference section.
    """
    out = src
    for m in re.finditer(r"#\[cfg\(test\)\]", src):
        brace = src.find("{", m.end())
        semi = src.find(";", m.end())
        if brace == -1 or (semi != -1 and semi < brace):
            continue  # a gated `use`/decl, not a block
        end = matching_brace(src, brace)
        out = out[: m.start()] + re.sub(r"\S", " ", out[m.start() : end]) + out[end:]
    return out


def balanced_call(src: str, open_paren: int) -> str:
    """The argument text of the call whose `(` is at open_paren, exclusive of
    the outer parens."""
    depth = 0
    i = open_paren
    n = len(src)
    while i < n:
        c = src[i]
        if c == '"':
            i += 1
            while i < n:
                if src[i] == "\\":
                    i += 2
                elif src[i] == '"':
                    break
                else:
                    i += 1
        elif c == "(":
            depth += 1
        elif c == ")":
            depth -= 1
            if depth == 0:
                return src[open_paren + 1 : i]
        i += 1
    return src[open_paren + 1 :]


def split_args(argtext: str) -> list[str]:
    """Top-level comma split, respecting (), [], {} and strings."""
    args: list[str] = []
    depth = 0
    cur: list[str] = []
    i, n = 0, len(argtext)
    while i < n:
        c = argtext[i]
        if c == '"':
            cur.append(c)
            i += 1
            while i < n:
                cur.append(argtext[i])
                if argtext[i] == "\\":
                    i += 1
                    if i < n:
                        cur.append(argtext[i])
                elif argtext[i] == '"':
                    break
                i += 1
        elif c in "([{":
            depth += 1
            cur.append(c)
        elif c in ")]}":
            depth -= 1
            cur.append(c)
        elif c == "," and depth == 0:
            args.append("".join(cur).strip())
            cur = []
        else:
            cur.append(c)
        i += 1
    tail = "".join(cur).strip()
    if tail:
        args.append(tail)
    return args


# ── Extraction ───────────────────────────────────────────────────────────────


def field_names(exprs: list[str]) -> tuple[dict[str, None], bool]:
    """Statically visible field names in a fields-building expression, plus
    whether anything opaque contributes fields this scanner cannot name."""
    names: dict[str, None] = {}
    dynamic = False
    joined = " ".join(exprs)
    if "at_seq()" in joined:
        names["seq"] = None  # the bridge's Fields::new().with("seq", …) helper
    for name in WITH_FIELD.findall(joined):
        names[name] = None
    if not names and joined and "Fields::new()" not in joined:
        # Something like `Parsed::report(clause)`: fields exist, names do not.
        dynamic = True
    return names, dynamic


def record(inventory: dict[str, Emit], code: str, crate: str, rel: str) -> Emit:
    entry = inventory.setdefault(code, Emit(code))
    entry.crates.add(crate)
    entry.files.add(rel)
    return entry


def scan_file(path: Path, inventory: dict[str, Emit]) -> None:
    rel = path.relative_to(REPO).as_posix()
    crate = path.relative_to(CRATES).parts[0]
    src = strip_cfg_test(strip_comments(path.read_text(encoding="utf-8")))
    consts = dict(CONST_STR.findall(src))

    # Shape 1: diag!(dx, level, "code", [cx: …,] k = v, …)
    for m in re.finditer(r"\bdiag!\s*\(", src):
        args = split_args(balanced_call(src, m.end() - 1))
        if len(args) < 3:
            continue
        lit = CODE_RE.match(args[2])
        if not lit:
            continue  # the macro's own definition, or a $-variable
        entry = record(inventory, lit.group(1), crate, rel)
        entry.levels.add(args[1].strip().lower())
        for arg in args[3:]:
            if arg.startswith("cx:"):
                continue
            key = arg.split("=", 1)[0].strip()
            if re.fullmatch(r"[a-z][a-z0-9_]*", key):
                entry.fields[key] = None

    # Shape 3: any call carrying (…, Level::X, "code", …) adjacent — the
    # bridge's emit helper and direct Record::new construction.
    for m in re.finditer(r"(?:\bRecord::new|\.emit)\s*\(", src):
        args = split_args(balanced_call(src, m.end() - 1))
        for i in range(1, len(args)):
            lit = CODE_RE.match(args[i])
            if not lit or "Level::" not in args[i - 1]:
                continue
            entry = record(inventory, lit.group(1), crate, rel)
            entry.levels.update(l.lower() for l in LEVELS.findall(args[i - 1]))
            names, dynamic = field_names(args[i + 1 :])
            entry.fields.update(names)
            entry.dynamic = entry.dynamic or dynamic
            break

    # Shape 2: impl Facet for T { fn code … fn level … fn fields … }
    for m in re.finditer(r"\bimpl\s+Facet\s+for\s+\w+", src):
        brace = src.find("{", m.end())
        if brace == -1:
            continue
        body = src[brace : matching_brace(src, brace)]
        code_m = re.search(r"fn\s+code\b[^{]*\{([^}]*)\}", body)
        if not code_m:
            continue
        ret = code_m.group(1).strip()
        lit = CODE_ANY.search(ret)
        code = lit.group(1) if lit else consts.get(ret)
        if not code:
            continue
        entry = record(inventory, code, crate, rel)
        level_m = re.search(r"fn\s+level\b[^{]*\{([^}]*)\}", body)
        if level_m:
            entry.levels.update(l.lower() for l in LEVELS.findall(level_m.group(1)))
        fields_m = re.search(r"fn\s+fields\b[^{]*\{", body)
        if fields_m:
            open_b = brace + fields_m.end() - 1
            fields_body = src[open_b : matching_brace(src, open_b)]
            names, dynamic = field_names([fields_body])
            entry.fields.update(names)
            entry.dynamic = entry.dynamic or dynamic


def scan_tree() -> dict[str, Emit]:
    inventory: dict[str, Emit] = {}
    for path in sorted(CRATES.glob("*/src/**/*.rs")):
        rel = path.relative_to(REPO).as_posix()
        if "/tests/" in rel or "/benches/" in rel or "/examples/" in rel:
            continue
        scan_file(path, inventory)
    return inventory


# ── The reference document ───────────────────────────────────────────────────

HEADER = """\
---
id: diagnostic-codes
title: "Diagnostic codes — every code the workspace emits, and what to do about each"
status: living
---

# Diagnostic codes

A record's `code` is stable, versioned public surface (`doc:diagnostics` §11):
operators alert on it, docs link it, and it outlives the message text. This
file is that surface's reference — one section per code the tree emits.

**The facts blocks and section list are generated** from the emit sites by
`make diag-reference` (`scripts/diagnostic-codes.py`); the prose under each
facts block is hand-written and preserved across regeneration. The gate
(`make diagnostic-codes`) fails when this file and the tree disagree — an
undocumented code, a section for a code nothing emits, two crates claiming one
code, stale facts, or prose still reading as the placeholder. Fields listed
are the statically visible ones; a section says so when an emit site builds
fields the scanner cannot name.

Codes are grouped by the crate that owns their facet vocabulary (§5.1 of the
spec: the crate that owns the vocabulary owns the rendering).
"""


def facts_block(entry: Emit) -> str:
    levels = " or ".join(f"`{l}`" for l in sorted(entry.levels)) or "`(unknown)`"
    files = ", ".join(f"`{f}`" for f in sorted(entry.files))
    if entry.fields:
        fields = ", ".join(f"`{name}`" for name in entry.fields)
        if entry.dynamic:
            fields += " — plus fields built at runtime; see the emit site"
    elif entry.dynamic:
        fields = "built at runtime; see the emit site"
    else:
        fields = "none"
    return "\n".join(
        [
            FACTS_BEGIN,
            f"- **Level:** {levels}",
            f"- **Emitted from:** {files}",
            f"- **Fields:** {fields}",
            FACTS_END,
        ]
    )


def render(inventory: dict[str, Emit], prose: dict[str, str]) -> str:
    out = [HEADER]
    by_crate: dict[str, list[Emit]] = {}
    for entry in inventory.values():
        by_crate.setdefault(sorted(entry.crates)[0], []).append(entry)
    for crate in sorted(by_crate):
        out.append(f"\n## `{crate}`\n")
        for entry in sorted(by_crate[crate], key=lambda e: e.code):
            out.append(f"\n### `{entry.code}`\n")
            out.append(facts_block(entry))
            out.append("")
            out.append(prose.get(entry.code, PLACEHOLDER).rstrip())
    return "\n".join(out) + "\n"


SECTION = re.compile(r"^### `([a-z0-9_.]+)`\s*$", re.MULTILINE)


def parse_reference(text: str) -> tuple[list[str], dict[str, str]]:
    """The documented codes in order, and each section's hand-written prose
    (everything after its facts block, up to the next heading)."""
    codes: list[str] = []
    prose: dict[str, str] = {}
    matches = list(SECTION.finditer(text))
    for i, m in enumerate(matches):
        code = m.group(1)
        codes.append(code)
        end = matches[i + 1].start() if i + 1 < len(matches) else len(text)
        section = text[m.end() : end]
        # Prose follows the facts block when there is one, else the heading.
        marker = section.find(FACTS_END)
        body = section[marker + len(FACTS_END) :] if marker != -1 else section
        # Stop at a crate heading that may sit between this section and the next.
        body = re.split(r"^## ", body, maxsplit=1, flags=re.MULTILINE)[0]
        cleaned = body.strip()
        if cleaned:
            prose[code] = cleaned
    return codes, prose


# ── Modes ────────────────────────────────────────────────────────────────────


def do_check() -> int:
    # The verdict is decided before anything is written, like the shell guards
    # (#1815): buffer, then emit once.
    report: list[str] = []
    inventory = scan_tree()

    for entry in sorted(inventory.values(), key=lambda e: e.code):
        if len(entry.crates) > 1:
            report.append(
                f"FAIL — `{entry.code}` is emitted by more than one crate "
                f"({', '.join(sorted(entry.crates))}); a facet vocabulary has one owner (§5.1)."
            )

    if not REFERENCE.exists():
        report.append(
            f"FAIL — {REFERENCE.relative_to(REPO)} does not exist. Generate it: make diag-reference"
        )
    else:
        text = REFERENCE.read_text(encoding="utf-8")
        codes, prose = parse_reference(text)
        seen: set[str] = set()
        for code in codes:
            if code in seen:
                report.append(f"FAIL — `{code}` is documented twice.")
            seen.add(code)
        for code in sorted(set(inventory) - seen):
            report.append(
                f"FAIL — `{code}` is emitted ({', '.join(sorted(inventory[code].files))}) "
                "but has no section in the reference."
            )
        for code in sorted(seen - set(inventory)):
            report.append(
                f"FAIL — the reference documents `{code}`, which nothing emits any more."
            )
        for code in sorted(set(inventory) & seen):
            if prose.get(code, "").strip() in ("", PLACEHOLDER):
                report.append(
                    f"FAIL — `{code}`'s section is still the placeholder; write what it "
                    "means and what to do about it."
                )
        if render(inventory, prose) != text:
            report.append(
                "FAIL — the reference's generated facts are stale for the current tree. "
                "Regenerate: make diag-reference (then commit the diff)."
            )

    if report:
        for line in report:
            print(f"check-diagnostic-codes: {line}", file=sys.stderr)
        print(
            "check-diagnostic-codes: the registry lives in docs/reference/diagnostics.md; "
            "`make diag-reference` rewrites its generated parts and preserves prose.",
            file=sys.stderr,
        )
        return 1
    print(
        f"check-diagnostic-codes: OK — {len(inventory)} codes emitted, all documented."
    )
    return 0


def do_write() -> int:
    inventory = scan_tree()
    prose: dict[str, str] = {}
    if REFERENCE.exists():
        _, prose = parse_reference(REFERENCE.read_text(encoding="utf-8"))
    REFERENCE.parent.mkdir(parents=True, exist_ok=True)
    REFERENCE.write_text(render(inventory, prose), encoding="utf-8")
    missing = [c for c in sorted(inventory) if prose.get(c, "").strip() in ("", PLACEHOLDER)]
    print(f"diagnostic-codes: wrote {REFERENCE.relative_to(REPO)} — {len(inventory)} codes.")
    if missing:
        print(
            f"diagnostic-codes: {len(missing)} still placeholder: {', '.join(missing)}"
        )
    return 0


def do_list() -> int:
    inventory = scan_tree()
    print(
        json.dumps(
            {
                code: {
                    "crates": sorted(e.crates),
                    "files": sorted(e.files),
                    "levels": sorted(e.levels),
                    "fields": list(e.fields),
                    "dynamic": e.dynamic,
                }
                for code, e in sorted(inventory.items())
            },
            indent=2,
        )
    )
    return 0


def main() -> int:
    mode = sys.argv[1] if len(sys.argv) > 1 else "check"
    if mode == "check":
        return do_check()
    if mode == "write":
        return do_write()
    if mode == "list":
        return do_list()
    print(f"usage: {sys.argv[0]} check|write|list", file=sys.stderr)
    return 2


if __name__ == "__main__":
    sys.exit(main())
