#!/usr/bin/env python3
"""Generate every colour artifact in the tree from design/tokens/stella-tokens.json.

The token file is the single upstream. This script is the only writer of the
files it emits, and `--check` re-derives them in memory and diffs, so the gate
fails when a generated file has been hand-edited or left stale.

That mechanism is the point. The palette is a *shared cell*: four surfaces (the
TUI, the marketing site, the brand kit, the Observatory) each need the same
twenty-one values, and every previous attempt to hold them together was a
sentence in a doc comment asking the next author to copy carefully. Twice that
sentence was the only thing left true -- website/src/app/tokens.css sat on the
v1.0 ramp through the whole life of the v4.0 rebrand while still claiming to
mirror the kit. A comment cannot hold a shared cell; a generator and a diff can.

Usage:
    scripts/gen-tokens.py            # write the generated files
    scripts/gen-tokens.py --check    # fail if any is stale (gate step)
"""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
TOKENS = REPO / "design" / "tokens" / "stella-tokens.json"

# Emitted files, relative to the repo root. Every one of these is generated in
# full; none is a partial region inside a hand-written file, because a marked
# region is a merge conflict waiting to happen and an unmarked one is worse.
CSS_OUT = Path("design/tokens/stella-tokens.css")
RUST_OUT = Path("crates/stella-tui-theme/src/token.rs")

BANNER_HASH = "# GENERATED by scripts/gen-tokens.py from design/tokens/stella-tokens.json."


def channels(hex_value: str) -> tuple[int, int, int]:
    """Split `#RRGGBB` into integer channels."""
    raw = hex_value.lstrip("#")
    if len(raw) != 6:
        raise ValueError(f"not a 6-digit hex: {hex_value}")
    return int(raw[0:2], 16), int(raw[2:4], 16), int(raw[4:6], 16)


# ── Clamp predicates ────────────────────────────────────────────────────────
#
# These mirror crates/stella-tui-theme/src/clamp.rs exactly, and the Rust file
# is generated from the same `clamps` block below, so the two cannot disagree.
# All arithmetic is integer: `g >= 0.78 r` is asserted as `100 g >= 78 r`, the
# same predicate with no float rounding to argue about at a boundary -- and a
# boundary is exactly where a palette drifts.


def gold_shape(r: int, g: int, b: int, green_pct: int) -> bool:
    return r > g and g > b and 100 * g >= green_pct * r


def hue_degrees(r: int, g: int, b: int) -> float | None:
    """Hue in [0, 360), or None for an achromatic colour."""
    hi, lo = max(r, g, b), min(r, g, b)
    delta = hi - lo
    if delta == 0:
        return None
    if hi == r:
        raw = ((g - b) / delta) % 6
    elif hi == g:
        raw = (b - r) / delta + 2
    else:
        raw = (r - g) / delta + 4
    return (60.0 * raw) % 360.0


def lightness(r: int, g: int, b: int) -> float:
    """The L of HSL -- the midpoint of the extreme channels."""
    return (max(r, g, b) + min(r, g, b)) / 510.0


def hue_distance(a: float, b: float) -> float:
    """Shortest angular distance between two hues, in degrees."""
    raw = abs(a - b) % 360.0
    return min(raw, 360.0 - raw)


def check_clamp(
    name: str, hexv: str, clamp: str, spec: dict, anchors: dict[str, str]
) -> str | None:
    """Return an error string if `hexv` fails the predicate for `clamp`.

    Mirrors crates/stella-tui-theme/src/clamp.rs. The two are held together by
    `check-tokens.py`, not by a promise -- see this file's header.
    """
    r, g, b = channels(hexv)
    if clamp in ("resting-gold", "gold-lift"):
        green = spec["green_pct"]
        # The hue clause, carried by every gold at every lightness. It is what
        # separates gold from orange, and orange on a near-black ground reads
        # brown on a cheap panel.
        if not gold_shape(r, g, b, green):
            return (
                f"{name} {hexv} fails {clamp}: needs r > g > b and "
                f"100*g >= {green}*r; got r={r} g={g} b={b} "
                f"(100*g={100 * g}, {green}*r={green * r})"
            )
    if clamp == "resting-gold":
        # The saturation clause, which governs only a hue that is not
        # lightened. See the `gold-lift` entry in the JSON for why it cannot
        # govern a lift: above lightness 0.6745 it is unsatisfiable by any
        # colour, so a lift could never have been held to it.
        blue = spec["blue_pct"]
        if 100 * b > blue * r:
            return (
                f"{name} {hexv} fails {clamp} blue ceiling: needs "
                f"100*b <= {blue}*r; got 100*b={100 * b}, {blue}*r={blue * r}"
            )
        return None
    if clamp == "gold-lift":
        # A lift is anchored to the gold it lifts, never to a second ceiling.
        # An anchor admits only the authored gold, brighter; a ceiling admits
        # everything beneath it and keeps passing after that gold is gone.
        anchor_name = spec["anchor"]
        anchor_hex = anchors.get(anchor_name)
        if anchor_hex is None:
            return f"{name}: clamp {clamp!r} names anchor {anchor_name!r}, which is not a token"
        ar, ag, ab = channels(anchor_hex)
        hue, anchor_hue = hue_degrees(r, g, b), hue_degrees(ar, ag, ab)
        if hue is None or anchor_hue is None:
            return f"{name} {hexv} or its anchor {anchor_hex} is achromatic and has no hue"
        tolerance = spec["hue_tolerance_deg"]
        distance = hue_distance(hue, anchor_hue)
        if distance > tolerance:
            return (
                f"{name} {hexv} is not a lift of {anchor_name} {anchor_hex}: "
                f"hue {hue:.2f} deg is {distance:.2f} deg away, tolerance {tolerance}"
            )
        if lightness(r, g, b) <= lightness(ar, ag, ab):
            return (
                f"{name} {hexv} is not a lift of {anchor_name} {anchor_hex}: "
                f"lightness {lightness(r, g, b):.4f} is not above "
                f"{lightness(ar, ag, ab):.4f}. A lift is brighter, or it is a "
                f"second gold -- and this palette authors one."
            )
        return None
    if clamp == "cool-silver":
        if not (b > r and g >= r):
            return (
                f"{name} {hexv} fails cool-silver: needs b > r and g >= r; "
                f"got r={r} g={g} b={b}"
            )
        return None
    if clamp == "neutral-gray":
        if not (r == g and b >= g):
            return (
                f"{name} {hexv} fails neutral-gray: needs r == g and b >= g; "
                f"got r={r} g={g} b={b}"
            )
        return None
    if clamp == "warm-paper":
        if not (r >= g >= b):
            return (
                f"{name} {hexv} fails warm-paper: needs r >= g >= b; "
                f"got r={r} g={g} b={b}"
            )
        if g * 100 < r * spec["green_pct"] or b * 100 < r * spec["blue_pct"]:
            return (
                f"{name} {hexv} fails warm-paper floors: needs "
                f"100*g >= {spec['green_pct']}*r and 100*b >= {spec['blue_pct']}*r; "
                f"got r={r} g={g} b={b}"
            )
        return None
    if clamp in ("verdict", "surface"):
        return None
    return f"{name}: unknown clamp role {clamp!r}"


def rust_tokens(doc: dict) -> list[dict]:
    """The tokens that reach the terminal, in declaration order.

    A token declares a `rust` name when the TUI renders it. The web-only ones
    -- the below-canvas backdrop, the gold-on-paper text stop, the five-step
    light ramp and the four status inks -- do not, and must not: every entry in
    the generated `ALL` table needs a 256-colour fallback pinned by
    `stella-tui-theme`'s tests, and inventing an ANSI approximation of a paper
    tint the terminal never draws would be an assertion about nothing.

    The alternative was to leave those values out of the system entirely, which
    is what `main` does -- and it means the only file that knows the site's
    warning hue is the site, unclamped and uncheckable. Declaring them here
    puts them under the same hue predicates as everything else while leaving
    `token.rs` byte-identical, because every token that had a `rust` name
    before this still has one.
    """
    return [tok for tok in doc["tokens"] if tok.get("rust")]


def validate(doc: dict) -> list[str]:
    """Every token against its declared clamp. Returns the failures."""
    errors: list[str] = []
    clamps = doc["clamps"]
    seen: dict[str, str] = {}
    # An anchored clamp (`gold-lift`) is checked against another token's value,
    # so the whole table has to be resolvable before any one row is judged.
    anchors = {tok["name"]: tok["hex"] for tok in doc["tokens"]}
    for tok in doc["tokens"]:
        clamp = tok["clamp"]
        if clamp not in clamps:
            errors.append(f"{tok['name']}: clamp {clamp!r} is not declared in `clamps`")
            continue
        err = check_clamp(tok["name"], tok["hex"], clamp, clamps[clamp], anchors)
        if err:
            errors.append(err)
        # A hex used twice under two names is how a role quietly loses meaning.
        prior = seen.get(tok["hex"].upper())
        if prior:
            errors.append(f"{tok['name']}: hex {tok['hex']} already used by {prior}")
        seen[tok["hex"].upper()] = tok["name"]
    # The banned list must not name a live token: that would make the guard
    # unsatisfiable, and an unsatisfiable guard gets deleted rather than fixed.
    live = {t["hex"].upper() for t in doc["tokens"]}
    for entry in doc["banned"]["values"]:
        if entry["hex"].upper() in live:
            errors.append(f"banned hex {entry['hex']} is also a live token")
    return errors


# ── Emitters ────────────────────────────────────────────────────────────────


def render_css(doc: dict) -> str:
    lines = [
        "/*",
        " * The stella colour system -- every custom property, one ground truth.",
        " *",
        " * GENERATED by scripts/gen-tokens.py from design/tokens/stella-tokens.json.",
        " * Do not edit this file. Edit the JSON and run `make tokens-update`.",
        " *",
        f" * System: {doc['name']} v{doc['version']}.",
        f" * Supersedes {doc['supersedes']['kit']} ({doc['supersedes']['brand_hex']} on",
        f" * {doc['supersedes']['ground_hex']}) -- see the JSON's `supersedes` block for why",
        " * both of that kit's anchor values sit outside this system's hue clamp.",
        " */",
        "",
        ":root {",
    ]
    for tok in doc["tokens"]:
        lines.append(f"  {tok['css']}: {tok['hex']}; /* {tok['role']} */")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def render_rust(doc: dict) -> str:
    clamps = doc["clamps"]
    resting = clamps["resting-gold"]
    lift = clamps["gold-lift"]
    paper = clamps["warm-paper"]

    def doc_block(text, indent: str = "//! ") -> list[str]:
        if isinstance(text, str):
            text = [text]
        return [f"{indent}{line}".rstrip() for line in text]

    out: list[str] = [
        "//! The palette -- SPEC-stella-tui-v2.md section 3.1.",
        "//!",
        "//! GENERATED by `scripts/gen-tokens.py` from `design/tokens/stella-tokens.json`.",
        "//! Do not edit this file. Edit the JSON and run `make tokens-update`.",
        "//!",
        "//! Every value is [`Color::Rgb`]; there are no indexed or named colours here,",
        "//! because the clamp can only speak about channels. [`ALL`] pairs each token",
        "//! with the [`Clamp`] its value is held to -- so a new hex cannot enter the",
        "//! palette without declaring what kind of colour it is, and the warm-drift",
        "//! predicates reject the declaration that would kill the scheme.",
        "//!",
        "//! **Values and role tags only.** The predicates themselves live in",
        "//! [`crate::clamp`], which is hand-written, and the tests that walk this table",
        "//! live beside them. That split is deliberate: the gold clamp is not a",
        "//! templatable expression but an argument with a geometric proof behind it",
        "//! (a lift is anchored to the gold it lifts, because the resting blue ceiling",
        "//! is unsatisfiable above lightness 0.6745), and a generator that emitted it",
        "//! would put the algorithm somewhere its proof could not follow.",
        "",
        "use ratatui::style::Color;",
        "",
        "// ── Clamp bounds ─────────────────────────────────────────────────",
        "//",
        "// The numbers the JSON declares. The predicates that read them are in",
        "// `crate::clamp`.",
        "",
        "/// The green ratio a gold must clear, as a percentage of red.",
        "///",
    ]
    out += doc_block(resting["why"], "/// ")
    out += [
        f"pub const GOLD_GREEN_PCT: u32 = {resting['green_pct']};",
        "",
        "/// The blue ceiling a resting gold must stay under, as a percentage of red.",
        "///",
        "/// Governs the resting gold alone. See [`GOLD_LIFT_HUE_TOLERANCE_DEG`] for a",
        "/// lift, and `crate::clamp` for why the two cannot be one bound.",
        f"pub const GOLD_BLUE_PCT: u32 = {resting['blue_pct']};",
        "",
        "/// How far a lift's hue may sit from the gold it lifts, in degrees.",
        "///",
    ]
    out += doc_block(lift["why"], "/// ")
    out += [
        f"pub const GOLD_LIFT_HUE_TOLERANCE_DEG: f64 = {lift['hue_tolerance_deg']}.0;",
        "",
        "/// The token a lift is anchored to.",
        f'pub const GOLD_LIFT_ANCHOR: &str = "{lift["anchor"]}";',
        "",
        "/// The green floor warm paper must clear, as a percentage of red.",
        "///",
    ]
    out += doc_block(paper["why"], "/// ")
    out += [
        f"pub const PAPER_GREEN_PCT: u32 = {paper['green_pct']};",
        "",
        "/// The blue floor warm paper must clear, as a percentage of red.",
        f"pub const PAPER_BLUE_PCT: u32 = {paper['blue_pct']};",
        "",
        "// ── Tokens ─────────────────────────────────────────────────────────",
        "",
    ]
    for tok in rust_tokens(doc):
        r, g, b = channels(tok["hex"])
        out += [
            f"/// {tok['role'][0].upper()}{tok['role'][1:]}. `{tok['hex']}`",
            f"pub const {tok['rust']}: Color = Color::Rgb(0x{r:02X}, 0x{g:02X}, 0x{b:02X});",
            "",
        ]

    out += [
        "// ── The walkable table ─────────────────────────────────────────────",
        "",
        "/// Which predicate a token's value is held to.",
        "///",
        "/// The role is declared per token in the source JSON rather than inferred from",
        "/// the name, because inference is what lets a warm hex in under a cool name.",
        "#[derive(Debug, Clone, Copy, PartialEq, Eq)]",
        "pub enum Clamp {",
        "    /// `r > g > b`, `100 g >= GOLD_GREEN_PCT r`, `100 b <= GOLD_BLUE_PCT r`.",
        "    RestingGold,",
        "    /// Anchored to the resting gold: the same hue within",
        "    /// [`GOLD_LIFT_HUE_TOLERANCE_DEG`], strictly lighter. Never a second blue",
        "    /// ceiling -- `crate::clamp` carries the argument.",
        "    GoldLift,",
        "    /// `b > r` and `g >= r` -- the second metal, never warm.",
        "    CoolSilver,",
        "    /// `r == g` and `b >= g` -- neutral, or tipped toward blue, never toward red.",
        "    NeutralGray,",
        "    /// `r >= g >= b`, `100 g >= PAPER_GREEN_PCT r`, `100 b >= PAPER_BLUE_PCT r`",
        "    /// -- the light ground, warm or neutral, never blue.",
        "    WarmPaper,",
        "    /// Pass and fail. Deliberately neither metal nor gray; no channel predicate.",
        "    Verdict,",
        "    /// A tint carrying a sign column, not a hue in a role; no channel predicate.",
        "    Surface,",
        "}",
        "",
        "/// Every token, paired with its name and the clamp it must satisfy.",
        "pub const ALL: &[(&str, Color, Clamp)] = &[",
    ]
    variant = {
        "resting-gold": "Clamp::RestingGold",
        "gold-lift": "Clamp::GoldLift",
        "cool-silver": "Clamp::CoolSilver",
        "neutral-gray": "Clamp::NeutralGray",
        "warm-paper": "Clamp::WarmPaper",
        "verdict": "Clamp::Verdict",
        "surface": "Clamp::Surface",
    }
    for tok in rust_tokens(doc):
        out.append(f'    ("{tok["name"]}", {tok["rust"]}, {variant[tok["clamp"]]}),')
    out += [
        "];",
        "",
        "// The predicates that read this table are in `crate::clamp`, and the",
        "// tests that walk it live beside them. See this file's module doc for why",
        "// the algorithm is not generated.",
        "",
    ]
    return "\n".join(out)


# ── Driver ──────────────────────────────────────────────────────────────────


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--check",
        action="store_true",
        help="fail if a generated file is stale instead of writing it",
    )
    args = ap.parse_args()

    doc = json.loads(TOKENS.read_text())

    errors = validate(doc)
    if errors:
        print("token validation failed:", file=sys.stderr)
        for err in errors:
            print(f"  {err}", file=sys.stderr)
        return 1

    outputs = {CSS_OUT: render_css(doc), RUST_OUT: render_rust(doc)}

    stale: list[Path] = []
    for rel, content in outputs.items():
        path = REPO / rel
        if args.check:
            if not path.exists() or path.read_text() != content:
                stale.append(rel)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)

    # The emitted Rust must already be rustfmt-clean. Nothing else enforces the
    # coupling, and getting it wrong is quiet in the worst way: `make
    # tokens-update` would write a file that `format-check` then rejects, so the
    # only way to a green gate would be to hand-edit a generated file — which is
    # precisely what the "do not edit" banner forbids, and the tree would have
    # taught the next author to ignore it. Checked rather than remembered.
    if shutil.which("rustfmt"):
        probe = subprocess.run(
            ["rustfmt", "--edition", "2024", "--emit", "stdout", "--quiet"],
            input=outputs[RUST_OUT],
            capture_output=True,
            text=True,
        )
        if probe.returncode != 0:
            print(f"rustfmt refused the generated Rust:\n{probe.stderr}", file=sys.stderr)
            return 1
        if probe.stdout != outputs[RUST_OUT]:
            print(
                f"the generated Rust is not rustfmt-clean. Fix the emitter in "
                f"{Path(__file__).name} — do not format {RUST_OUT} by hand, it is "
                f"overwritten on every run.",
                file=sys.stderr,
            )
            return 1

    if args.check:
        if stale:
            print("generated colour artifacts are stale:", file=sys.stderr)
            for rel in stale:
                print(f"  {rel}", file=sys.stderr)
            print(
                "\nrun `make tokens-update` and commit the result.",
                file=sys.stderr,
            )
            return 1
        print(f"tokens: {len(doc['tokens'])} validated, {len(outputs)} artifacts in sync")
    else:
        for rel in outputs:
            print(f"wrote {rel}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
