#!/usr/bin/env python3
"""Generate every colour artifact in the tree from design/tokens/stella-tokens.json.

The token file is the single upstream. This script is the only writer of the
files it emits, and `--check` re-derives them in memory and diffs, so the gate
fails when a generated file has been hand-edited or left stale.

That mechanism is the point. The palette is a *shared cell*: four surfaces (the
TUI, the marketing site, the brand kit, the Observatory) each need the same
twenty-one values, and every previous attempt to hold them together was a
sentence in a doc comment asking the next author to copy carefully. Twice that
sentence was the only thing left true -- website/src/app/tokens.css sat on the
v1.0 ramp through the whole life of the v4.0 rebrand while still claiming to
mirror the kit. A comment cannot hold a shared cell; a generator and a diff can.

Usage:
    scripts/gen-tokens.py            # write the generated files
    scripts/gen-tokens.py --check    # fail if any is stale (gate step)
"""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
TOKENS = REPO / "design" / "tokens" / "stella-tokens.json"

# Emitted files, relative to the repo root. Every one of these is generated in
# full; none is a partial region inside a hand-written file, because a marked
# region is a merge conflict waiting to happen and an unmarked one is worse.
CSS_OUT = Path("design/tokens/stella-tokens.css")
RUST_OUT = Path("crates/stella-tui-theme/src/generated.rs")

BANNER_HASH = "# GENERATED by scripts/gen-tokens.py from design/tokens/stella-tokens.json."


def channels(hex_value: str) -> tuple[int, int, int]:
    """Split `#RRGGBB` into integer channels."""
    raw = hex_value.lstrip("#")
    if len(raw) != 6:
        raise ValueError(f"not a 6-digit hex: {hex_value}")
    return int(raw[0:2], 16), int(raw[2:4], 16), int(raw[4:6], 16)


# ── Clamp predicates ────────────────────────────────────────────────────────
#
# These mirror crates/stella-tui-theme/src/clamp.rs exactly, and the Rust file
# is generated from the same `clamps` block below, so the two cannot disagree.
# All arithmetic is integer: `g >= 0.78 r` is asserted as `100 g >= 78 r`, the
# same predicate with no float rounding to argue about at a boundary -- and a
# boundary is exactly where a palette drifts.


def gold_shape(r: int, g: int, b: int, green_pct: int) -> bool:
    return r > g and g > b and 100 * g >= green_pct * r


def check_clamp(name: str, hexv: str, clamp: str, spec: dict) -> str | None:
    """Return an error string if `hexv` fails the predicate for `clamp`."""
    r, g, b = channels(hexv)
    if clamp in ("resting-gold", "lifted-gold"):
        green = spec["green_pct"]
        blue = spec["blue_pct"]
        if not gold_shape(r, g, b, green):
            return (
                f"{name} {hexv} fails {clamp}: needs r > g > b and "
                f"100*g >= {green}*r; got r={r} g={g} b={b} "
                f"(100*g={100 * g}, {green}*r={green * r})"
            )
        if 100 * b > blue * r:
            return (
                f"{name} {hexv} fails {clamp} blue ceiling: needs "
                f"100*b <= {blue}*r; got 100*b={100 * b}, {blue}*r={blue * r}"
            )
        return None
    if clamp == "cool-silver":
        if not (b > r and g >= r):
            return (
                f"{name} {hexv} fails cool-silver: needs b > r and g >= r; "
                f"got r={r} g={g} b={b}"
            )
        return None
    if clamp == "neutral-gray":
        if not (r == g and b >= g):
            return (
                f"{name} {hexv} fails neutral-gray: needs r == g and b >= g; "
                f"got r={r} g={g} b={b}"
            )
        return None
    if clamp in ("verdict", "surface"):
        return None
    return f"{name}: unknown clamp role {clamp!r}"


def rust_tokens(doc: dict) -> list[dict]:
    """The tokens that reach the terminal, in declaration order.

    A token declares a `rust` name when the TUI renders it. The web-only ones
    -- the below-canvas backdrop, the gold-on-paper text stop, the five-step
    light ramp and the four status inks -- do not, and must not: every entry in
    the generated `ALL` table needs a 256-colour fallback pinned by
    `stella-tui-theme`'s tests, and inventing an ANSI approximation of a paper
    tint the terminal never draws would be an assertion about nothing.

    The alternative was to leave those values out of the system entirely, which
    is what `main` does -- and it means the only file that knows the site's
    warning hue is the site, unclamped and uncheckable. Declaring them here
    puts them under the same hue predicates as everything else while leaving
    `generated.rs` byte-identical, because every token that had a `rust` name
    before this still has one.
    """
    return [tok for tok in doc["tokens"] if tok.get("rust")]


def validate(doc: dict) -> list[str]:
    """Every token against its declared clamp. Returns the failures."""
    errors: list[str] = []
    clamps = doc["clamps"]
    seen: dict[str, str] = {}
    for tok in doc["tokens"]:
        clamp = tok["clamp"]
        if clamp not in clamps:
            errors.append(f"{tok['name']}: clamp {clamp!r} is not declared in `clamps`")
            continue
        err = check_clamp(tok["name"], tok["hex"], clamp, clamps[clamp])
        if err:
            errors.append(err)
        # A hex used twice under two names is how a role quietly loses meaning.
        prior = seen.get(tok["hex"].upper())
        if prior:
            errors.append(f"{tok['name']}: hex {tok['hex']} already used by {prior}")
        seen[tok["hex"].upper()] = tok["name"]
    # The banned list must not name a live token: that would make the guard
    # unsatisfiable, and an unsatisfiable guard gets deleted rather than fixed.
    live = {t["hex"].upper() for t in doc["tokens"]}
    for entry in doc["banned"]["values"]:
        if entry["hex"].upper() in live:
            errors.append(f"banned hex {entry['hex']} is also a live token")
    return errors


# ── Emitters ────────────────────────────────────────────────────────────────


def render_css(doc: dict) -> str:
    lines = [
        "/*",
        " * The stella colour system -- every custom property, one ground truth.",
        " *",
        " * GENERATED by scripts/gen-tokens.py from design/tokens/stella-tokens.json.",
        " * Do not edit this file. Edit the JSON and run `make tokens-update`.",
        " *",
        f" * System: {doc['name']} v{doc['version']}.",
        f" * Supersedes {doc['supersedes']['kit']} ({doc['supersedes']['brand_hex']} on",
        f" * {doc['supersedes']['ground_hex']}) -- see the JSON's `supersedes` block for why",
        " * both of that kit's anchor values sit outside this system's hue clamp.",
        " */",
        "",
        ":root {",
    ]
    for tok in doc["tokens"]:
        lines.append(f"  {tok['css']}: {tok['hex']}; /* {tok['role']} */")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def render_rust(doc: dict) -> str:
    clamps = doc["clamps"]
    resting = clamps["resting-gold"]
    lifted = clamps["lifted-gold"]

    def doc_block(text, indent: str = "//! ") -> list[str]:
        if isinstance(text, str):
            text = [text]
        return [f"{indent}{line}".rstrip() for line in text]

    out: list[str] = [
        "//! The palette and its hue clamp -- SPEC-stella-tui-v2.md sections 3.1 and 3.2.",
        "//!",
        "//! GENERATED by `scripts/gen-tokens.py` from `design/tokens/stella-tokens.json`.",
        "//! Do not edit this file. Edit the JSON and run `make tokens-update`.",
        "//!",
        "//! Every value is [`Color::Rgb`]; there are no indexed or named colours here,",
        "//! because the clamp can only speak about channels. [`ALL`] pairs each token",
        "//! with the [`Clamp`] its value is held to, and the tests at the bottom walk",
        "//! that table -- so a new hex cannot enter the palette without declaring what",
        "//! kind of colour it is, and the warm-drift predicates reject the declaration",
        "//! that would kill the scheme.",
        "",
        "use ratatui::style::Color;",
        "",
        "// ── Clamp bounds ─────────────────────────────────────────────────",
        "",
        "/// The green ratio a gold must clear, as a percentage of red.",
        "///",
    ]
    out += doc_block(resting["why"], "/// ")
    out += [
        f"pub const GOLD_GREEN_PCT: u32 = {resting['green_pct']};",
        "",
        "/// The blue ceiling a resting gold must stay under, as a percentage of red.",
        f"pub const GOLD_BLUE_PCT: u32 = {resting['blue_pct']};",
        "",
        "/// The blue ceiling for the *lift* -- the one gold that sits above",
        "/// [`GOLD_BLUE_PCT`], used only for single-cell live indicators.",
        "///",
    ]
    out += doc_block(lifted["why"], "/// ")
    out += [
        f"pub const GOLD_LIFT_BLUE_PCT: u32 = {lifted['blue_pct']};",
        "",
        "// ── Tokens ─────────────────────────────────────────────────────────",
        "",
    ]
    for tok in rust_tokens(doc):
        r, g, b = channels(tok["hex"])
        out += [
            f"/// {tok['role'][0].upper()}{tok['role'][1:]}. `{tok['hex']}`",
            f"pub const {tok['rust']}: Color = Color::Rgb(0x{r:02X}, 0x{g:02X}, 0x{b:02X});",
            "",
        ]

    out += [
        "// ── The walkable table ─────────────────────────────────────────────",
        "",
        "/// Which predicate a token's value is held to.",
        "///",
        "/// The role is declared per token in the source JSON rather than inferred from",
        "/// the name, because inference is what lets a warm hex in under a cool name.",
        "#[derive(Debug, Clone, Copy, PartialEq, Eq)]",
        "pub enum Clamp {",
        "    /// `r > g > b`, `100 g >= GOLD_GREEN_PCT r`, `100 b <= GOLD_BLUE_PCT r`.",
        "    RestingGold,",
        "    /// The resting clamp with [`GOLD_LIFT_BLUE_PCT`] in place of the blue ceiling.",
        "    LiftedGold,",
        "    /// `b > r` and `g >= r` -- the second metal, never warm.",
        "    CoolSilver,",
        "    /// `r == g` and `b >= g` -- neutral, or tipped toward blue, never toward red.",
        "    NeutralGray,",
        "    /// Pass and fail. Deliberately neither metal nor gray; no channel predicate.",
        "    Verdict,",
        "    /// A tint carrying a sign column, not a hue in a role; no channel predicate.",
        "    Surface,",
        "}",
        "",
        "/// Every token, paired with its name and the clamp it must satisfy.",
        "pub const ALL: &[(&str, Color, Clamp)] = &[",
    ]
    variant = {
        "resting-gold": "Clamp::RestingGold",
        "lifted-gold": "Clamp::LiftedGold",
        "cool-silver": "Clamp::CoolSilver",
        "neutral-gray": "Clamp::NeutralGray",
        "verdict": "Clamp::Verdict",
        "surface": "Clamp::Surface",
    }
    for tok in rust_tokens(doc):
        out.append(f'    ("{tok["name"]}", {tok["rust"]}, {variant[tok["clamp"]]}),')
    out += [
        "];",
        "",
        "// ── Predicates ───────────────────────────────────────────────────",
        "",
        "/// Split a colour into its channels, or `None` if it is not a 24-bit value.",
        "///",
        "/// Every token here is [`Color::Rgb`] by construction, so `None` means a caller",
        "/// handed us an ANSI or indexed colour -- which no clamp can speak about.",
        "#[must_use]",
        "pub const fn channels(color: Color) -> Option<(u8, u8, u8)> {",
        "    match color {",
        "        Color::Rgb(r, g, b) => Some((r, g, b)),",
        "        _ => None,",
        "    }",
        "}",
        "",
        "/// The half of the gold clamp both bounds share: descending channels and the",
        "/// green ratio that separates gold from orange.",
        "#[must_use]",
        "const fn gold_shape(r: u8, g: u8, b: u8) -> bool {",
        "    r > g && g > b && 100 * (g as u32) >= GOLD_GREEN_PCT * (r as u32)",
        "}",
        "",
        "/// Does this colour belong to the resting gold role?",
        "#[must_use]",
        "pub const fn is_resting_gold(r: u8, g: u8, b: u8) -> bool {",
        "    gold_shape(r, g, b) && 100 * (b as u32) <= GOLD_BLUE_PCT * (r as u32)",
        "}",
        "",
        "/// Does this colour belong to the lifted gold role?",
        "#[must_use]",
        "pub const fn is_lifted_gold(r: u8, g: u8, b: u8) -> bool {",
        "    gold_shape(r, g, b) && 100 * (b as u32) <= GOLD_LIFT_BLUE_PCT * (r as u32)",
        "}",
        "",
        "/// Is this colour a cool silver -- the second metal, never warm?",
        "#[must_use]",
        "pub const fn is_cool_silver(r: u8, g: u8, b: u8) -> bool {",
        "    b > r && g >= r",
        "}",
        "",
        "/// Is this colour a neutral or blue-tipped gray?",
        "#[must_use]",
        "pub const fn is_neutral_gray(r: u8, g: u8, b: u8) -> bool {",
        "    r == g && b >= g",
        "}",
        "",
        "/// Does `color` satisfy `clamp`? [`Clamp::Verdict`] and [`Clamp::Surface`]",
        "/// assert nothing, so they hold for any 24-bit value.",
        "#[must_use]",
        "pub const fn satisfies(color: Color, clamp: Clamp) -> bool {",
        "    let Some((r, g, b)) = channels(color) else {",
        "        return false;",
        "    };",
        "    match clamp {",
        "        Clamp::RestingGold => is_resting_gold(r, g, b),",
        "        Clamp::LiftedGold => is_lifted_gold(r, g, b),",
        "        Clamp::CoolSilver => is_cool_silver(r, g, b),",
        "        Clamp::NeutralGray => is_neutral_gray(r, g, b),",
        "        Clamp::Verdict | Clamp::Surface => true,",
        "    }",
        "}",
        "",
        "#[cfg(test)]",
        "mod tests {",
        "    use super::*;",
        "",
        "    /// The anti-drift test SPEC 3.2 asks for: every shipped token against the",
        "    /// predicate it declares. This is what makes the palette unable to rot.",
        "    #[test]",
        "    fn every_token_satisfies_its_clamp() {",
        "        for (name, color, clamp) in ALL {",
        "            assert!(",
        "                satisfies(*color, *clamp),",
        '                "{name} ({color:?}) violates {clamp:?}"',
        "            );",
        "        }",
        "    }",
        "",
        "    /// The retired brand metals must still fail, or the clamp has gone slack.",
        "    /// Bronze Gold is the live case: it is what this system supersedes.",
        "    #[test]",
        "    fn retired_brand_golds_are_rejected() {",
        "        // #C58A32 -- brand v4.0 Bronze Gold. 100*g = 13800, 78*r = 15366.",
        "        assert!(!is_resting_gold(0xC5, 0x8A, 0x32));",
        "        assert!(!is_lifted_gold(0xC5, 0x8A, 0x32));",
        "        // #FFB000 -- brand v1.0 Phosphor Gold.",
        "        assert!(!is_resting_gold(0xFF, 0xB0, 0x00));",
        "        // #070B10 -- brand v4.0 Obsidian. Green-tipped, so not a neutral gray.",
        "        assert!(!is_neutral_gray(0x07, 0x0B, 0x10));",
        "    }",
        "",
        "    /// The lift is an exception with a tight bound, not an open door: a gold",
        "    /// one point bluer than `gold_bright` still fails it.",
        "    #[test]",
        "    fn the_gold_lift_is_bounded() {",
        "        assert!(",
        "            is_lifted_gold(0xF7, 0xD9, 0x6B),",
        '            "gold_bright must pass the lift"',
        "        );",
        "        assert!(",
        "            !is_resting_gold(0xF7, 0xD9, 0x6B),",
        '            "and must fail the resting clamp"',
        "        );",
        "        assert!(",
        "            !is_lifted_gold(0xF7, 0xD9, 0x6D),",
        '            "two points bluer must fail"',
        "        );",
        "    }",
        "}",
        "",
    ]
    return "\n".join(out)


# ── Driver ──────────────────────────────────────────────────────────────────


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--check",
        action="store_true",
        help="fail if a generated file is stale instead of writing it",
    )
    args = ap.parse_args()

    doc = json.loads(TOKENS.read_text())

    errors = validate(doc)
    if errors:
        print("token validation failed:", file=sys.stderr)
        for err in errors:
            print(f"  {err}", file=sys.stderr)
        return 1

    outputs = {CSS_OUT: render_css(doc), RUST_OUT: render_rust(doc)}

    stale: list[Path] = []
    for rel, content in outputs.items():
        path = REPO / rel
        if args.check:
            if not path.exists() or path.read_text() != content:
                stale.append(rel)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)

    # The emitted Rust must already be rustfmt-clean. Nothing else enforces the
    # coupling, and getting it wrong is quiet in the worst way: `make
    # tokens-update` would write a file that `format-check` then rejects, so the
    # only way to a green gate would be to hand-edit a generated file — which is
    # precisely what the "do not edit" banner forbids, and the tree would have
    # taught the next author to ignore it. Checked rather than remembered.
    if shutil.which("rustfmt"):
        probe = subprocess.run(
            ["rustfmt", "--edition", "2024", "--emit", "stdout", "--quiet"],
            input=outputs[RUST_OUT],
            capture_output=True,
            text=True,
        )
        if probe.returncode != 0:
            print(f"rustfmt refused the generated Rust:\n{probe.stderr}", file=sys.stderr)
            return 1
        if probe.stdout != outputs[RUST_OUT]:
            print(
                f"the generated Rust is not rustfmt-clean. Fix the emitter in "
                f"{Path(__file__).name} — do not format {RUST_OUT} by hand, it is "
                f"overwritten on every run.",
                file=sys.stderr,
            )
            return 1

    if args.check:
        if stale:
            print("generated colour artifacts are stale:", file=sys.stderr)
            for rel in stale:
                print(f"  {rel}", file=sys.stderr)
            print(
                "\nrun `make tokens-update` and commit the result.",
                file=sys.stderr,
            )
            return 1
        print(f"tokens: {len(doc['tokens'])} validated, {len(outputs)} artifacts in sync")
    else:
        for rel in outputs:
            print(f"wrote {rel}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
